### ISSUE TITLE
Links suggestions missed some files

### ISSUE THREAD

**Issue by HynDuf** [epwalsh/obsidian.nvim#102]
### 🐛 Describe the bug

I have a `00. Home/🏡 Homepage.md` file in my specified vault folder, but when I type `[[Homepage`, it didn't suggest it. It missed the file or Is it what it supposed to be?

![image](https://user-images.githubusercontent.com/29995756/225469847-88bf9cef-720a-4016-9d0b-ee1e3d1b47d7.png)

Thanks in advance.

### Versions

NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
1.8.0%

**Comment by epwalsh** [comment]
I'm guessing it's an issue with the spaces or emojis in the file name. Let's try to narrow it down. Can you see if it works for a file without an emoji in the name, within the same folder?

**Comment by HynDuf** [comment]
> I'm guessing it's an issue with the spaces or emojis in the file name. Let's try to narrow it down. Can you see if it works for a file without an emoji in the name, within the same folder?

Hmm it didn't work for `Homepage.md` or `Homepage1.md` in the same folder `00. Home` too. 

![image](https://user-images.githubusercontent.com/29995756/225479666-0b28d01b-6ff7-4f04-8a2e-14074fc3cb3e.png)

It didn't work with folder `00.Home` (without the middle space) too.

![image](https://user-images.githubusercontent.com/29995756/225479900-5df719f9-0eb0-4f2b-bd3e-1b6e197242ff.png)

It didn't work in vault root folder too

![image](https://user-images.githubusercontent.com/29995756/225480052-dff6ba71-e97f-4eba-8a7c-e488858caff0.png)

**Comment by epwalsh** [comment]
Hmm... do these notes not have frontmatter?

**Comment by epwalsh** [comment]
I was able to reproduce this when `aliases` was not defined or set to an empty list `[]` in the frontmatter. #103 fixes that case. Let me know if you're still having issues after that and I'll reopen.

**Comment by HynDuf** [comment]
> I was able to reproduce this when `aliases` was not defined or set to an empty list `[]` in the frontmatter. #103 fixes that case. Let me know if you're still having issues after that and I'll reopen.

Thanks a lot for your time. 

It's now getting the files already but it produces weird aliases for files with no (or empty) `aliases` in the frontmatter.

- Duplicated file name as aliases: 
![image](https://user-images.githubusercontent.com/29995756/225768960-a5b27b21-a84a-4170-a8ad-7ed8ae7813bd.png)

- Couldn't get `Homepage1.md` if `Homepage1.md` is empty or have a few characters (like `page` below).
![image](https://user-images.githubusercontent.com/29995756/225769425-84a3fd6e-d277-4de8-83ad-8a8278ba3910.png)

- Get headings of notes into aliases (is this intended?). The `|` should be `#` for heading though. (`Items` is a heading in `Content Hub`)
![image](https://user-images.githubusercontent.com/29995756/225769607-3a02ba37-131d-4b4a-9b5f-927e9c386eff.png)

**Comment by epwalsh** [comment]
> Duplicated file name as aliases

That should be a quick fix.

> Couldn't get Homepage1.md if Homepage1.md is empty or have a few characters (like page below).

That's odd. I'll try to repro that.

> Get headings of notes into aliases (is this intended?). The | should be # for heading though. (Items is a heading in Content Hub)

Obsidian will assume the first H1 heading is the title of the note, so this is intended. But you should also get something like `[[Content Hub|Content Hub]]` as a suggestion. If not, that's a bug.

**Comment by epwalsh** [comment]
Ah, `Homepage1.md` isn't coming up because the search only searches file content, not file names. Should be straightforward to do both.

**Comment by HynDuf** [comment]
> > Duplicated file name as aliases
> 
> That should be a quick fix.
> 
> > Couldn't get Homepage1.md if Homepage1.md is empty or have a few characters (like page below).
> 
> That's odd. I'll try to repro that.
> 
> > Get headings of notes into aliases (is this intended?). The | should be # for heading though. (Items is a heading in Content Hub)
> 
> Obsidian will assume the first H1 heading is the title of the note, so this is intended. But you should also get something like `[[Content Hub|Content Hub]]` as a suggestion. If not, that's a bug.

Is it the first H1 heading or the first heading? `Items` is the first H2 heading of my note. But it would be fine if it also suggests `[[Content Hub]]` so I would choose that anyway and ignore those redundancies.

![image](https://user-images.githubusercontent.com/29995756/225774914-1ba2efdb-821b-441f-b181-0c0ebce0a4c7.png)

**Comment by epwalsh** [comment]
Ok just opened #104 to fix those issues.

**Comment by HynDuf** [comment]
Thanks so much. It works fine now. Really appreciate.

**Comment by epwalsh** [comment]
No problem!
