### ISSUE TITLE
Option to bring Obsidian.app to foreground on opening a note (macos)

### ISSUE THREAD

**Issue by zhengpd** [epwalsh/obsidian.nvim#109]
### 🚀 The feature, motivation and pitch

Currently calling `ObsidianOpen` keeps Obsidian.app in background and this behavior is not configurable. It would be helpful if there is option to bring Obsidian to foreground, something like:

```
require'obsidian'.setup { open_app_foreground = true }
```

### Additional context

- platform: macos

**Comment by epwalsh** [comment]
Happy to accept a PR on this
