### ISSUE TITLE
I install with lazy.nvim and obsidian.txt help page is not exist

### ISSUE THREAD

**Issue by devstefancho** [epwalsh/obsidian.nvim#114]
### 🐛 Describe the bug

Hello!

I don't know if this is a bug or not, but I need your help searching doc
I use lazy.nvim and I successfully install obsidian.nvim but the help page does not exist ( I want to read the doc in vim)
Here is my config
```lua
return {
  {
    "epwalsh/obsidian.nvim",
    tag = "1.*",
    config = function()
      require("obsidian").setup({
        dir = "~/iCloud/Documents/my-vault",
        notes_subdir = "notes",
      })
    end,
  },
}
```

I try `:h obsidian.txt` and also `:h obs` then try tab key to auto complete, but obsidian doc is not exist

the screenshot is about searching the help page with telescope
<img width="2082" alt="image" src="https://user-images.githubusercontent.com/61320923/228580299-4d0b8e25-bbe1-495c-a067-883504d0e0f6.png">

<img width="583" alt="image" src="https://user-images.githubusercontent.com/61320923/228582145-3bd92e21-a967-4ecf-898d-0ed537759aa1.png">

### Versions

```
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-005.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.2/share/nvim"

Run :checkhealth for more info
1.8.0
[NvimTree] "open_on_setup behaviour has been deprecated, please see https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup"%
```

**Comment by epwalsh** [comment]
Hmm that's odd. @folke, do you have any ideas?

**Comment by folke** [comment]
Op probably has set config.defaults.lazy = true.

Either change that or add lazy=false to the spec for obsidian. Help files in neovim are only available for loaded plugins
