### ISSUE TITLE
[FR] Set working directory to vault

### ISSUE THREAD

**Issue by daveriedstra** [epwalsh/obsidian.nvim#119]
### 🚀 The feature, motivation and pitch

Proposal: set the current working directory to the vault's directory when the plugin is loaded in a subdirectory of the vault.

My vault is organized into subdirectories. I often find myself having opened a note in a subdirectory directly, as opposed to navigating to the vault, opening nvim, and then opening the note. There are several nvim and plugin features which benefit from having a relevant working directory / CWD when interacting with notes across subdirectories:

- path completion (relevant to #75)
- path following (ie, `gf`'s default behaviour)
- search
- directory overview (eg, plugins like nerdtree)

Setting the working directory would allow users to take full advantage of these features.

Thanks for the fantastic plugin!

**Comment by epwalsh** [comment]
Hey @daveriedstra, I'm happy to accept a PR for this. I'd like to keep it an optional feature, however it might make sense to make this the default behavior.

**Comment by daveriedstra** [comment]
Thanks! I'll give it a shot if I can find the time.

**Comment by metalelf0** [comment]
For this, I use [ahmedkhalf/project.nvim](https://github.com/ahmedkhalf/project.nvim). Here's my config (lazy.nvim format):

```lua
local M = {
	"ahmedkhalf/project.nvim",
	event = "VeryLazy",
}

M.config = function()
	local project = require("project_nvim")
	project.setup({
		active = true,
		on_config_done = nil,
		manual_mode = false,
		detection_methods = { "pattern" },
		patterns = { ".git", "_darcs", ".hg", ".bzr", ".svn", "Makefile", "package.json", ".project_root" },
		show_hidden = false,
		silent_chdir = true,
		ignore_lsp = {},
	})

	local telescope = require("telescope")
	telescope.load_extension("projects")
end

return M
```

This way, when I open a file and one of its parent directories contains a file that matches one of the `patterns`, the directory is changed.

**Comment by epwalsh** [comment]
Unless I'm misunderstanding the feature request, this has been implemented via the `config.workspaces` and `config.detect_cwd` options.
