### ISSUE TITLE
Graph Formatting

### ISSUE THREAD

**Issue by kylechui** [epwalsh/obsidian.nvim#120]
### 🐛 Describe the bug

Hi there! I'm a new user of this plugin (and Obsidian in general). I didn't see any Discussions tab, so I figured I'd ask here. From what I can gather, the file names are hashed in order to prevent collisions, so the links always match up properly (i.e. if you had multiple files named `hello.md`). However, now my graph looks like the following:

![image](https://user-images.githubusercontent.com/48545987/229692137-f7fb9b79-eb85-4e10-bea7-70965a39c2ed.png)

Is there some way to "prettify" the graph to make it understand what the files are *supposed* to be, maybe via reading the first header? Thanks a bunch in advance, and thanks for creating this plugin!

### Versions

Latest version of Neovim nightly.

**Comment by epwalsh** [comment]
Hey @kylechui, as far as I know there's still no way to configure the graph that way. Alternatively you can customize the note naming function in Neovim to create more readable names. See https://github.com/epwalsh/obsidian.nvim#customizing-note-paths-and-ids. That's what I have in my personal configuration.

**Comment by kylechui** [comment]
Thanks for the quick response; I think I'll settle for something like `TOPIC_NAME_DATE` or something like that.
