### ISSUE TITLE
cmp not picking obsidian completion `unused source`

### ISSUE THREAD

**Issue by TheSafdarAwan** [epwalsh/obsidian.nvim#124]
### 🐛 Describe the bug

Obsidian is not being added to the source list in the cmp. I manually added the `obsidian` source to the cmp and it worked.
using `[[` doesn't give the completion.

### Versions

NVIM v0.10.0-dev-118+g59fed8bb6
Build type: RelWithDebInfo
1.8.0

**Comment by epwalsh** [comment]
Thanks @TheSafdarAwan, this may be due to an update with `nvim-cmp`. I'll try to reproduce.

**Comment by epwalsh** [comment]
@TheSafdarAwan so far I can't reproduce with the latest commit of `nvim-cmp`. Can you post your config for obsidian and nvim-cmp and the version?

**Comment by TheSafdarAwan** [comment]
@epwalsh This is my [nvim-cmp](https://github.com/TheSafdarAwan/nvim_conf/blob/master/lua/safdar/setup/completion/nvim-cmp/config.lua) config. and this is my [obsidian.nvim](https://github.com/TheSafdarAwan/nvim_conf/blob/master/lua/safdar/setup/writing/obsidian-nvim/init.lua) config.
i am on `main` branches and i have just update both of these.

**Comment by epwalsh** [comment]
Weird.. I'm not sure what's going on. Can you confirm that Obsidian has loaded when you open an MD file in your vault? (Just check for any `:Obsidian*` command).

If Obsidian has indeed loaded but completion is not working, can you run this lua script from an MD file in your vault? Just save it to `tmp.lua` or something, then call `:luafile tmp.lua` from neovim.

```lua
local cmp = require("cmp")

for _, source in pairs(cmp.get_config().sources) do
	print(source.name)
end
```

**Comment by TheSafdarAwan** [comment]
> 

this is the output

```
nvim_lsp
neorg
luasnip
buffer
nvim_lua
emoji
cmp_tabnine

```

**Comment by epwalsh** [comment]
But `:Obsidian*` commands work? In that case it seems like `nvim-cmp` is being loaded/configured after Obsidian? Here is my [cmp config](https://github.com/epwalsh/dotfiles/blob/235727a10fd3962bcb35fccd4d03767048e54e12/neovim/lua/plugins/completion.lua#L1) if that helps.

But it's totally fine to manually add `obsidian` as a cmp source if that works for you, just make sure you set it up in the same way that Obsidian does (i.e. pass the same `opts` that you pass to `obsidian.setup(...)`):

https://github.com/epwalsh/obsidian.nvim/blob/1a29569952cce9b4838ffbc7be5d343f50d049a6/lua/obsidian/init.lua#L78-L81

**Comment by AXGKl** [comment]
Hi, for lazy I think this would not hurt:

```lua
  { "epwalsh/obsidian.nvim", dependencies = "hrsh7th/nvim-cmp", ft = "markdown" },
```

In my case, w/o that, I had the opposite problem w/o the dep.: *Only* obs. refs worked - but nothing else, though listed in your testscript output.

**Comment by TheSafdarAwan** [comment]
@epwalsh yeah, now that you mentioned i think that is the cause for it. I am lazy loading cmp on `InsertEnter` event.

**Comment by epwalsh** [comment]
@AXGKl @TheSafdarAwan thank you both, this sounds like it could become a common issue so I'll add a note about this to the README
