### ISSUE TITLE
"Frontmatter skipped" notification spam

### ISSUE THREAD

**Issue by gregorias** [epwalsh/obsidian.nvim#127]
### 🐛 Describe the bug

I have set `disabled_frontmatter` to true and since https://github.com/epwalsh/obsidian.nvim/commit/66651b5b67f39bdc0ed17bd394691687e9d4a9f4 I'm getting visible notifications that ["Frontmatter skipped"](https://github.com/epwalsh/obsidian.nvim/blob/c4a04747c05de62ec198def16a0565956d390de9/lua/obsidian/init.lua#L114).

Since I tend write a file often, this is spammy. I believe this notification should be configurable.

Plugin is sending me messages that it has done nothing on a setting I've explicitly toggled; I don't think it's a good idea to send it on every write. If you don't want to disable it, perhaps use `notify_once`?

### Versions

N/A

**Comment by epwalsh** [comment]
Ah, yea that's annoying. I'll just take that out. 0418505
