### ISSUE TITLE
Support for multiple vaults

### ISSUE THREAD

**Issue by sadtab** [epwalsh/obsidian.nvim#128]
### 🚀 The feature, motivation and pitch

The title says it all !

Great plug BTW, almost replaced the Obsidian app for me, I used the app just to visualize the graphs

**Comment by epwalsh** [comment]
Thanks @sadtab! At the moment I think you could just call `obsidian.setup({...})` for each vault directory separately and it should work. Have you tried that, or did you have something else in mind?

**Comment by sadtab** [comment]
I was thinking of something like [Neorg](https://github.com/nvim-neorg/neorg), You may have this plug already. What it does, is it can have multiple `workspaces` :
```lua
            config = {
                workspaces = {
                    work = "~/notes/work",
                    home = "~/notes/home",
                }
            }
```
Other than that, calling the `obsidian.setup({...})` with different paths seems like a decent workaround

**Comment by aniketgm** [comment]
> At the moment I think you could just call `obsidian.setup({...})` for each vault directory separately and it should work.

I'm not sure how to do this. Do you mean changing the `dir` option each time when I want to switch to another vault ? A short example config would be helpful. I'm new to neovim. In the GUI Obsidian, I have two vaults "Work" and "Personal".

**Comment by epwalsh** [comment]
Hey @aniketgm, I mean calling `obsidian.setup({})` twice in your `init.nvim` / `init.lua`. Like this for example:

```lua
obsidian.setup({
  dir = "~/notes/work",
  ...
})

obsidian.setup({
  dir = "~/notes/home",
  ...
})
```

**Comment by vimcki** [comment]
i wanted to be able to select between 2 vaults, this telescope picker allows you to pick one of 2 vaults. It switches current directory and calls `require("obsidian").setup(obsopts)` with proper `obsopts.dir`. At the end there is auto group to call this picker on startup.
```lua
local pickers = require "telescope.pickers"
local finders = require "telescope.finders"
local conf = require("telescope.config").values
local actions = require "telescope.actions"
local action_state = require "telescope.actions.state"

obsopts = {
...
}

obsidian_picker = function(opts)
	opts = opts or {}
	pickers.new(opts, {
		prompt_title = "vaults",
		finder = finders.new_table {
			results = { "vault1", "vault2" }
		},
		sorter = conf.generic_sorter(opts),
		attach_mappings = function(prompt_bufnr, map)
			actions.select_default:replace(function()
				actions.close(prompt_bufnr)
				local selection = action_state.get_selected_entry()[1]
				local dir
				if selection == "valut1" then
					dir = <path to vault1>
				elseif selection == "vault2" then
					dir = <path to vault2>
				end
				vim.api.nvim_set_current_dir(dir)
				obsopts.dir = dir
				require("obsidian").setup(obsopts)
			end)
			return true
		end,
	}):find()
end

vim.cmd([[
	augroup InitPicker
	autocmd!
	autocmd VimEnter * lua obsidian_picker()
	augroup END
]])
```

**Comment by weskoerber** [comment]
Calling `obsidian.setup({})` twice seems to have overridden the first call. In other words, it just causes `~/notes/work` to be the working directory.

```lua
obsidian.setup({
  dir = '~/notes/personal'
})

obsidian.setup({
  dir = '~/notes/work'
})
```

Here's how I hacked my way around this:

First, I added a `workspaces` field to the config object:

```lua
local config = {
  workspaces = {
    '/home/wes/Documents/notes/personal',
    '/home/wes/Documents/notes/work',
  },
  finder = 'telescope.nvim'
  -- other obsidian.nvim options...
}
```

Then, I iterate through the workspaces and compare each one to the current directory. If they match, then I pass the workspace directory into the `dir` field in the config and pass that to `obsidian.setup`:

```lua
local setup_obsidian = function()
    for _, val in pairs(config.workspaces) do
        if vim.fs.normalize(val) == vim.fn.getcwd() then
            obsidian.setup(vim.tbl_extend('error', config, {dir = val}))
            break
        end
    end
end
```

Finally, at the end of the file, I call `setup_obsidian`:

```lua
setup_obsidian()
```

**Comment by epwalsh** [comment]
@weskoerber thanks for that. Interested in making a PR with this feature?

**Comment by weskoerber** [comment]
> @weskoerber thanks for that. Interested in making a PR with this feature?

Sure!

**Comment by larrybotha** [comment]
thanks @weskoerber - I've written a similar init script based on yours that has a few differences:

- includes an autocommand that will initialise `obsidian.nvim` with the correct vault if you cd elsewhere
- will initialise `obsidian.nvim` when opening vim at any depth inside an obsidian vault

```lua
local obsidian = require("obsidian")

local vaults_dir = "~/projects/obsidian-vaults"
local options = {}

local function configure_obsidian(root_dir, cwd)
	local vaults = {}
	local vault_dir = nil
	local dirs = { cwd }

	for dir in vim.fs.dir(root_dir) do
		local path = vim.fn.expand(string.format("%s/%s", root_dir, dir))
		vaults[path] = true
	end

	for x in vim.fs.parents(cwd) do
		table.insert(dirs, x)
	end

	for _, x in pairs(dirs) do
		local is_match = vaults[x]

		if is_match then
			vault_dir = x
			break
		end
	end

	if vault_dir then
		local workspace_options = vim.tbl_extend("force", options, { dir = vault_dir })

		obsidian.setup(workspace_options)
	end
end

local au_group = vim.api.nvim_create_augroup("ObsidianAutogroup", { clear = true })

vim.api.nvim_create_autocmd("DirChanged", {
	pattern = "*",
	group = au_group,
	callback = function()
		configure_obsidian(vaults_dir, vim.fn.getcwd())
	end,
	desc = "Re-initialises Obsidian when the working directory changes",
})

configure_obsidian(vaults_dir, vim.fn.getcwd())
```

My Lua-fu is pretty weak, so I'm sure there are more elegant ways of populating / evaluating tables.

One improvement to this would be to uninit `obsidian.nvim` if cd'ing to a folder that isn't in a vault.

**Comment by enrico223** [comment]
@larrybotha I am trying to use you script, but I am missing something because `:ObsidianOpen` doesn't find any vault. Here my [obsidian.lua](https://github.com/enrico223/.config/blob/master/nvim/plugin/obsidian.lua). Should I insert my vaults in `local vault_dirs = {}`?

**Comment by larrybotha** [comment]
@enrico223 your script looks ok, but if `:ObsidianOpen` is not opening it _may_ be because Neovim wasn't opened from inside one of your vault folders. If that's the case, you should get a `Not an editor command: ObsidianOpen` error

The `vault_dirs` table is populated at https://github.com/enrico223/.config/blob/987e45b651c791aeb9b7f0490636f1f5ea2ba9f7/nvim/plugin/obsidian.lua#L86-L89 from the parent vault directory - you could populate it yourself, but by providing a parent folder you can add and remove vaults as you want without changing your dotfiles, until you change where your vaults are stored on your machine

What I'd recommend is:

- cd to one of your vault directories
- open Neovim from that directory (at this point it _should_ be working, but it seems it may not be for you)
- in Neovim open your `obsidian.lua` file for editing
- start with the simplest case - replace the options passed to the `configure_obsidian` function with an empty table in https://github.com/enrico223/.config/blob/987e45b651c791aeb9b7f0490636f1f5ea2ba9f7/nvim/plugin/obsidian.lua#L127-L132 
    ```lua
    -- ...
    configure_obsidian(vault_dirs, {}})
    ``` 
- use print statements to evaluate the vault dirs etc. in the `configure_obsidian` function:
    ```lua
    local function configure_obsidian(vaults, options)
      local cwd = vim.fn.getcwd()
      local dirs = { cwd }
      local vault_dir = nil
      local vault_map = {}

      print("cwd: " .. cwd)

      for _, dir in pairs(vaults) do
        print("dir: " .. dir)
        vault_map[dir] = true
      end
      
      -- ...
    ```

Once you've diagnosed the issue there you can go back to passing in your full options table into the function

**Comment by enrico223** [comment]
@larrybotha thanks, `:ObsidianOpen` works! Now I'll have to figure what in my config is messing with `:ObsidianSearch`
