### ISSUE TITLE
Allow configuring the finder in the plugin setup

### ISSUE THREAD

**Issue by idanarye** [epwalsh/obsidian.nvim#129]
### 🚀 The feature, motivation and pitch

`:ObsidianSearch` is trying - in that order - Telescope, fzf-lua, and fzf.vim:

```lua
command.search = function(client, data)
  local base_cmd = vim.tbl_flatten { util.SEARCH_CMD, { "--smart-case", "--column", "--line-number", "--no-heading" } }

  local has_telescope, telescope = pcall(require, "telescope.builtin")

  if has_telescope then
    -- ...
    return
  end

  local has_fzf_lua, fzf_lua = pcall(require, "fzf-lua")

  if has_fzf_lua then
    -- ...
    return
  end

  -- Fall back to trying with fzf.vim
  local has_fzf, _ = pcall(function()
    -- ...
  end)

  if not has_fzf then
    echo.err "Either telescope.nvim, fzf-lua or fzf.vim is required for :ObsidianSearch command"
  end
end
```

I prefer fzf-lua, but because Telescope is the standard I have it installed for plugins that don't support anything else, so Obsidian will use Telescope on my machine because it's the first in the tryout order.

I would like an option to configure, with a setting, which option `ObsidianSearch` will use. Something like:

```lua
require'obsidian'.setup {
    finder = 'fzf-lua',
}
```

**Comment by epwalsh** [comment]
Hey @idanarye, definitely makes sense! Happy to review a PR here.

**Comment by epwalsh** [comment]
Closed as completed.
