### ISSUE TITLE
Open specific file in nvim

### ISSUE THREAD

**Issue by Vesyrak** [epwalsh/obsidian.nvim#132]
### 🚀 The feature, motivation and pitch

Currently, I assume it is not possible to go to a specific note using obsidian

What I would like to achieve, is binding a `:ObsidianOpenNote <note-id>` to a specific keypress, so that I have that file handy at all times.
This functionality is already available in `:ObsidianOpen <note-id>`, but this opens the file in Obsidian, not in a new buffer.

Thanks in advance!

**Comment by epwalsh** [comment]
Hey @Vesyrak, why not just bind `:e <node-id>.md` or something?
