### ISSUE TITLE
Couldn't find an Obsidian Vault

### ISSUE THREAD

**Issue by camin-mccluskey** [epwalsh/obsidian.nvim#133]
### 🐛 Describe the bug

# Description 

Loving the plugin and finding it really useful but a couple of commands are not functional for me. I imagine all my issues _may_ be related and most likely some issue with my specific set up but any help would be appreciated!

- Running `:ObsidianOpen` fails with message: `[Obsidian] couldn't find an Obsidian vault`
- Running `:ObsidianBacklinks` results in an empty results list on every page (including those with known backlinks)
- _this one may be a misunderstanding on my part regarding how the plugin should be used:_ Using the shortcut `gf` won't follow a link of type `[[<some-page-title>]]`. Using `:ObsidianFollowLink` will follow the link but seemingly it will create a new empty page with an alias to the Obsidian page.
- _as with the above, this may be my misunderstanding_ but I'd expect typing `[[` to allow me to just create a new obsidian markdown note, instead it creates what appears to be a linked note - I'm not sure what the expected workflow is here? Will that linked note stay up-to-date with the Obsidian markdown note it is aliased to? It doesn't appear to for me.

I recognise a) many of the above may not be bugs, I just am not understanding the expected workflow and b) perhaps these all stem from misconfiguring this plugin. 

# Config

_obsidian.lua_
```lua
local options = {
  dir = "/Users/caminmccluskey/Obsidian-camin-vault",
  completion = {
    nvim_cmp = true,
  },
  daily_notes = {
    folder = "Daily",
  },
  templates = {
    subdir = "Templates",
    date_format = "YYYY-MM-DD",
    time_format = "HH:mm",
  },
  -- newly created notes should just use the title as the filename
  note_id_func = function(title)
    local sane_name = ""
    if title ~= nil then
      -- If title is given, transform it into valid file name.
      sane_name = title:gsub(" ", "_"):gsub("[^A-Za-z0-9-]", ""):lower()
    else
      -- If title is nil, just add 4 random uppercase letters to the suffix.
      for _ in 1, 4 do
        sane_name = sane_name .. string.char(math.random(65, 90))
      end
    end
    return sane_name
  end,
  -- b/c configured on Obsidian instance
  use_advanced_uri = true,
  -- forces :ObsidianOpen to bring app to foreground
  -- open_app_foreground = false,
}

return options
```

_plugins.lua_
```lua
local obsidianOpts  = require "custom.configs.obsidian"

  {
    "epwalsh/obsidian.nvim",
    event = { "BufReadPre " .. vim.fn.expand "~" .. "/Obsidian-camin-vault/**.md" },
    opts = obsidianOpts,
    dependencies = {
      "nvim-lua/plenary.nvim",
      "hrsh7th/nvim-cmp",
      "nvim-telescope/telescope.nvim",
    },
    config = function(opts)
      require("obsidian").setup(opts)
    end,
  },

  {
    "hrsh7th/nvim-cmp",
     opts = {
       sources = {
         { name = "obsidian", option = obsidianOpts },
         { name = "obsidian_new", option = obsidianOpts },
       }
     }
  },
```

I'm using NvChad so my configuration is overriding theirs which may be the source of some issues. For example, previously I found I could not get nvim-cmp working without specifying the sources above.

Thanks for your help!

### Versions

nvim version = v0.9.0
Obsidian version = v1.9.0

**Comment by epwalsh** [comment]
Hey @camin-mccluskey it definitely seems like something weird is going on with the setup. All of the issues might stem from the first one you mentioned (Obsidian not being able to find a vault - `[Obsidian] couldn't find an Obsidian vault`). So let's try to figure that one out first.

Can you update Obsidian to the latest commit and then run `:ObsidianCheckHealth`. This will report where the vault directory is configured, so if it's not "/Users/caminmccluskey/Obsidian-camin-vault" then we know that it's being overwritten.

**Comment by camin-mccluskey** [comment]
Thanks for your prompt response!

Running `:ObsidianCheckHealth` returns with: `[Obsidian] FAILED - couldn't find an Obsidian vault in '/Users/caminmccluskey/.local/share/nvim/lazy/obsidian.nvim'`

**Comment by epwalsh** [comment]
Okay that's odd, so somehow the `dir` option in the Obsidian config is being set to `'/Users/caminmccluskey/.local/share/nvim/lazy/obsidian.nvim'`...

**Comment by camin-mccluskey** [comment]
Seems like it yea, I get the same result from `:ObsidianCheckHealth` when I set `dir = ~/Obsidian-camin-vault` also

**Comment by camin-mccluskey** [comment]
Finally had a bit of time to figure this out. My config was off:

Changing this:
```lua
config = function(opts)
      require("obsidian").setup(opts)
   end,
```

To this:
```lua
config = function(_, opts)
      require("obsidian").setup(opts)
   end,
```

Got everything working correctly. This also meant I could take away to nvim-cmp source declaration (as is suggested in the README). We can close this issue but just before that I was wondering if it was possible to create new pages without the prefix and frontmatter related content?

Ideally creating a new note "New Note" using  `:ObsidianLinkNew` would just create a regular obsidian markdown page with the file name `New Note.md` (with no frontmatter content) and link it in the current page as `[[New Note]]` (no prefix). Is this something that is possible using this plugin?

**Comment by camin-mccluskey** [comment]
Now realise I can easily disable the frontmatter issue with the opt `disable_frontmatter = true` and in reality the underlying page created will be titled `New Note.md`. It just appeared with a prefixed link inside Neovim (not Obsidian). Apologies for the confusion and thanks for your help and this great plugin!
