### ISSUE TITLE
Plugin does not `require` properly

### ISSUE THREAD

**Issue by linduxed** [epwalsh/obsidian.nvim#134]
### 🐛 Describe the bug

I copied the default configuration that's included in the `README`, and the plugin does not load at all.

Investigation lead me to notice the following:

1. `require("obsidian")` returns `true`, not a table.
2. `package.loaded.obsidian == true`.

I'm not knowledgable enough about how plugin loading works for me to have any further ideas as to what could be wrong.

I'm using `lazy.nvim` as my package manager.

### Versions

`nvim --version`:
```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

`nvim --headless -c 'lua print("Obsidian v" .. require("obsidian").VERSION)' -c q`:
```
Error detected while processing command line:
E5108: Error executing lua [string ":lua"]:1: attempt to index a boolean value
stack traceback:
	[string ":lua"]:1: in main chunk%                                                                              
```
This error is caused by the problem described above, with the plugin just being loaded as `true`.

**Comment by epwalsh** [comment]
Do you have another Lua module somewhere called "obsidian"?

**Comment by linduxed** [comment]
Indeed!

I had an idea some time ago to write my own `obsidian.nvim`, so I had placed an `obsidian.lua` file in my Neovim configuration `lua/` directory, for experimentation purposes. I had totally forgotten about this file.

Since this project does all I ever intended to build and more, I guess I can remove that file :wink:.

Problem solved!
