### ISSUE TITLE
Create new notes with path from vault directory

### ISSUE THREAD

**Issue by mscott99** [epwalsh/obsidian.nvim#147]
### 🚀 The feature, motivation and pitch

I use links within my templates with a path: [[Daily\ Notes/2023-06-06.md]] to create notes at a specific location when I follow the link (this is a "tomorrow" and "yesterday" link in my daily note). Currently this creates a note with the notes folder as the base; I think it should be the vault folder instead, to match the behaviour of Obsidian.

**Comment by epwalsh** [comment]
Hey @mscott99, let me make sure my understanding is correct:

So you have the `notes_subdir` option configured in Obsidian.nvim, and when you follow a link like `[[Daily\ Notes/2023-06-06.md]]` that doesn't exist yet, Obsidian.nvim will create that note in `notes_subdir / "Daily Notes" / "2023-06-06.md"` instead of just `"Daily Notes" / "2023-06-06.md"`?

**Comment by mscott99** [comment]
Yes that's right, exactly.

**Comment by epwalsh** [comment]
Ok, got it. I'll try to make this functionality more robust in general. Working on a PR.

**Comment by epwalsh** [comment]
@mscott99 can you check that #148 fixes before I merge?

**Comment by epwalsh** [comment]
@mscott99 I went ahead and merged #148. Let me know if you still find issues.

**Comment by mscott99** [comment]
Hi! Sorry for not being responsive. I cloned and tried it, and it does not seem to work for me. It seems to still be taking the path as being relative to the note-subdir, instead of the vault root.

**Comment by mscott99** [comment]
I checked an if statement in your pr, my daily notes folder is actually two folders deep /Temporal/Daily\ Notes/. Also my notes_subdir is defined, so it does not match the cases. Would it be easy to make it so that any time there is a path in the link it defaults to the relative path from the vault folder?

**Comment by mscott99** [comment]
I was thinking that new notes should NOT be in the notes folder when a path is specified, even if the notes_subdir is given.

**Comment by epwalsh** [comment]
> Would it be easy to make it so that any time there is a path in the link it defaults to the relative path from the vault folder? ... I was thinking that new notes should NOT be in the notes folder when a path is specified, even if the notes_subdir is given.

Yea I think that's okay. I was trying to avoid that at first because I thought users might want something like `[[subfolder/note.md]]` to actually end up in `notes_subdir/subfolder/note.md`, but in that case they could just use the full path. I'll cut a new PR.

**Comment by epwalsh** [comment]
Ok, https://github.com/epwalsh/obsidian.nvim/pull/151 implements that logic.
