### ISSUE TITLE
Allow customizing daily notes path

### ISSUE THREAD

**Issue by metalelf0** [epwalsh/obsidian.nvim#15]
### 🚀 The feature, motivation and pitch

In Obsidian, I customized my daily notes path to a subfolder of the main space. I'd like to be able to set it as a custom option in `obsidian.nvim`, so that when I type `:ObsidianToday`, it creates the daily note in that path instead of the root of the obsidian space.

### Alternatives

Right now I'm manually moving the daily note to the specified path, but if I already created it inside Obsidian, I have to manually merge the two files and it's not the ideal workflow.

**Comment by epwalsh** [comment]
Hey @metalelf0, I'd be happy to have this feature. Are you interesting in making a PR?

You'd just have to edit the command function here:
https://github.com/epwalsh/obsidian.nvim/blob/e3d10fe6bf19f99e7ce289a13f0fc720c2cb276f/lua/obsidian/command.lua#L52-L59

And then add a field for this setting in the [Obsidian client class](https://github.com/epwalsh/obsidian.nvim/blob/e3d10fe6bf19f99e7ce289a13f0fc720c2cb276f/lua/obsidian/init.lua#L20-L28) and [config](https://github.com/epwalsh/obsidian.nvim/blob/e3d10fe6bf19f99e7ce289a13f0fc720c2cb276f/lua/obsidian/config.lua#L1-L44).

**Comment by metalelf0** [comment]
Hey @epwalsh ! Sure thing, but my lua-fu is still not that great. I tried hacking a solution here:

https://github.com/metalelf0/obsidian.nvim/commit/dc9956a24ca1c4235f406bcd22bb237f7dc878c9

But it seems something is not working.

Here's my reasoning: I added a client options called `dailies_path`, that should be relative to the main dir. This has a default value of `""` (empty string), so that it can seamlessly be joined to the dir. In the client initialization, I convert it to a `dailiies_dir` variable, so that it can be used without `if`s in the command. Loading the plugin with my changes, however, breaks with or without the option set.  

What am I doing wrong?

Thanks a lot for your work!

**Comment by epwalsh** [comment]
Hey @metalelf0, can you open a draft PR so I can leave suggestions? Also the last few commits I made yesterday touch some of the same code, so you'll want to update your branch first.

**Comment by epwalsh** [comment]
Also I was thinking instead of adding a top-level field like `dailies_path: ""`, we should add a field `daily_notes: { folder: "", ... }` that mimics the exact JSON structure in `~/.obsidian/daily-notes.json`.

**Comment by metalelf0** [comment]
I opened a PR for this: #21 .

**Comment by epwalsh** [comment]
Closed via #21
