### ISSUE TITLE
Make `gf` keybinding a part of the config

### ISSUE THREAD

**Issue by shakesbeare** [epwalsh/obsidian.nvim#157]
### 🚀 The feature, motivation and pitch

Making `gf` pass through the default behavior seems like it would enhance the new-user experience greatly. I'm proposing we move the keybind configuration into the plugin itself and have a flag in the config like "configure_gf_passthrough" or "manage_keybinds" (in case there are other keybindings that might be added in the future). 

### Alternatives

The one question I have about this is whether or not to turn it on by default. It seems like having plugins manage their own keybinds is not an unheard of thing, but it might be frustrating if our implementations for keybinds end up having any errors that result in unexpected breakages even while not in the vault. For example, messing with `gf` could cause issues with someone just trying to use the command normally. 

Personally, I think that since the `gf` keybind shouldn't affect anything if the user isn't on a markdown link, it probably is fine to turn it on by default. But we should probably add a check whether or not the open buffer is in the vault directory at the same time to ensure there aren't any issues. 

On the other hand, turning it on by default may cause existing configurations to break if they have a custom bind already setup for `gf`. Plus, if there are ever any other keybinds added, they might be more disruptive and may want to be turned off by default.

**Comment by epwalsh** [comment]
I'm in favor of making this the default.

> On the other hand, turning it on by default may cause existing configurations to break if they have a custom bind already setup for gf.

To get around this we could check if `gf` has already been set by the user or some other plugin and leave it alone if that's the case. For example, `:verbose nmap gf` will print "no mapping found" if it hasn't been set.

**Comment by shakesbeare** [comment]
Sounds good! I'll work on it when I get the chance unless someone else beats me to it. Shouldn't be too much effort.

**Comment by epwalsh** [comment]
Hey @shakesbeare I was able to tackle this just now in #161. I'd appreciate it if you could review the PR when you get a chance.
