### ISSUE TITLE
Config documentation is a bit convoluted

### ISSUE THREAD

**Issue by shakesbeare** [epwalsh/obsidian.nvim#158]
### 📚 The doc issue

Currently, configuration information may be found in three different places, `Install and Configure/Lazy.nvim`, `Install and Configure/packer`, and `Configuration Options`. Also, the installation code example for Lazy.nvim only is the only place to find information about dependencies.

These are a handful of larger changes that I thought might warrant some discussion as opposed to the small ones I submitted a PR for earlier. 

### Suggest a potential alternative/fix

1) Move dependency information to its own section and remove it from the Lazy.nvim setup, assuming users know how their package managers work. This will drastically cut down on the size of the Lazy.nvim setup portion and add emphasis to the configuration portion.

2) Remove keybinding recommendation from Lazy.nvim setup, moving either to a system I proposed in #157, or to its own keybinding section as a subheader of the Configuration section. This keybind may be skipped over as its part of the installation section and it feels like it belongs in a different place anyway. This will also help to shorten the section. 

3) Configuration about templates seems to be partially duplicated. Seems intentional but it's worth taking a think about as it adds some extra clutter and makes the config section difficult to scan quickly.

4) Treesitter markdown additional vim regex highlighting is recommended but it's unclear the effect it will have. We should probably add some comparison pictures to make it more clear.

**Comment by epwalsh** [comment]
Agreed. Let's tackle this after #157.

**Comment by epwalsh** [comment]
> 1. Move dependency information to its own section and remove it from the Lazy.nvim setup, assuming users know how their package managers work. This will drastically cut down on the size of the Lazy.nvim setup portion and add emphasis to the configuration portion.

Addressed by https://github.com/epwalsh/obsidian.nvim/commit/2c2a36840271993ac10f05eb7b134bd56ad85e29.

**Comment by epwalsh** [comment]
> 2. Remove keybinding recommendation from Lazy.nvim setup, moving either to a system I proposed in Make gf keybinding a part of the config #157, or to its own keybinding section as a subheader of the Configuration section. This keybind may be skipped over as its part of the installation section and it feels like it belongs in a different place anyway. This will also help to shorten the section.

Addressed by #161.

**Comment by epwalsh** [comment]
> 3. Configuration about templates seems to be partially duplicated. Seems intentional but it's worth taking a think about as it adds some extra clutter and makes the config section difficult to scan quickly.

Addressed by 6e2af3d.

**Comment by epwalsh** [comment]
Closed as completed.
