### ISSUE TITLE
[Feature] Open notes in a vertical split

### ISSUE THREAD

**Issue by stefanlogue** [epwalsh/obsidian.nvim#165]
### 🚀 The feature, motivation and pitch

I typically write notes at the same time as working, and it would be nice to be able to open the notes in a vertical split to record my notes side by side with my work.

I see this as being a non-breaking change, as it would add distinctly new commands to the plugin without affecting current features.

**Comment by weskoerber** [comment]
Quick hack without adding new commands:

```lua
require('obsidian').setup({
  -- your config options...

  vim.keymap.set("n", "<leader>tv", function()
    vim.cmd("vertical sbuffer | ObsidianToday")
  end)
})
```
