### ISSUE TITLE
ObsidianNew command doesnt read args

### ISSUE THREAD

**Issue by lucidph3nx** [epwalsh/obsidian.nvim#167]
### 🐛 Describe the bug

When running the command `:ObsidianNew Example` the note_id_func does not receive the 'Example' title, and only ever receives `nil`.

minimal note_id_func to reproduce:
```lua
note_id_func = function(title)
  print(title)
end,
```

I suspect this bug was caused by the change in #166 as the command.new function now looks for `data.args[1]` instead of `data.args`

### Versions

Obsidian v1.12.0

**Comment by epwalsh** [comment]
Closed via #169.
