### ISSUE TITLE
Completion: can't navigate nor choose suggestions

### ISSUE THREAD

**Issue by armaninux** [epwalsh/obsidian.nvim#168]
### 🐛 Describe the bug

Inserting [[ produces a list of suggestions as expected, but none of the lines can be selected as no keystroke has any effect. 
I haven't specified any cmp mapping (I wouldn't know how to do that in an init.vim file, because the cmp documentation takes for granted the use of an init.lua  and a corresponding lua setup). 

### Versions

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/usr/share/nvim"

Other relevant plugins:
junegunn/fzf
hrsh7th/nvim-cmp
hrsh7th/cmp-buffer
hrsh7th/cmp-path
preservim/vim-markdown
vimwiki/vimwiki

**Comment by epwalsh** [comment]
Hey @armaninux, I found [this guide](https://github.com/nanotee/nvim-lua-guide) very helpful when I was learning Lua in the context of Neovim. [This section](https://github.com/nanotee/nvim-lua-guide#using-lua-from-vimscript) in particular shows you how you can call Lua code from Vimscript. So you could just put all of the Lua nvim-cmp setup within your `init.vim` using that method.

**Comment by armaninux** [comment]
thanks, I got this now. I added a basic config for cmp and added 'hrsh7th/cmp-nvim-lsp' plugin to make it all work:

```
lua <<EOF
local cmp = require('cmp')

cmp.setup({
  window = {
    completion = cmp.config.window.bordered(),
    documentation = cmp.config.window.bordered(),
  },
  mapping = cmp.mapping.preset.insert({
    ['<C-b>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.abort(),
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
  }),
  sources = {
    {name = 'buffer'},
    {name = 'path'},
  }
})

-- `/` cmdline setup.
cmp.setup.cmdline('/', {
  mapping = cmp.mapping.preset.cmdline(),
  sources = {
    {name = 'buffer'}
  }
})

-- `:` cmdline setup.
cmp.setup.cmdline(':', {
  mapping = cmp.mapping.preset.cmdline(),
  sources = {
    {name = 'path'},
    {name = 'cmdline'}
  }
})
EOF
```

**Comment by armaninux** [comment]
This fixed the issue.
