### ISSUE TITLE
More info about how to setup completions with nvim-cmp

### ISSUE THREAD

**Issue by EvanEzell** [epwalsh/obsidian.nvim#170]
### 📚 The doc issue

I have tried to get nvim-cmp working with no luck. I noticed in [issue 133](https://github.com/epwalsh/obsidian.nvim/issues/133) that the user had to set up the source manually. I have tried various things, like setting up the source manually, and just using the default configuration. Not exactly sure what is going on, but according to the documentation, it should handle the setup for you. It would be nice if there were trouble shooting instructions for setting up the completions.

**Comment by epwalsh** [comment]
Hey @EvanEzell, sorry to hear that completion isn't working. Does your `nvim-cmp` setup work with other completion sources?

**Comment by epwalsh** [comment]
If this is still an issue I'll reopen.
