### ISSUE TITLE
ObsidianQuickSwitch search_file filter is broken

### ISSUE THREAD

**Issue by bry-guy** [epwalsh/obsidian.nvim#172]
### 🐛 Describe the bug

When using `:ObsidianQuickSwitch`, I receive no results with `telescope.nvim` as my finder. I was able to reproduce this without using `:ObsidianQuickSwitch`, and instead invoking telescope directly as `command.quick_switch` does.
```
:lua require("telescope.builtin").find_files({cwd="~/second-brain",search_file="*.md"})
```

When I update the `search_file` argument from `"*.md"` to `"./*.md"`, I receive successful results:
 ```
:lua require("telescope.builtin").find_files({cwd="~/second-brain",search_file="*./.md"})
```

Making the same change in my local `obsidian.nvim` source produces successful results as well:
```
  client:_run_with_finder_backend(":ObsidianQuickSwitch", {
    ["telescope.nvim"] = function()
      local has_telescope, telescope = pcall(require, "telescope.builtin")

      if not has_telescope then
        util.implementation_unavailable()
      end
      -- Search with telescope.nvim
      --- telescope.find_files { cwd = dir, search_file = "*.md" }
      telescope.find_files { cwd = dir, search_file = "./*.md" }
    end,
...
```

My intuition is somehow, this is a configuration issue on my end, but I wanted to do a sanity check first. Does `:ObsidianQuickSwitch` work by default for others today?

My obsidian config:
```
require("obsidian").setup({
  dir = "~/second-brain",
  log_level = vim.log.levels.DEBUG,
  open_app_foreground = false,
  completion = {
    nvim_cmp = true,
	min_chars = 2,
	new_notes_location = "notes_subdir",
	prepend_note_id = true
  },
  notes_subdir = "Inbox",
  daily_notes = {
    folder = "Diaries",
  },
  finder = "telescope.nvim",
  open_notes_in = "hsplit"
})
```

My telescope config:
```
local actions = require('telescope.actions')

require('telescope').setup {
  defaults = {
    file_ignore_patterns = { "^.git/", "node_modules", "^.yarn/cache" },
	hidden = true,
  },
  pickers = {
	find_files = {
	  no_ignore = true,
	  hidden = true,
	},
	buffers = {
	  sort_mru = true
	},
	live_grep = {
	  additional_args = function(_)
		return {"--hidden"}
	  end
	},
  },
}

require('telescope').load_extension('fzf')
```

I am on macOS 12.6.8.

If this is broken, happy to submit the PR to fix - thanks!

### Versions

```
$ nvim --version
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"

Run :checkhealth for more info

$ nvim --headless -c 'lua print("Obsidian v" .. require("obsidian").VERSION)' -c q
Obsidian v1.12.0%
```

**Comment by epwalsh** [comment]
Hey @bry-guy, that's odd. It works fine for me on MacOS right now, but changing `"*.md"` to `"./*.md"` actually breaks it 🤔

**Comment by bry-guy** [comment]
Haha, that's fun 😅. One quirk that could be influencing it is my ~ directory has a `.git` subdirectory (maybe a bad idea, but that's how I've made iterating my dots easier). I wonder if that's influencing the search mechanism.

I'll let you know if learn more, but it's likely this is a configuration issue on my end.

**Comment by epwalsh** [comment]
We've made a lot of changes recently to how we integrate with finders like `telescope.nvim`. I don't think this is an issue anymore since we're using a custom find command, but I'll reopen if it is.
