### ISSUE TITLE
How would I go about creating a default tag on new note?

### ISSUE THREAD

**Issue by mesa123123** [epwalsh/obsidian.nvim#173]
### 📚 The doc issue

I'm creating notes left and right using this and theres heaps of blank notes in my vault, I want to know which ones are blank so I can go back and rewrite them later on, so I'm thinking everytime I create a note could it have a default tag of "TODO" or something akin?

After reading the code a bit I'm guessing it has something to do with the note_id_func option and inserting something like { title = "title", tags = { "TODO" } }?

Thought I'd ask as I'm a little stumped as my lua is not as sharp as I'd like?

Am I on the right track?

**Comment by epwalsh** [comment]
Hey @mesa123123, you could accomplish this by customizing the `note_frontmatter_func` in your config. From the README, this is what the default function looks like:

```
  note_frontmatter_func = function(note)
    -- This is equivalent to the default frontmatter function.
    local out = { id = note.id, aliases = note.aliases, tags = note.tags }
    -- `note.metadata` contains any manually added fields in the frontmatter.
    -- So here we just make sure those fields are kept in the frontmatter.
    if note.metadata ~= nil and require("obsidian").util.table_length(note.metadata) > 0 then
      for k, v in pairs(note.metadata) do
        out[k] = v
      end
    end
    return out
  end,
```

**Comment by mesa123123** [comment]
Hey @epwalsh been giving that a crack and my tags aren't changing:

This is my frontmatter function:

```lua
 local make_note_frontmatter = function(note)                                                  
      local out = { tags = "todo"}                                                              
      return out                                                                                
  end
```
so my fontmatter should be something along the lines of:

  ---                                                                                           
  id: "Note"                                                                                   
  aliases:                                                                                      
    - "Note"                                                                                   
  tags:
   - "todo"                                                                    
  ---           


Instead its still:

  ---                                                                                           
  id: "Fucky"                                                                                   
  aliases:                                                                                      
    - "Fucky"                                                                                   
  tags: []                                                                                      
  ---                                                                                           

How would I change it?

**Comment by mesa123123** [comment]
Ok so looking through note.lua

I think this is what updates the tags based on the front matter??

```lua
       elseif k == "tags" then
          if type(v) == "table" then
            for _, tag in ipairs(v) do
              if type(tag) == "string" then
                table.insert(tags, tag)
              else
                echo.warn(
                  "Invalid tag value found in frontmatter for "
                    .. path
                    .. ". Expected string, found "
                    .. type(tag)
                    .. "."
                )
              end
            end
```

**Comment by mesa123123** [comment]
Would calling this method somehow help?
```lua
--- Line 86 Note.lua ---
---Add a tag to the note.
---
---@param tag string
note.add_tag = function(self, tag)
  if not self:has_tag(tag) then
    table.insert(self.tags, tag)
  end
end
```

**Comment by epwalsh** [comment]
Hey @mesa123123, sorry for the slow response. I think you're right about calling `note:add_tag`. This worked for me:


```lua
      note_frontmatter_func = function(note)
        note:add_tag "TODO"
        local out = { id = note.id, aliases = note.aliases, tags = note.tags }
        -- `note.metadata` contains any manually added fields in the frontmatter.
        -- So here we just make sure those fields are kept in the frontmatter.
        if note.metadata ~= nil and require("obsidian").util.table_length(note.metadata) > 0 then
          for k, v in pairs(note.metadata) do
            out[k] = v
          end
        end
        return out
      end,
```

**Comment by mesa123123** [comment]
Brilliant, sorry for the slow response on my end too, I'll give that a try now and see if i can recreate it

**Comment by mesa123123** [comment]
Doesn't appear to be working sadly! Is there somethig that might be blocking it? I've tried for both link under cursor and regular create functions

**Comment by epwalsh** [comment]
Ah I see the issue! #178 should fix.

**Comment by mesa123123** [comment]
Hey @epwalsh just wondering if you have a similar bug where a daily note upon being saved ends up adding the default tag to the note.
I've tested this on a new note that isn't daily either. 

Is there a way to solve this issue?

Let me know!

**Comment by epwalsh** [comment]
Hey @mesa123123, sorry just getting back to this now. Are you saying that when you make a new daily note it's missing the extra tag?
