### ISSUE TITLE
Completion of tags

### ISSUE THREAD

**Issue by linduxed** [epwalsh/obsidian.nvim#180]
### 🚀 The feature, motivation and pitch

Currently there's completion for notes and for the notes together with their aliases. I was wondering whether a similar completion of the tags is possible.

The idea would be to (if possible) to emulate the behaviour of Obsidian, for when one presses `#`: a fuzzy-finding across all of the tags is started.

I'm not sure if this is a feature that has already been considered and rejected (e.g. due to complexity), but I thought that I would ask, as this is one of the main features I notice myself going back to the Obsidian editor to use.

### Alternatives

Switching back and forth between Neovim and Obsidian.

**Comment by epwalsh** [comment]
Hey @linduxed this is probably doable. We'd have to add a new completion source, like `lua/cmp_obsidian_tags.lua` which could use our existing search functionality (`util.search()`) along with the `Note` class to find matching tags.

**Comment by linduxed** [comment]
Thank you very much for implementing this! 👍 🎉
