### ISSUE TITLE
Creating new notes using with path does not trigger note_id_func

### ISSUE THREAD

**Issue by peeeyow** [epwalsh/obsidian.nvim#184]
### 🐛 Describe the bug

This is partially related to #147, #148 and #151. When I'm creating new file with path, my custom `note_id_func` is not applied to the title of the newly created note. I was expecting it to use the `note_id_func` for the title.

Here's an example:  
Creating new file using `:ObsidianNew dailies/new note` creates a new file named `new note.md` on `dailies` directory. But, I am expecting it to be named as `20230906185913-new-note.md`.  
Creating new file using without path works as usual.  
How could I make the plugin trigger `note_id_func` when creating new note with path?

Here's the relevant part in the setup:
```lua
require("obsidian").setup({
    -- other fields ...
    note_id_func = function(title)
      local suffix = ""
      if title ~= nil then
        suffix = title:gsub(" ", "-"):gsub("[^A-Za-z0-9-]", ""):lower()
      else
        for _ = 1, 4 do
          suffix = suffix .. string.char(math.random(65, 90))
        end
      end
      return tostring(os.date "%Y%m%d%H%M%S") .. "-" .. suffix
    end,
})
```

### Versions

```bash
$ nvim --version
NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include/luv -I/builddir/build/BUILD/neovim-0.9.1/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.9.1/redhat-linux-build/include -I/builddir/build/BUILD/neovim-0.9.1/redhat-linux-build/cmake.config -I/builddir/build/BUILD/neovim-0.9.1/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

$ nvim --headless -c 'lua print("Obsidian v" .. require("obsidian").VERSION)' -c q
Obsidian v1.13.0
```

**Comment by epwalsh** [comment]
Hey @peeeyow, this is currently the intended behavior when the argument to `:ObsidianNew` looks like a path (e.g. "dailies/new note"). We might need a separate command to get the behavior you want, something like

```vim
:ObsidianNewInDir [dir_path] [title]
```

What do you think?

**Comment by peeeyow** [comment]
I see. I thought it was a bug. Thanks for confirming.

> ```viml
> :ObsidianNewInDir [dir_path] [title]
> ```

This would be a great feature if implemented. It can improve workflows. I can help testing it out if implemented.

**Comment by lpanebr** [comment]
Would it be possible to use the same command? Even if a new config option is required?

I feel that having to rely on memory to use a different command is an overhead. I can already see myself starting a new note and going "damn.. I wanted it in a directory..."

**Comment by epwalsh** [comment]
Ok @peeeyow @lpanebr, fair enough. I've opened #188 to address this. With that change, `:ObsidianNew dailies/new note` should work as you want. For those that want the original behavior, you just need to add a `.md` suffix, i.e. `:ObsidianNew dailies/new_note.md`.
