### ISSUE TITLE
`max_item_count` for files

### ISSUE THREAD

**Issue by mel10c** [epwalsh/obsidian.nvim#185]
### 🚀 The feature, motivation and pitch

Currently, I was not able to find a way to limit the max number of files suggested by the cmp. I have tried adding `max_item_count` in cmp settings and it wasn't working.

Can we please add a way to limit the number of files suggested by the autocomplete, thanks! It is a lovely plugin!

**Comment by epwalsh** [comment]
Hey @mel10c, I've added a feature to control this in #186.

**Comment by epwalsh** [comment]
As we found in #186 this is beyond the scope of Obsidian.nvim. It would have to implemented in nvim-cmp.
