### ISSUE TITLE
Move files to other folders

### ISSUE THREAD

**Issue by austinwilcox** [epwalsh/obsidian.nvim#189]
### 🚀 The feature, motivation and pitch

When I am reviewing notes in my fleeting notes, I would like the ability to move those notes over into my permanent notes without using the command line or leaving the current file I am editing.

### Alternatives

I have written an alternative solution, that I kind of glued together, I would be happy to merge the code into here where it will make much more sense, and then others would be able to enjoy it. [ZK Move File](https://github.com/austinwilcox/ZKMoveFile)

edit:
Changed name to match new name of plugin.

**Comment by epwalsh** [comment]
Thanks @austinwilcox, I'd be happy to review a PR with this.

**Comment by austinwilcox** [comment]
Awesome! I'll try and get a pr up in the coming weeks to review.

**Comment by epwalsh** [comment]
This is supported now with `:ObsidianRename`.
