### ISSUE TITLE
Multi vault support

### ISSUE THREAD

**Issue by mertnuhoglu** [epwalsh/obsidian.nvim#190]
### 🚀 The feature, motivation and pitch

I have multiple Obsidian vaults (directories). Is it possible to add support for multiple vaults?

**Comment by epwalsh** [comment]
Hey @mertnuhoglu we have a PR right now that would support this: #155

**Comment by oflisback** [comment]
Very nice to see that more people are interested in this. Please critique this alternative approach:

Each buffer knows what vault it belongs to automatically by checking the path hierarchy for `.obsidian` folders, these lookups can also be cached. Basically something like what I did here but returning the vault path: [is_obsidian_vault](https://github.com/oflisback/obsidian-bridge.nvim/blob/e21b42ade811112cda18c6b4d268ff4847283950/lua/obsidian-bridge/init.lua#L14-L24).

Two benefits:

* No need to explicitly set a vault dir or workspaces in the configuration.
* Each buffer knows its context so commands can be applied in the right context automatically.

**Comment by epwalsh** [comment]
@oflisback, I like the simplicity of that. But I also like how #155 gives users more control. That said, I think this functionality could be built on top of #155 easily. Once that merges we can explore this more.

**Comment by epwalsh** [comment]
I'll follow up on the templates question in the PR.

**Comment by epwalsh** [comment]
Closing as this is now fully supported through the `config.workspaces` option. As of #277 you can also override certain settings for each workspace.
