### ISSUE TITLE
Add option to overwrite existing keybindings

### ISSUE THREAD

**Issue by MissSis** [epwalsh/obsidian.nvim#193]
### 🚀 The feature, motivation and pitch

Right now, the mappings specified in the config table are only applied if they don't conflict with existing keybinding. If there is a conflict, a warning message pops up, which has [already been mentioned](https://github.com/epwalsh/obsidian.nvim/issues/162). This seems to be especially problematic when using which-key because appenrently which-key will reconfigure all keybindings (probably to trigger its popup menu when you press a key). The solution from the github issue was to not use the mapping that conflicts.

However, I would like to have a way to still apply the mapping. The easiest way I could think of is to ignore the conflict and apply the mapping anyways. This could be added as an additional config option and used in the if statement [here](https://github.com/epwalsh/obsidian.nvim/blob/main/lua/obsidian/init.lua#L99) like so:
```lua
if mapping_set_by == "" or opts.overwrite_mappings then
    vim.keymap.set("n", mapping_keys, mapping_config.action, mapping_config.opts)
elseif not string.find(mapping_set_by, "obsidian") then
    -- warning logic
```

### Alternatives

An alternative would be to not use which-key or using another key binding. Another method would be to call the `lazy_setup` function non-lazily, but for just this use-case it probably sacrifices too much performance. Overall, all these alternatives are not really satisfying imo.

### Additional context

Please let me know what you think of my idea. I would also be willing to implement this new config option if needed, but be warned that I have never written or contributed to a Neovim plugin.

**Comment by epwalsh** [comment]
Hey @MissSis, I like the idea of adding a config field to overwrite mappings. Would you like to make a PR?

**Comment by MissSis** [comment]
Yeah sure, I'm gonna submit a PR in the near future.
