### ISSUE TITLE
Completion when wikilink is not preceded by a space

### ISSUE THREAD

**Issue by mscott99** [epwalsh/obsidian.nvim#194]
### 🐛 Describe the bug

When writing "see the info in~[[", completion is not triggered. It is only triggered when there is a space before the [[. This also happens when I try to write embedded links "![[".

The completion seems to be conditional on the link being an independent word, probably this condition can be removed somehow?

### Versions

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"

Run :checkhealth for more info
Obsidian v1.13.0%

**Comment by epwalsh** [comment]
Hey @mscott99, #198 should fix.
