### ISSUE TITLE
Frontmatter date is always quoted

### ISSUE THREAD

**Issue by gergol** [epwalsh/obsidian.nvim#225]
### 🐛 Describe the bug

I'm trying to add the date to the frontmatter of new notes like this:

```lua
  local out = {
    test_date = "2023_11_10 13:26", 
    just_a_string = "blah blah",
    crated = os.date(),
    title = note.id,
    aliases = note.aliases,
    tags = note.tags
  }
```

It works in general, but the resulting dates are always surronded by double quotes. 
```
---
aliases:
  - ajskljd
tags: []
crated: "Fri Nov 10 13:46:14 2023"
just_a_string: blah blah
test_date: "2023_11_10 13:26"
title: ajskljd
---
```
Is there a way to get rid of these extra quotes?

Thanks in advance!

### Versions

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.0-beta3
```

```
  "obsidian.nvim": { "branch": "main", "commit": "6e72c9ed34f2c1566af9b690c7fe88aaa18c52f4" },
```

**Comment by epwalsh** [comment]
Hey @gergol, I've been pretty conservative with the rules for quoting YAML so far strings, but #228 relaxes it a bit and should definitely fix this case.

**Comment by gergol** [comment]
@epwalsh thank you so much for your quick fix!!
