### ISSUE TITLE
Cannot open existing notes, but will create new note

### ISSUE THREAD

**Issue by guasabara** [epwalsh/obsidian.nvim#226]
### 🐛 Describe the bug

New obsidian.nvim install, KDE on Ubuntu.  When calling: ObsidianOpen somenote, the error is:
Error executing Lua callback: .../pack/packer/start/obsidian.nvim/lua/obsidian/client.lua:416: attempt to call a table value
stack traceback:
        .../pack/packer/start/obsidian.nvim/lua/obsidian/client.lua:416: in function 'resolve_note'
        ...pack/packer/start/obsidian.nvim/lua/obsidian/command.lua:99: in function 'func'
        ...pack/packer/start/obsidian.nvim/lua/obsidian/command.lua:747: in function <...pack/packer/start/obsidian.nvim/lua/obsidian/command.lua:746>

I can call ObsidianNew test and a note is created. 

### Versions

NVIM v0.10.0-dev-1492+g3ca967387
Build type: Release
LuaJIT 2.1.1699198486
Run "nvim -V1 -v" for more info

[obsidian.nvim (v1.15.0)] Commit SHA: 107469e8ec44550290fe4cdafc8d640d144c64c3
[plenary.nvim] Commit SHA: 50012918b2fc8357b87cff2a7f7f0446e47da174
[nvim-cmp] Commit SHA: 0b751f6beef40fd47375eaf53d3057e0bfa317e4
[telescope.nvim] Commit SHA: 20bf20500c95208c3ac0ef07245065bf94dcab15
ripgrep 13.0.0%

**Comment by epwalsh** [comment]
Hey @guasabara, this should be fixed now on `main` as of a73b143.

**Comment by guasabara** [comment]
Hmmm, just tested, I did perform an update.  Error: [Obsidian] failed opening Obsidian app to note.  I tried the ID as well as the alias.  Am I doing something wrong?  Eg, I type in nvim ':ObsidianOpen Notepad'.  The actual file is Notepad.md.

[obsidian.nvim (v1.15.0)] Commit SHA: dd9ef6a7743e2fdc57bd10ecc6f3a2bb59e4405f

**Comment by epwalsh** [comment]
Hmm the open command we shell out to must be erroring. Can you try again with this branch: #229? This should surface the errors you're getting.

**Comment by guasabara** [comment]
How do I force the install of a particular version?  Speaking of shells, I
am using zsh.

Thanks for the support!

**Comment by epwalsh** [comment]
Which plugin manager are you using?

**Comment by guasabara** [comment]
Packer

**Comment by epwalsh** [comment]
Just set `branch` to "log-stderr-on-open".
https://github.com/wbthomason/packer.nvim#specifying-plugins

**Comment by guasabara** [comment]
So, I added branch = "229"

nvim --headless -c 'lua require("obsidian").info()' -c q                                                                                           
[obsidian.nvim (v1.15.0)] Commit SHA: dd9ef6a7743e2fdc57bd10ecc6f3a2bb59e4405f

Same error:  [Obsidian] failed opening Obsidian app to note

**Comment by guasabara** [comment]
Ok, set to log-stderr-on-open

info:
[Obsidian] captured stderr output while opening Obsidian app to note:
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/obsidian" not found
Press ENTER or type command to continue

**Comment by epwalsh** [comment]
This might help: https://unix.stackexchange.com/questions/251054/how-does-the-xdg-open-command-know-which-application-to-use-to-open-a-file

Sounds like you need to run something like:

```
xdg-mime default /path/to/Obsidian.desktop x-scheme-handler/obsidian
```

**Comment by guasabara** [comment]
After reading the stackexchange ... I am using an appimage of obsidian, so I did not find obsidian.desktop.  I downloaded and installed the deb package from the obsidian website, I then did find the obsidian.desktop file in /usr/share/application, but the program did not open.  Any further insights?

**Comment by epwalsh** [comment]
I'm not sure. Unfortunately I can't help debug because I don't have access to a Linux desktop right now.

**Comment by guasabara** [comment]
Ok, thanks for your interest and help.

**Comment by guasabara** [comment]
Solved, I reinstalled obsidian using the deb file and obsidian opened properly.  I then reinstalled your plugin and the call to ObsidianOpen worked.  Not sure why my first install of the deb package did not work.

**Comment by epwalsh** [comment]
Glad to hear it!
