### ISSUE TITLE
Commands are no longer available outside vault

### ISSUE THREAD

**Issue by campbellr** [epwalsh/obsidian.nvim#234]
### 🐛 Describe the bug

I think until recently all the `:Obsidian*` commands were always available, but as of 5a71d81a490c47b1c6236d1ba27f6e90d21c3df5 they seem to only be loaded when we enter a markdown file in the vault.

I couldn't find an obvious workaround to go back to the previous behaviour. It would be great if this was configurable

It's really convenient to be able to do `ObsidianToday` or `:ObsidianOpen` from any random file...

### Versions

NVIM v0.9.4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /gnu/store/.../bin/gcc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/gnu/store/cvx5k3wsy0iczzc1pk0fid9lfg48kyml-luajit-2.1.0-beta3-0.6c4826f/include/luajit-2.1 -I/gnu/store/ln6hxqjvz6m9gdd9s97pivlqck7hzs99-glibc-2.35/include -I/gnu/store/dl86fjk9b066gmkdyzdcwq37w3r8vn97-lua5.1-luv-1.43.0-0/include -I/tmp/guix-build-neovim-0.9.4.drv-0/build/src/nvim/auto -I/tmp/guix-build-neovim-0.9.4.drv-0/build/include -I/tmp/guix-build-neovim-0.9.4.drv-0/build/cmake.config -I/tmp/guix-build-neovim-0.9.4.drv-0/source/src -I/gnu/store/ln6hxqjvz6m9gdd9s97pivlqck7hzs99-glibc-2.35/include -I/gnu/store/ai02fnfa9kzqnqi4b6g9ln8q3kg00x6v-libtermkey-0.22/include -I/gnu/store/xma3qh1yszb3m99241rmys2ibhxv4lfc-libvterm-0.3.3/include -I/gnu/store/d4kljpf1gyd8gyqrhbr36dj65jdzkjxf-msgpack-3.3.0/include -I/gnu/store/gf5fy8nmhn3qsvq49l2hcmvpv5v551ib-tree-sitter-0.20.10/include -I/gnu/store/i2gmfv92a3vyfd4d5gnm02mdzgzwabm9-unibilium-2.0.0/include -I/gnu/store/lkram5mncrccvy6274q7qrayv8c2gpms-libuv-1.43.0/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/gnu/store/ml835sz7xzflbhp2ac00kmcidaglxdx7-neovim-0.9.4/share/nvim"

Run :checkhealth for more info
[obsidian.nvim (v2.0.0)] Commit SHA: 7df67dcaa0bfc943318e88ec3555afa9bfef71fe
[plenary.nvim] Commit SHA: 50012918b2fc8357b87cff2a7f7f0446e47da174
[nvim-cmp] Commit SHA: 0b751f6beef40fd47375eaf53d3057e0bfa317e4
[telescope.nvim] Commit SHA: 18774ec7929c8a8003a91e9e1f69f6c32258bbfe
[fzf.vim] Commit SHA: 1e054c1d075d87903647db9320116d360eb8b024
ripgrep 13.0.0%

**Comment by epwalsh** [comment]
Hey @campbellr, this commit (now on `main`) should fix: 8ade892

**Comment by campbellr** [comment]
Wow thanks @epwalsh , that has to be a record for fastest fix! :smile:
