### ISSUE TITLE
Links to notes with spaces in the title are not able to be followed

### ISSUE THREAD

**Issue by shakesbeare** [epwalsh/obsidian.nvim#24]
### Summary
Links with space in the note title are not followable by a simple `gf`. Instead, user must highlight the entire contents of the link at which point `gf` works. 

### Steps to reproduce
1) Create a note in vault
2) Link to a note with which has a space in the name (Ex: "From the Vast - Session 1.md") 
3) Place cursor inside the link at any position
4) Use `gf` command
5) Observe error 'Cannot find file "From" in path'
6) Use visual mode to select entire file name
7) Use `gf` command
8) Observe link followed correctly

### Expected Behavior
Link is followed no matter if visual mode technique is used or not. 

### Versions

```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info
```

```
1.3.0
```

**Comment by epwalsh** [comment]
Hey @shakesbeare, I'm not sure what the best solution to this would be. I guess we could potentially override `gf` with our own implementation.

**Comment by epwalsh** [comment]
Contributions welcome on this. I looked into a little more and I'm pretty sure the best solution is in fact to override `gf` with a custom function. I think it's reasonable to assume that we can only handle filenames with spaces when they're contained in a reference, e.g. `[[my note.md]]`. So implementing this function shouldn't be too hard. Basically:
1. Get the cursor position and corresponding line in the buffer.
2. Check if cursor is on a reference, in which case parse out the reference and follow it.
3. Otherwise just treat the current "word" under the cursor as a filename and follow it.

**Comment by shakesbeare** [comment]
@epwalsh I figured I'd give it a shot but I had some questions about the exact implementation which is best. 

My thought was to create a command such as `:ObsidianFollowLink` and a companion function, something like `cursor_inside_markdown_link`. That way the user could decide to bind it at their own discretion and choose to use the `gf` keybind if desired and allow it to pass through to standard `gf` if the cursor isn't inside of a markdown link. The idea would be to avoid rewriting vim's existing code for this purpose and allow greater customization for the user. 

Furthermore, Obsidian allows for links to be styled without sub-directories listed in the link (ie `[[my note.md]]` instead of `[[notes/my note.md]]`) provided that the no other note exists with that file name. It seems from some quick testing that the standard `gf` does *not* share this functionality (vim fails to find the file `test3.md` within the folder `folder` unless the text is written as `folder/test3.md`). Should we follow the standard set by vim `gf` or make the experience consistent with Obsidian's links?

**Comment by epwalsh** [comment]
> My thought was to create a command such as :ObsidianFollowLink and a companion function, something like cursor_inside_markdown_link. That way the user could decide to bind it at their own discretion and choose to use the gf keybind if desired and allow it to pass through to standard gf if the cursor isn't inside of a markdown link. The idea would be to avoid rewriting vim's existing code for this purpose and allow greater customization for the user.

I like that idea.

> It seems from some quick testing that the standard gf does not share this functionality (vim fails to find the file test3.md within the folder folder unless the text is written as folder/test3.md).

Vim will actually do this as long as your notes folder is in `path`. So in vim, just do `set path+=folder` and then that should work. Now that I think of it, Obsidian should do that automatically. I'm going to make a PR for that.
