### ISSUE TITLE
Publish API docs for the public Lua API

### ISSUE THREAD

**Issue by epwalsh** [epwalsh/obsidian.nvim#245]
We could use the `docgen` module from tree-sitter-lua: https://github.com/tjdevries/tree-sitter-lua/tree/master#how-to-generate-documentation

**Comment by sotte** [comment]
`mini.doc` also works well.

https://github.com/echasnovski/mini.doc

**Comment by epwalsh** [comment]
Thanks @sotte, this is exactly what I was looking for!

**Comment by sotte** [comment]
Glad it helped @epwalsh!
