### ISSUE TITLE
"gf" does not follow "links" to attachments

### ISSUE THREAD

**Issue by arturo-salinas** [epwalsh/obsidian.nvim#247]
### 🚀 The feature, motivation and pitch

I usually work with text files (logs) that I need to open in nvim. It would be nice if the Obsidian can follow those links.

**Comment by epwalsh** [comment]
Hey @arturo-salinas can you let me know if #248 fixes this for you?

**Comment by arturo-salinas** [comment]
It did not fix it.  
```
[My attachment](Files/text_file.txt)
```
Where "Files" is my attachment directory. It works fine in Obsidian.

**Comment by epwalsh** [comment]
How about now?

**Comment by arturo-salinas** [comment]
It works!! 👍

**Comment by epwalsh** [comment]
Great, I'll merge
