### ISSUE TITLE
Search all notes with Telescope (:ObsidianSearch)

### ISSUE THREAD

**Issue by codingluke** [epwalsh/obsidian.nvim#25]
### 🚀 The feature, motivation and pitch

I am wondering how to easy search inside Obsidian (filename, tags) with Telescope from within a random buffer. I guess a `:ObsidianSearch` command would be needed, or is it possible to configure Telescope directly?

### Alternatives

At the moment I have to open a Neovim instance inside the Obsidian folder to search within with Telescope. Or use the Obsidian app

### Additional context

While working on a random Project I want to be able to quickly search and open an existing Obsidian note with Telescope.

**Comment by epwalsh** [comment]
Hey @codingluke, having an `:ObsidianSearch` command is a great idea! I just gave it a shot in #27. Can you see if that works for you?
