### ISSUE TITLE
How to get rid of "backlink tips"

### ISSUE THREAD

**Issue by armaninux** [epwalsh/obsidian.nvim#253]
### 🐛 Describe the bug

Not a bug I guess, but I can't find a way to be rid of the message "Showing backlinks to 'xxxxx'. TIPS: Hit Enter on a match ... etc etc" which appears instead of the backlinks list. The list appears only after I dismiss this message.
Is this related to some neovim settings independent of the plugin?

### Versions

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
[obsidian.nvim (v2.3.0)] Commit SHA: 962456ee8c369556d4a79a0dfa3bb9638aba9122
[plenary.nvim] Commit SHA: 55d9fe89e33efd26f532ef20223e5f9430c8b0c0
[nvim-cmp] Commit SHA: 0b751f6beef40fd47375eaf53d3057e0bfa317e4
[fzf.vim] Commit SHA: 1e054c1d075d87903647db9320116d360eb8b024
ripgrep 14.0.3

**Comment by epwalsh** [comment]
Hey @armaninux, obsidian.nvim logs messages like this through `vim.notify`. You could disable messages like this entirely by setting `log_level` to `vim.log.levels.WARN` in your obsidian.nvim config, or if you could add another plugin that provides a better experience for `vim.notify` messages, such as `nvim-notify` (which is what I use).

**Comment by armaninux** [comment]
Thanks! This fixes it.
