### ISSUE TITLE
issues with switching workspaces

### ISSUE THREAD

**Issue by adam-devel** [epwalsh/obsidian.nvim#254]
### 🐛 Describe the bug

the notes from the workspace i switch to do not get any keys mapped to them and their frontmatter doesn't get updated.
this looks like an autocmd issue, i guess `:ObsidianWorksapce` forgets to register a new autocmd for the files under the selected workspace.

### Versions

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

[obsidian.nvim (v2.3.0)] Commit SHA: 384b7e94e8f521921cc6d6a91f6e0cb9a77950af
[plenary.nvim] Commit SHA: 55d9fe89e33efd26f532ef20223e5f9430c8b0c0
[nvim-cmp] Commit SHA: 0b751f6beef40fd47375eaf53d3057e0bfa317e4
[telescope.nvim] Commit SHA: 84c5a71d825b6687a55aed6f41e98b92fd8e5454
ripgrep 13.0.0

**Comment by adam-devel** [comment]
Looks like the autocommand is registered when calling `setup`:
https://github.com/epwalsh/obsidian.nvim/blob/384b7e94e8f521921cc6d6a91f6e0cb9a77950af/lua/obsidian/init.lua#L178-L207
- we can call setup everytime we switch workspaces, lazy but works
- or we can move the command registering logic to the workspace module, `setup` can use workspace APIs to set the current workspace; the command for switching workspaces will also use those very same APIs to set the current workspace. registering autocommands will be part of initializing the a workspace; this is harder but it sounds more correct to me, feel free to critique.

#190 is relevant

**Comment by epwalsh** [comment]
Hey @adam-devel, I like your proposal of moving that logic to the workspace module, and I'm happy to review a PR for that. In the meantime I think I have quick work-around in #255. Can you confirm that fixes it for you?

**Comment by adam-devel** [comment]
@epwalsh i think it'd be wise to merge and release #255 as a hotfix, and defer an API revamp for the workspace module to a later release, what do you think

**Comment by adam-devel** [comment]
`Client.dir` make sense if the client was managing a single vault/workspace, it should be removed in favor of a `Client.current_workspace` property, which will store a workspace instance. the instance has a `.path` field which represent the `dir`ectory of the current workspace managed by the client

**Comment by epwalsh** [comment]
Released in 2.3.1.

I agree it would be nice to get rid of `dir`.
