### ISSUE TITLE
ObsidianLink to open Telescope for options and fuzzy filtration

### ISSUE THREAD

**Issue by omerxx** [epwalsh/obsidian.nvim#261]
### 🚀 The feature, motivation and pitch

The current linking feature assumes I remember the alias or ID where if most cases I'd have a general idea of what the linked note was and would need a fuzzy search (possible one that would have the context of the note itself as well). 
In a perfect world, it would be triggered by the identification of `[[` much like in Obsidian itself :)

Thanks!

### Alternatives

The alternative is to run `ObsidianOpen` and then link but this is cumbersome...

**Comment by epwalsh** [comment]
Hey @omerxx, so currently `:ObsidianLink` uses the visual selection to search for a matching note by ID, alias, or filename. If that doesn't return a match we could fall back to a fuzzy search with the configured finder. Is that what you're suggesting?

**Comment by omerxx** [comment]
Yep! Does this make sense?
TBH I just figured that the auto completion feature when starting a link with an opening bracket kinda does the trick so not a must really.

Thanks!

**Comment by epwalsh** [comment]
Yeup definitely makes sense! I have this implemented in #262.
