### ISSUE TITLE
completion / cmp: Calling completion returns error: executing cmp_obsidian_new: assertion failed

### ISSUE THREAD

**Issue by tjex** [epwalsh/obsidian.nvim#263]
### 🐛 Describe the bug

When calling completion, after having typed more than the minimum characters required for completion as per config, I encounter the below error. The first two lines are output as part of `vim.log.levels.WARN`.

```text
Initializing job 'rg' with args '{ "--no-config", "--type=md", "--json", "--fixed-strings", "--ignore-case", "-g!extra/templates", "-m=1", "-e", "nature", "/Users/tjex/obsidian/paradigm-s
Initializing job 'rg' with args '{ "--no-config", "--type=md", "--files", "-g!extra/templates", "-g", "*nature*.md", "/Users/tjex/obsidian/paradigm-shifted" }'
Press ENTER or type command to continue
E5108: Error executing lua: ...pack/packer/start/obsidian.nvim/lua/cmp_obsidian_new.lua:44: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...pack/packer/start/obsidian.nvim/lua/cmp_obsidian_new.lua:44: in function 'complete'
        .../nvim/site/pack/packer/start/nvim-cmp/lua/cmp/source.lua:326: in function 'complete'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:299: in function 'complete'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:77: in function 'complete'
        ...te/pack/packer/start/nvim-cmp/lua/cmp/config/mapping.lua:139: in function 'on_keymap'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:145: in function 'callback'
        ...site/pack/packer/start/nvim-cmp/lua/cmp/utils/keymap.lua:133: in function <...site/pack/packer/start/nvim-cmp/lua/cmp/utils/keymap.lua:127>
Press ENTER or type command to continue
```

However, after stepping through the error messages with enter, completion does execute properly (i.e. returning me a list of matching note titles in the cmp popup window).

So I'm very confused what to think about the bug.

My full conf is [here in my dotfiles repo](https://github.com/tjex/dotfiles/blob/mac/.config/nvim/after/plugin/obsidian.lua).

Minimal conf:

```lua
require("obsidian").setup({
	log_level = vim.log.levels.WARN,
	workspaces = {
		{
			name = "paradigm-shifted",
			path = "~/obsidian/paradigm-shifted",
		},
	},
	detect_cwd = false,
	disable_frontmatter = true,
	notes_subdir = "forrest-floor", -- main notes sub dirctory
	finder = "telescope.nvim",

	completion = {
		nvim_cmp = true,
		min_chars = 2,
		new_notes_location = "notes_subdir",
	},
})
```

nvim-cmp minimal conf:

```lua
cmp.setup ({
	sources = cmp.config.sources({
		{ name = "nvim_lsp" },
		{ name = "nvim_lua" },
		{ name = "path" },
		{ name = "luasnip" },
		{ name = "buffer", keyword_length = 5 },
	}, {
		{ name = "buffer" },
	}),
	formatting = {
		format = lspkind.cmp_format {
			mode = "symbol",
			maxwidth = 50,
			ellipsis_char = "...", -- when popup menu exceed maxwidth, the truncated part would show ellipsis_char instead (must define maxwidth first)
			menu = {
				buffer = "[buf]",
				nvim_lsp = "[LSP]",
				nvim_lua = "[api]",
				path = "[path]",
				luasnip = "[snip]",
			},
		},
	},
})
```

### Versions

MacOS 13.5

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891
```
```
[obsidian.nvim (v2.3.1)] Commit SHA: 6ddc2d4dbe044b8e114c52633c04391077f1f734
[plenary.nvim] Commit SHA: 55d9fe89e33efd26f532ef20223e5f9430c8b0c0
[nvim-cmp] Commit SHA: 538e37ba87284942c1d76ed38dd497e54e65b891
[telescope.nvim] Commit SHA: 7011eaae0ac1afe036e30c95cf80200b8dc3f21a
ripgrep 14.0.3
```

**Comment by epwalsh** [comment]
Hey @tjex I just pushed a commit to `main`(25b0fa1) that will log the inputs that led to the error when this happens. Can you try with that?

But I may know what the issue is anyway: is your vault configured behind a symbolic link? https://github.com/epwalsh/obsidian.nvim#configuring-vault-directory-behind-a-link

**Comment by tjex** [comment]
Thanks for the commit and suggestion.
My vault isn't a symbolic link.

I also tried to change the path in my config to `/Users/tjex/obsidian/...` rather than `~/obsidian`.

After the update, I get less and smaller errors. So it's a step in the right direction haha.

Broken down as:

1. enter the note at `~/obsidian/paradigm-shifted/ref-notes/chokepoint capitalism.md`
2. invoke completion within this note.
3. an error is returned, but it only flashes up briefly. The completion box then appears as expected

error:

```text
Failed to resolve path '/forrest-floor/1702664690-WZWW.md' relative to vault root '/Users/tjex/obsidian/paradigm-shifted'
```

The weird thing is that the note that I'm working on is in the subfolder "ref-notes", not "forrest-floor", and the note is definitely not titled that. I also do not have a note in my forrest-floor subfolder with that title. 

My paths are configured as so:

```lua
	workspaces = {
		{
			name = "paradigm-shifted",
			path = "~/obsidian/paradigm-shifted",
		},
	},
	notes_subdir = "forrest-floor", 
	completion = {
		nvim_cmp = true,
		min_chars = 2,
		new_notes_location = "notes_subdir",
	},
```

It almost 'feels' like, cmp is getting confused by being executed in file that is outside of its `new_notes_location`? That is of course a wild stab in the dark...

...but I did a quick check, and removing the `new_notes_location` assignment in `completion` does allow me to execute completion without error. And in the screenshot, there is an entry to create the note that is from the error message. 

So there does seem to be some weird behaviour when executing completion from a directory other than what is assigned to `completion = { new_notes_dir }`.

![Screenshot 2023-12-15 at 19 24 58](https://github.com/epwalsh/obsidian.nvim/assets/83029642/d35fe14a-7cb5-451c-9e01-392b691963a6)

**Comment by epwalsh** [comment]
Ah, okay that's super helpful! I'll try to reproduce and then go from there.

**Comment by epwalsh** [comment]
One more question: is `~/obsidian/paradigm-shifted` an actual Obsidian vault? In other words, does the directory `~/obsidian/paradigm-shifted/.obsidian/` exist?

**Comment by epwalsh** [comment]
What's odd to me is that in this error message:

```
Failed to resolve path '/forrest-floor/1702664690-WZWW.md' relative to vault root '/Users/tjex/obsidian/paradigm-shifted'
```

It shows that the path "/forrest-floor/1702664690-WZWW.md"has a leading "/". This shouldn't happen, and I'm not sure why it happens for you. So far I haven't been able to reproduce that.

That path comes from [this line](https://github.com/epwalsh/obsidian.nvim/blob/6a3ce7ae1d1748a8ae7f699b9ef446067946d7c0/lua/cmp_obsidian_new.lua#L43). If you get a chance could you add print out what `dir` is before that line?

**Comment by tjex** [comment]
Yup, `.obsidian` is there.
```text
~/obsidian/paradigm-shifted main* ≡
sys > ls -la
drwxr-xr-x tjex staff 384B Fri 15 Dec .
drwxrwx--- tjex staff 256B Fri 15 Dec ..
drwxr-xr-x tjex staff 704B Tue 26 Sep .obsidian
drwxr-xr-x tjex staff 1.5K Thu 14 Dec diaries
drwxr-xr-x tjex staff 224B Tue 19 Sep extra
drwxr-xr-x tjex staff 5.2K Fri 15 Dec forrest-floor
drwxr-xr-x tjex staff 736B Fri 15 Dec forrest-people
drwxr-xr-x tjex staff 2.3K Fri 15 Dec glossary
drwxr-xr-x tjex staff 224B Tue 19 Sep masters
drwxr-xr-x tjex staff 384B Tue 19 Sep mocs
drwxr-xr-x tjex staff 2.1K Fri 15 Dec ref-notes
```

Sorry, but I don't understand what you'd like me to do.

Do you mean to paste here the directory before `/forrest-floor/1702664690-WZWW.md`?
That is then as above: `~/obsidian/paradigm-shifted`

I also tried to manually prepend the `/` to the path in config. i.e. `notes_subdir = "/forrest-floor". But it didn't change.

## Potentially found the problem

Keeping the above as context incase its useful. But I think I found the issue, or in any case definitely some weird behaviour. 

The thought occurred to me that maybe lua is freaking out because it doesn't like hyphens in path names / strings if I'm not mistaken? i.e `-`.

I changed my folder names to use `_` instead of `-`. And I could execute completion without error. 

However, if I tried the 'reverse', where I kept hyphens in the directories on my system, but changed the path name strings in obsidian.nvim config to use underscores; and I could also execute completion without error. This is standard lua behaviour from what I understand (underscores in path strings can be underscores *or* hyphens in system directories).

However, what makes me think it's an issue in obsidian.nvim code is because I can still use hyphens in the path strings in obsidian.nvim config, while having underscores in my system directories. 

If lua was only ever wanting to see underscores, then it would throw an error when being provided path strings with hyphens **regardless** of whether my system directories had hyphens or not?

So the above in code:

This config allows errorless execution of completion with system directory: `~/obsidian/paradigm-shifted/forrest-floor`, but **not** `~/obsidian/paradigm_shifted/forrest_floor`.
```lua
	workspaces = {
		{
			name = "paradigm_shifted",
			path = "~/obsidian/paradigm_shifted",
		},
	},
	notes_subdir = "forrest_floor",

```

This config allows errorless execution of completion with system directory: `~/obsidian/paradigm_shifted/forrest_floor`, but **not** `~/obsidian/paradigm-shifted/forrest-floor`.

```lua
	workspaces = {
		{
			name = "paradigm-shifted",
			path = "~/obsidian/paradigm-shifted",
		},
	},
	notes_subdir = "forrest-floor",

```

**Comment by tjex** [comment]
Even more strangely... 

This config **also** allows for errorless execution of completion despite the `notes_subdir` having a hyphen, while the other subdirs require underscores (system file path during this test: `~/obsidian/paradigm-shifted/forrest-floor`

```lua
	workspaces = {
		{
			name = "paradigm-shifted",
			path = "~/obsidian/paradigm-shifted",
		},
	},
	notes_subdir = "forrest_floor",
```

**Comment by tjex** [comment]
And now I get an error about my templates dir:

```text
Error detected while processing /Users/tjex/.config/nvim/after/plugin/obsidian.lua:
'/Users/tjex/obsidian/paradigm_shifted/extra/templates' is not a valid directory for templates
```

Because my vault is still with hyphen `paradigm-shifted` (whereby I don't get cmp errors).

**Comment by roceb** [comment]
I have a similar error, my vault isn't hyphen and it is full path.
``` Error detected while processing TextChangedI Autocommands for "*":
Error executing lua callback: ...pack/packer/start/obsidian.nvim/lua/cmp_obsidian_new.lua:67: attempt to concatenate local 'new_title' (a nil value)
stack traceback:
        ...pack/packer/start/obsidian.nvim/lua/cmp_obsidian_new.lua:67: in function 'complete'
        .../nvim/site/pack/packer/start/nvim-cmp/lua/cmp/source.lua:326: in function 'complete'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:299: in function 'complete'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:169: in function 'autoindent'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:161: in function 'on_change'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:338: in function 'callback'
        ...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:49: in function 'emit'
        ...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:23: in function <...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:22>
        ```

**Comment by epwalsh** [comment]
@roceb that looks like a different issue. What did you type that triggered that error?

**Comment by roceb** [comment]
Whenever I make a check box. I assume that the "[" triggers cmp.

**Comment by epwalsh** [comment]
@roceb can you open a separate bug report and post your config there?

**Comment by epwalsh** [comment]
@tjex I'm still scratching my head on this one...

I've tried to reproduce the error you get on my own MacBook with the same config and directory structure but no luck (it works as expected for me) 🤔

> Sorry, but I don't understand what you'd like me to do.

I just wanted you to put some print statements in so I could see what was going on. But I did that on a new branch: `epwalsh/tjex-debug`. Can you checkout that branch and let me know what gets logged again?

As for the underscores vs hyphens thing... You should definitely be consistent between your filesystem and config since `~/obsidian/paradigm_shifted` is **not** the same directory as `~/obsidian/paradigm-shifted`. The weird results you got are probably masking the real issue.

**Comment by tjex** [comment]
@epwalsh ... I've also just entered into a new realm of confusion.

As of this morning everything works fine ... 😔 I did make a few config changes to other plugins / programs last night unrelated to this issue. But I also rolled back those changes and tested again. 

Also weird is that sometimes the log printing doesn't appear. I tried in mac Terminal and it appears every time, but in wezterm it shows *mostly* every time (on execution of cmp).

I'm really a bit stunned and worried I've wasted your time a bit. It's just weird because I would think that it could be related to how I've setup wezterm vs terminal, but seeing as though we're dealing with everything inside neovim... It should be the same between both.

```text
search: 'Chin', new_id: '1702814230-UIVY', dir: '/Users/tjex/obsidian/paradigm-shifted/forrest-floor'
```

![Screenshot 2023-12-17 at 12 58 23](https://github.com/epwalsh/obsidian.nvim/assets/83029642/e0ed1b81-0a95-4556-a001-bb6f3b1e84db)

I'll close for now, but reopen if this reoccurs and I have some more useful / reproducible information for you...

**Comment by epwalsh** [comment]
@tjex no worries, I'm glad it's working now! I'm surprised that the choice of terminal changes the behavior and I have no idea why. FWIW I've been using Alacritty as my terminal on Macs for 4+ years now and have been very happy.

**Comment by tjex** [comment]
@epwalsh It is better it's working haha. Although the 'mysteriousness' of why mixed with 'wtf is up with my environment' is a bummer haha. I tried Alacritty, but it didn't stick for some reason. I think the configuration of it / lack of some features. 

I love wezterm as it's a) cross platform, b) configurable with lua and to quite a low level and c) has a built in multiplexer (also running mux clients on remote machines) which has replaced tmux 1:1 for me.
