### ISSUE TITLE
Concealment of Todo, checked or postponed items not working as expected

### ISSUE THREAD

**Issue by Msouza91** [epwalsh/obsidian.nvim#264]
### 🐛 Describe the bug

I just started using the plugin, finished the setup with some customizations the concealment of the todo items didn't work then I tried explicitly put the ui block in the config file for testing, but it only does the substitution for the text parameters, but even then it wont hide the md sybols like `===` or `*` here is the configuration I'm using for the plugin: https://gist.github.com/Msouza91/951943600c5d80e53292a8a8702685cc.
An image showing what I mean:
![image](https://github.com/epwalsh/obsidian.nvim/assets/19522556/42f1f006-a659-4770-9284-fd90c4dff661)

Tested with treesitter option `additional_vim_regex_highlighting = false` and `additional_vim_regex_highlighting = { "markdown" }`

### Versions

nvim --version
```
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```
nvim --headless -c 'lua require("obsidian").info()' -c q
```
[obsidian.nvim (v2.3.1)] Commit SHA: ce58193226fa72302ad0732aa61d6a4bec3f0789
[plenary.nvim] Commit SHA: 55d9fe89e33efd26f532ef20223e5f9430c8b0c0
[nvim-cmp] Commit SHA: 538e37ba87284942c1d76ed38dd497e54e65b891
[telescope.nvim] Commit SHA: d90956833d7c27e73c621a61f20b29fdb7122709
ripgrep 13.0.0%   
```

**Comment by epwalsh** [comment]
Hey @Msouza91 what's your conceallevel set to?

```
:set conceallevel?
```

**Comment by Msouza91** [comment]
I was not aware of the option and setting it to one solved the problem, double checked on the readme and didn't see mention to this needing to be set.
Setting it to 1 resolved my problem, I'll close it as it is not a bug, but will submit a PR to the doc mentioning that you may need to set this option to enable the feature.

**Comment by epwalsh** [comment]
PR would be appreciated! Thanks
