### ISSUE TITLE
Creating Markdown Links - Cannot Cycle Through Ripgrep Results

### ISSUE THREAD

**Issue by sixstorm** [epwalsh/obsidian.nvim#268]
### 🐛 Describe the bug

When creating a new Markdown link '[', I can start typing the name of a file I want to link and the results show up via RipGrep from the Obsidian Vault.  However, pressing Tab or using the arrow keys won't allow me to cycle down through the list.  Pressing Enter will not select the first highlighted note if I type the entire name out.  I've re-read the Readme multiple times but I don't see any mappings or ways to accomplish this.  Even if I type the whole name out in a Markdown link, it does not link to the actual document itself.

![image](https://github.com/epwalsh/obsidian.nvim/assets/13417063/18ba4737-ba77-4d9d-beeb-e6f492bed661)
![image](https://github.com/epwalsh/obsidian.nvim/assets/13417063/b320f063-3387-4efc-917d-ee81cb282daf)

### Versions

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.4/share/nvim"

Run :checkhealth for more info

[obsidian.nvim (v2.3.1)] Commit SHA: ce58193226fa72302ad0732aa61d6a4bec3f0789
[plenary.nvim] Commit SHA: 55d9fe89e33efd26f532ef20223e5f9430c8b0c0
[nvim-cmp] Commit SHA: 538e37ba87284942c1d76ed38dd497e54e65b891
[telescope.nvim] Commit SHA: d90956833d7c27e73c621a61f20b29fdb7122709
ripgrep 14.0.3%

**Comment by epwalsh** [comment]
Hey @sixstorm, this is probably an issue with your `nvim-cmp` config. This is my cmp config, in case that helps: https://github.com/epwalsh/dotfiles/blob/5d4bfea06bbddbf1827aa6f5c84a578157b51462/neovim/lua/plugins/completion.lua#L59

**Comment by sixstorm** [comment]
Hey @epwalsh , thank you for this.  I'll have to take a closer look at the CMP mappings a bit further.  When I put the "complete" and "insert" mappings as you have it, it finally links properly!  Thanks again!

**Comment by epwalsh** [comment]
Glad to hear it!
