### ISSUE TITLE
[Feature] Display document context when searching for text

### ISSUE THREAD

**Issue by pidgeon777** [epwalsh/obsidian.nvim#28]
### 🚀 The feature, motivation and pitch

Let's consider a file named `FILE.md` with the following content:

```markdown
# Title

## Subtitle

hello world
hello adam

### Subsubtitle

hello everyone
```

Let's suppose I would like to search for the word `hello` in the document. I would like to have the following result:

```
C:\Path\to\FILE.md:
Title -> Subtitle
hello world
hello adam
Title -> Subtitle -> Subsubtitle
everyone hello
```

This means displaying the markdown context of the searched text.

Alternatively:

```
C:\Path\to\FILE.md | Title -> Subtitle                | hello world
C:\Path\to\FILE.md | Title -> Subtitle                | hello adam
C:\Path\to\FILE.md | Title -> Subtitle -> Subsubtitle | everyone hello
```

**Comment by epwalsh** [comment]
Hey @pidgeon777, is this with respect to the new `:ObsidianSearch` command, or searching some other method?

**Comment by pidgeon777** [comment]
I don't know if this could be implemented directly with tools such as `ripgrep`, but LSP would certainly help.

For example, an algorithm could be: search the line and column number of all the search occurrences with `ripgrep`, and then use those (line; column) "coordinates" to identify the scope of the section of the occurrences by using, for example, the `DocumentSymbol` feature of the active LSP (such as done with the breadcrumb view usually available in modern editors).

**Comment by epwalsh** [comment]
I'm not clear where exactly this would fit. `:ObsidianSearch` will already show the preview of document and highlight the line where the match was, at least with telescope.nvim.
