### ISSUE TITLE
Commands are not available outside of the vault

### ISSUE THREAD

**Issue by Christopher876** [epwalsh/obsidian.nvim#280]
### 🐛 Describe the bug

This is a continuation of this bug https://github.com/epwalsh/obsidian.nvim/issues/234

It appears that the fix that was added is no longer working. This piece of code and the setup function itself are no longer being executed outside of the vault folder
```lua
 -- Install commands.
 -- These will be available across all buffers, not just note buffers in the vault.
 obsidian.command.install(client)
```

Here is my current config using lazy:
```lua
{
    "epwalsh/obsidian.nvim",
    version = "*",
    lazy = true,
    ft = "markdown",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    opts = {
      workspaces = {
        {
          name = "personal",
          path = "~/Obsidian/notes/",
        },
      },
    },
  },
```

### Versions

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

```
[obsidian.nvim (v2.4.0)] Commit SHA: 319f06024cdde97e0c2c3a836dff49b9f0d5f3bd
[plenary.nvim] Commit SHA: 55d9fe89e33efd26f532ef20223e5f9430c8b0c0
[nvim-cmp] Commit SHA: 538e37ba87284942c1d76ed38dd497e54e65b891
[telescope.nvim] Commit SHA: c0ee29e8e4700ef49623d12ca3ffb8481c8d69f3
[fzf.vim] Commit SHA: 1e054c1d075d87903647db9320116d360eb8b024
ripgrep 14.0.3%  
```

**Comment by epwalsh** [comment]
Hey @Christopher876, based on your config Obsidian.nvim should be set up anytime you open a markdown file regardless of location. Is that not the case?

**Comment by Christopher876** [comment]
It doesn't appear so, only when I open a note in the vault are the commands available

**Comment by epwalsh** [comment]
Hmm this is pretty odd! Did you check `:messages` for any errors? And what happens if you remove the `ft = "markdown"` from your Lazy config there?

**Comment by Christopher876** [comment]
Nothing appears in `:messages`. However, I did find that if I comment out both `lazy` and `ft`, the commands become available. They are not available if just one or the other is commented out

**Comment by epwalsh** [comment]
@Christopher876 ah right, that makes sense. Maybe for some reason markdown files outside of your vault are not detected as markdown? You can check with `:set ft?`.

**Comment by Christopher876** [comment]
Yeah, that was the problem, I've since resolved the issue. However, I still need to disable `lazy` for the commands to be available when opening any file

**Comment by epwalsh** [comment]
Yea if you really do want the commands to be available in any filetype, then `lazy = false` is the right thing to do. Sounds like we can close this but let me know if you run into other issues. ✌️
