### ISSUE TITLE
Checkboxes not rendering

### ISSUE THREAD

**Issue by hsheikhali1** [epwalsh/obsidian.nvim#283]
### 🐛 Describe the bug

Not sure where to ask this question other than a bug request.. but I can't get them to render properly

![CleanShot 2023-12-30 at 12 04 42@2x](https://github.com/epwalsh/obsidian.nvim/assets/14851850/f4db5787-b175-4999-8f5a-9f3254234196)

### Versions

All versions are up to date etc.. like I said not sure where to ask this question other than create a bug ticket

**Comment by epwalsh** [comment]
Hey @hsheikhali1, I'm guessing you need to set `conceallevel` to a higher value, such as 2. See https://github.com/epwalsh/obsidian.nvim/issues/264 and https://github.com/epwalsh/obsidian.nvim#concealing-characters.

**Comment by hsheikhali1** [comment]
> Hey @hsheikhali1, I'm guessing you need to set `conceallevel` to a higher value, such as 2. See #264 and https://github.com/epwalsh/obsidian.nvim#concealing-characters.

Thanks @epwalsh that's exactly what I was looking for !!
