### ISSUE TITLE
Assertion failure when doing `:ObsidianOpen`

### ISSUE THREAD

**Issue by the-shank** [epwalsh/obsidian.nvim#285]
### 🐛 Describe the bug

Thanks for the amazing plugin!

I have the vault path set to absolute (not a link). However, when I try using `:ObsidianOpen`, I get an error:

![image](https://github.com/epwalsh/obsidian.nvim/assets/546476/220cb79d-f92a-4663-b080-eb847ef5fa2f)

I tried debugging it, and the error seems to go away if I do `return relative_path` instead of `return nil` at [this](https://github.com/epwalsh/obsidian.nvim/blob/88bf9150d9639a2cae3319e76abd7ab6b30d27f0/lua/obsidian/client.lua#L125) line. Both `relative_path` and `normalized_path` have the same value (the doc name, not the doc path) at this point.

Please let me know if I can provide any other information to help debug this.

### Versions

[lazy-lock.json](https://github.com/epwalsh/obsidian.nvim/files/13801109/lazy-lock.json)

**Comment by epwalsh** [comment]
Hey @the-shank, is your vault behind a symlink? There's a known issue about this here: https://github.com/epwalsh/obsidian.nvim#configuring-vault-directory-behind-a-link

Otherwise could you let me know your vault path and the path of the note you're trying to open so I can debug further?

**Comment by the-shank** [comment]
Hey @epwalsh, the vault isn't behind a symlink. And thanks for getting back on this so quickly!

Here are some of the details:

Path to vault: `~/Sync/MyBrain`

All notes are directly inside the vault directory.

Test Note: `test-nvim-obsidian.md`.
Linked Note: `test-linked-note.md`.

Contents of Test Note:
```md
refs: [[test-linked-note]]
```

I added a log to debug this and both the `relative_path` and `normalized_path` on [this](https://github.com/epwalsh/obsidian.nvim/blob/88bf9150d9639a2cae3319e76abd7ab6b30d27f0/lua/obsidian/client.lua#L116C1-L116C1) line evaluate to `test-linked-note.md` for this sample test case. And therefore the `string.find()` on the next line doesn't find the `self:vault_name()` in `relative_path`, setting `j` to be `nil`.

Please let me know if any other information is required to debug this.

**Comment by epwalsh** [comment]
Perfect! I was able to reproduce and I think your proposed fix is the right thing to do. PR here: #291
