### ISSUE TITLE
Markdown not rendering

### ISSUE THREAD

**Issue by catasaurus** [epwalsh/obsidian.nvim#286]
### 🐛 Describe the bug

When I create checkboxes, they simply do not render. I don't know the expected behavior for the rendering of other markdown, but I have seen screenshots of checkboxes rendered. I know I wrote them right as when I open the file in Obsidian (the desktop client), they render perfectly fine.
```id: 1704062531-GHQA
aliases:
  - test_markdown_rendering
tags: []
---

# test_markdown_rendering

- [ ] testing this still

## markdown not rendering for some reason
- [ ] item 2

### Versions

~ via 🐍 v3.9.12 
❯ nvim --version
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.4/share/nvim"

Run :checkhealth for more info

~ via 🐍 v3.9.12 
❯               
nvim --headless -c 'lua require("obsidian").info()' -c q
[obsidian.nvim (v2.5.0)] Commit SHA: 88bf9150d9639a2cae3319e76abd7ab6b30d27f0
[plenary.nvim] Commit SHA: 55d9fe89e33efd26f532ef20223e5f9430c8b0c0
[nvim-cmp] Commit SHA: 538e37ba87284942c1d76ed38dd497e54e65b891
[telescope.nvim] Commit SHA: d90956833d7c27e73c621a61f20b29fdb7122709
ripgrep 14.0.3%                                                                                                                                     

~ via 🐍 v3.9.12 
❯

**Comment by sebassdc** [comment]
Same issue here

```
❯ nvim --headless -c 'lua require("obsidian").info()' -c q
[obsidian.nvim (v2.5.0)] Commit SHA: 88bf9150d9639a2cae3319e76abd7ab6b30d27f0
[plenary.nvim] Commit SHA: 55d9fe89e33efd26f532ef20223e5f9430c8b0c0
[nvim-cmp] Commit SHA: 538e37ba87284942c1d76ed38dd497e54e65b891
[telescope.nvim] Commit SHA: 54930e1abfc94409e1bb9266e752ef8379008592
[vim-markdown] Commit SHA: 46add6c3017d3e4035dc10ffa9cb54221d8dfe1a
ripgrep 13.0.0%
```

**Comment by epwalsh** [comment]
Hey @catasaurus, please check if your `conceallevel` is set properly. See https://github.com/epwalsh/obsidian.nvim#concealing-characters.

**Comment by alphaone** [comment]
I have a similar issue. I have to set the `conceallevel` exactly to "1", to see the rendered checkboxes:
<img width="315" alt="Screenshot 2024-01-04 at 16 11 36" src="https://github.com/epwalsh/obsidian.nvim/assets/40830/000a6471-ed0e-4e34-b66f-0e6ad6684345">

For `conceallevel=0` I get this (expected):
<img width="319" alt="Screenshot 2024-01-04 at 16 12 33" src="https://github.com/epwalsh/obsidian.nvim/assets/40830/67638682-31ef-4372-9473-e1db63aa58cd">

For `conceallevel=3` (which is my default) I get nothing (unexpected):
<img width="316" alt="Screenshot 2024-01-04 at 16 13 31" src="https://github.com/epwalsh/obsidian.nvim/assets/40830/ec649bdf-a13b-4f76-a6e9-7dcc5b8f2cb3">

**Comment by sebassdc** [comment]
@epwalsh @alphaone Thank you! that did the trick on my end

**Comment by epwalsh** [comment]
Just to reiterate, obsidian.nvim sets explicit conceal characters, so either `conceallevel=1` or `conceallevel=2` will work. `conceallevel=3` forces even the overlayed characters to be hidden. A quick way to ensure this is set correctly for markdown files is to add a file called `after/ftplugin/markdown.lua` in your neovim config directory (usually `~/.config/nvim`) with the following:

```lua
vim.opt_local.conceallevel = 2
```

I've just pushed a commit that will warn users when they have obsidian.nvim's UI features enabled yet their conceallevel isn't set correctly.

**Comment by FilipHarald** [comment]
@epwalsh I think the conceal-level warning could be useful. But how do I turn the warning off if I want to see all characters, and actually have `vim.opt_local.conceallevel = 0`?

**Comment by epwalsh** [comment]
@FilipHarald you can simply disable this plugin's UI features by setting `ui.enable = false` in your obsidian.nvim config.

**Comment by catasaurus** [comment]
Thanks for all the help! Sorry I took a while to check back on this.

**Comment by anuramat** [comment]
is it possible to suppress the warning without turning off the the feature? I have a `vim: cole=0` modeline in some of the files

**Comment by epwalsh** [comment]
Hey @anuramat you could set `log_level = vim.log.levels.ERROR`, but that would disable pretty much all messages, so might not be desirable. I'm happy to accept a PR to disable to disable this. In particular we could add another config field like `disable_user_warnings: boolean`.

**Comment by dromse** [comment]
@epwalsh It would be awesome to have this warning disable option. Because I use only conceallevel=0, and I need only colorized checkboxes. But when I open my notes this warning is disrupting me all time from doing another things.

**Comment by robertjdominguez** [comment]
@epwalsh, I know this is closed, but a related question: should this configuration work in LazyVim as well? As you can see in this recording, with `conceallevel` set to `1`, checkboxes continue to not render while other formatting does.

Thanks for any guidance!

https://github.com/epwalsh/obsidian.nvim/assets/24390149/deeb24ea-aa5d-4d7b-a5c5-ddad7b1589ed

**Comment by epwalsh** [comment]
@robertjdominguez that looks like a font issue. If you don't have a patched font you'll need to use different characters than what's in the README.

**Comment by robertjdominguez** [comment]
Bang on! Great call — thanks, @epwalsh 🙏

**Comment by swahpy** [comment]
Hi JFYI,
I also setup [markdown_oxide](https://github.com/Feel-ix-343/markdown-oxide) in my neovim config and after that the conceallevel I've set in obsidian.lua was overwritten. Like below(the lsp configurations), I have to config conceallevel again in lsp config.
```lua
["markdown_oxide"] = function ()
  lspconfig.markdown_oxide.setup({
    capabilities = capabilities, -- again, ensure that capabilities.workspace.didChangeWatchedFiles.dynamicRegistration = true
    ---@diagnostic disable-next-line:unused-local
    on_attach = function (client, bufnr)
      -- refresh codelens on TextChanged and InsertLeave as well
      vim.api.nvim_create_autocmd({ 'TextChanged', 'InsertLeave', 'CursorHold', 'LspAttach' }, {
        buffer = bufnr,
        callback = vim.lsp.codelens.refresh,
      })

      -- trigger codelens refresh
      vim.api.nvim_exec_autocmds('User', { pattern = 'LspAttached' })

      -- setup conceallevel to enable it in obsidian.nvim
      vim.opt.conceallevel = 2
    end
  })
end
```
And to disable the warning message I have to set it again in obsidian.nvim setup function.

**Comment by jjrp78** [comment]
Hi all, 
I have a weird behavior. My conceal level is 2. When I add checkboxes and while Im still  in input mode they render fine, but as soon as I switch to normal mode they turn into bullets:

<img width="618" alt="Image" src="https://github.com/user-attachments/assets/fcbb69fa-4910-4ac4-abd9-793f310a5010" />

<img width="666" alt="Image" src="https://github.com/user-attachments/assets/a5afe3ae-70ee-4f77-a27f-6f1245797e87" />

Any ideas what is going wrong?

**Comment by arcaartem** [comment]
> Hi all, I have a weird behavior. My conceal level is 2. When I add checkboxes and while Im still in input mode they render fine, but as soon as I switch to normal mode they turn into bullets:
> 
> <img alt="Image" width="618" src="https://private-user-images.githubusercontent.com/1482465/417068277-fcbb69fa-4910-4ac4-abd9-793f310a5010.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY4NjM5ODEsIm5iZiI6MTc0Njg2MzY4MSwicGF0aCI6Ii8xNDgyNDY1LzQxNzA2ODI3Ny1mY2JiNjlmYS00OTEwLTRhYzQtYWJkOS03OTNmMzEwYTUwMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDUxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA1MTBUMDc1NDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJiN2U1NzUzN2M0ZmMwZWJiNGUxMWQ0NjUzOTZlZTgxOWYxNTFmZmFlOGY1YTIxYjg4YWFjYmZlY2IzNmFjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AvyuSWfizY96eytgMBZpolXAobv8z2mld-xdXJwVYnw"> <img alt="Image" width="666" src="https://private-user-images.githubusercontent.com/1482465/417068495-a5afe3ae-70ee-4f77-a27f-6f1245797e87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY4NjM5ODEsIm5iZiI6MTc0Njg2MzY4MSwicGF0aCI6Ii8xNDgyNDY1LzQxNzA2ODQ5NS1hNWFmZTNhZS03MGVlLTRmNzctYTI3Zi02ZjEyNDU3OTdlODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDUxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA1MTBUMDc1NDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2I5MGE3YjAyYWYzMTMxMTQwOTY0ZjM4NTY4MjBhMTAwYWIxZjU2Y2EyOWUzMjdkYWM0YWE3N2I1NmQ4YmM3MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.q_37B80y3qJNTHjYHp0nb7R3EpRg9FoSC4M6yapdjrk">
> Any ideas what is going wrong?

Are you using [markview.nvim](https://github.com/OXY2DEV/markview.nvim) or any other plugin to render markdown files by any chance? Markview will override the `conceallevel` after a mode change.

**Comment by AntraXClown** [comment]
I was use LazyVim and its problem is because plugin markdown-preview.nvim, everytime this plugin set conceallevel to 3, every time. I disable markdown lang, and everything works flawless.
