### ISSUE TITLE
Error when opening or inserting links

### ISSUE THREAD

**Issue by tott** [epwalsh/obsidian.nvim#289]
### 🐛 Describe the bug

Love the plugin but run into a bit of an issue with links inserting or following. In either case I'm getting similar errors. 
When typing `[[something` to trigger the autocomplete it will give me the following message

`2 error(s) occurred during search. First error from note at '/home/xxx/vaults/notes/2024-01-01-xxx.md':
...te/pack/packer/start/obsidian.nvim/lua/obsidian/note.lua:161: ...te/pack/packer/start/obsidian.nvim/lua/obsidian/note.lua:326: E5560: vimL function must not be called in a lua loop
callback`

I'm getting a similar message when I enter the link manually and try to follow it using the `gf` command. In these cases I get the following message

`Error executing luv callback:
...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...te/pack/packer/start/obsidian.nvim/lua/obsidian/note.lua:161: ...te/pack/pack
er/start/obsidian.nvim/lua/obsidian/note.lua:326: E5560: vimL function must not be called in a lua loop callback
stack traceback:
        [C]: in function 'error'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:45: in function <...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:44>`

### Versions

# nvim --version
NVIM v0.9.0-dev-683+gd549734fb
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g  -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=always -fstack-protector-strong -DNVIM_UNIBI_HAS_VAR_FROM -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -I/home/xxx/work/projects/private/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/xxx/work/projects/private/neovim/.deps/usr/include -I/home/xxx/work/projects/private/neovim/build/src/nvim/auto -I/home/xxx/work/projects/private/neovim/build/include -I/home/xxx/work/projects/private/neovim/build/cmake.config -I/home/xxx/work/projects/private/neovim/src
Compiled by root@enterprise

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

# nvim --headless -c 'lua require("obsidian").info()' -c q

[obsidian.nvim (v2.5.0)] Commit SHA: 88bf9150d9639a2cae3319e76abd7ab6b30d27f0
[plenary.nvim] Commit SHA: 55d9fe89e33efd26f532ef20223e5f9430c8b0c0
[nvim-cmp] Commit SHA: 538e37ba87284942c1d76ed38dd497e54e65b891
[telescope.nvim] Commit SHA: b79cd6c88b3d96b0f49cb7d240807cd59b610cd8
ripgrep 13.0.0 (rev 7ec2fd51ba)%

**Comment by epwalsh** [comment]
Hey @tott, could you see if #290 fixes this for you?

**Comment by tott** [comment]
Hi @epwalsh, that was quick - this works like a charm! Thanks

**Comment by epwalsh** [comment]
Awesome! I'll merge and release.

**Comment by Muhammad-Aadil** [comment]
I am facing this issue
