### ISSUE TITLE
Unclear on how ObsidianPasteImg command Works/Is configured

### ISSUE THREAD

**Issue by me11203sci** [epwalsh/obsidian.nvim#297]
### 📚 The doc issue

Greetings. Allow me to begin by praising this wonderful plugin! I have found it so helpful and useful, however I have been unable to get the image paste command to work. I go and get the path to an image and then try to run the command but only receive the error message "There is no image data in the clipboard". I am not sure if I have set this up correctly.

**Comment by epwalsh** [comment]
Hey @me11203sci sorry if this wasn't clear, but the command is meant to be used to paste an image from the clipboard, i.e. you should use it when your system clipboard contains an actual image, not the path to an image.

**Comment by me11203sci** [comment]
Hmmm, after going to Google and attempting to copy image data into my clipboard by right-clicking and selecting "Copy Image" I get the following error.
![image](https://github.com/epwalsh/obsidian.nvim/assets/35207935/442ca9eb-0c59-4470-986c-158ae48e8d1c)

**Comment by epwalsh** [comment]
@me11203sci what's the format of the image you tried to paste? It might only work with png.

**Comment by me11203sci** [comment]
https://en.wikipedia.org/wiki/ABBA#/media/File:ABBA_-_TopPop_1974_5.png

I have been testing it with this image.

**Comment by epwalsh** [comment]
Thanks @me11203sci.  Pasting this image works on my Mac, so it sounds like this Linux-specific code here is not working as intended:

https://github.com/epwalsh/obsidian.nvim/blob/3c99b2cfc120321d6c0e96ebe35941d22664fa86/lua/obsidian/img_paste.lua#L41-L42

Maybe @sQVe could help debugging this?

**Comment by bcl1713** [comment]
linux mint here and pasting images works fine for me on neovim 0.9.5 and 0.10

**Comment by me11203sci** [comment]
I got it to work. It was in fact a configuration error, I was on using wayland but only had xclip installed. Installing wl-clipboard solved my issue.
