### ISSUE TITLE
Open input prompt when using with key map

### ISSUE THREAD

**Issue by destnguyxn** [epwalsh/obsidian.nvim#299]
### 🚀 The feature, motivation and pitch

When using with keymap such as which-key, I want a simple config that opens to type the input the same as in **AdvancedNewFile.nvim** for commands **ObsidianNew** and **Obsidian rename**.

Can you implement this or guide me on how to set things up?
Thank you~

**Comment by bcl1713** [comment]
This is what I have in my keybind for new file that gets me what you want.  ObsidianRename isn't working for me at all at the moment, but a similar function should work.


```
{
  "<leader>on",
  function()
    local fname = vim.fn.input("Name: ", "", "file")
    local command = "ObsidianNew " .. fname
    vim.cmd(command)
  end,
  desc = "Obsidian New",
}
```

**Comment by epwalsh** [comment]
Hey @destnguyxn I added a prompt for `:ObsidianNew` in #296, and for `:ObsidianRename` in 3c99b2c. Let me know if that's what you're looking for.

**Comment by destnguyxn** [comment]
> Hey @destnguyxn I added a prompt for `:ObsidianNew` in #296, and for `:ObsidianRename` in [3c99b2c](https://github.com/epwalsh/obsidian.nvim/commit/3c99b2cfc120321d6c0e96ebe35941d22664fa86). Let me know if that's what you're looking for.

That's look good to me

**Comment by destnguyxn** [comment]
> This is what I have in my keybind for new file that gets me what you want. ObsidianRename isn't working for me at all at the moment, but a similar function should work.
> 
> ```
> {
>   "<leader>on",
>   function()
>     local fname = vim.fn.input("Name: ", "", "file")
>     local command = "ObsidianNew " .. fname
>     vim.cmd(command)
>   end,
>   desc = "Obsidian New",
> }
> ```

here is mine but it was not open the prompt to enter the file name, both mine and you
    ["<leader>on"] = {
      action = function()
        return "<expr>:ObsidianNew " .. vim.fn.input('file name: ') .. "<cr>"
      end,
      opts = { expr = true, buffer = false },
    },

**Comment by epwalsh** [comment]
@destnguyxn releasing in 2.6.0 right now.

**Comment by epwalsh** [comment]
Are we good to close this?

**Comment by destnguyxn** [comment]
Yes please close it, Lgtm
