### ISSUE TITLE
Unexpected current buffer change on new note

### ISSUE THREAD

**Issue by vihu** [epwalsh/obsidian.nvim#30]
### 🐛 Describe the bug

I  recently started using this plugin and noticed an oddity (which admittedly could be something to do with my setup).

I have the following keybind:

```lua
vim.keymap.set("n", "<leader>nn", function()
    return "<Cmd>ObsidianNew " .. vim.fn.input('Title: ') .. "<CR>"
end, { expr = true })
```

Essentially to make creating a new note with user supplied title.

I notice that for some reason as soon as I press enter, the new note indeed gets created as expected, but something in the currently opened buffer also changes.

Below is a video demonstrating the issue (note the little blue dot in the tabline next to obsidian.lua was not present before I created the note but is present after the creating of the note, indicating that the currrent buffer, obsidian.lua in this case has changed in some way). This causes an error when trying to exit nvim, because it thinks that the currently opened buffer has changed.

https://user-images.githubusercontent.com/3199183/195307003-bcedb27e-8c82-4d32-8aed-18464c8ceb05.mp4

### Versions

```bash
nvim --version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"
```

```bash
nvim --headless -c 'lua print(require("obsidian").VERSION)' -c q
1.4.0%
```

**Comment by epwalsh** [comment]
Hey @vihu, `:ObsidianNew` will call `:w` on the current file before switching to the new note. That could be the source of the issue. Maybe you have some autocmd that modifies lua files on write?

It's not really necessary that `:ObsidianNew` writes the current buffer before switching, so maybe we should remove that if it causes more problems.

**Comment by vihu** [comment]
> t's not really necessary that :ObsidianNew writes the current buffer before switching, so maybe we should remove that if it causes more problems.

I agree with this. Having `:ObsidianNew` and `:ObsidianToday` write out the currently opened buffer seems like unexpectedly introduced behavior to me. That's the responsibility of the user to _specifically_ choose when to write the open buffer imo.

**Comment by epwalsh** [comment]
> Having :ObsidianNew and :ObsidianToday write out the currently opened buffer seems like unexpectedly introduced behavior to me.

Fair enough. Do you want to make a PR to remove the writes? The lines are [here](https://github.com/epwalsh/obsidian.nvim/blob/5254426b386c2d40bdb3f877d947787912c296b4/lua/obsidian/command.lua#L53) and [here](https://github.com/epwalsh/obsidian.nvim/blob/5254426b386c2d40bdb3f877d947787912c296b4/lua/obsidian/command.lua#L70).

**Comment by epwalsh** [comment]
Ah, beat me to it!
