### ISSUE TITLE
ObsidianLink fails if working directory is not workspace root

### ISSUE THREAD

**Issue by hallettj** [epwalsh/obsidian.nvim#313]
#### Steps to reproduce

- in nvim, `cd` to a directory that is not in your Obsidian workspace
- open a note in your active workspace
- select some text, and run the command, `:'<,'>ObsidianLink`
- when the picker opens, select any note from the list

#### Expected results

The text should be changed to be a link to the selected note.

#### Actual results

An error is presented saying, "No such file or directory".

It looks like `ObsidianLink` produces a path relative to the workspace root, but attempts to resolve it relative to the current working directory.

### Versions

```
❯ nvim --version
NVIM v0.10.0-dev-80f75d0
Build type: Release
LuaJIT 2.1.1693350652
Run "nvim -V1 -v" for more info
```

```
❯ nvim --headless -c 'lua require("obsidian").info()' -c q
[obsidian.nvim (v2.5.3)] Commit SHA: 2d02fe914883f7de6ff4481f46b0081ccda5150b
[plenary.nvim] Commit SHA: 55d9fe89e33efd26f532ef20223e5f9430c8b0c0
[nvim-cmp] Commit SHA: 41d7633e4146dce1072de32cea31ee31b056a131
[telescope.nvim] Commit SHA: 6213322ab56eb27356fdc09a5078e41e3ea7f3bc
ripgrep 13.0.0
```

**Comment by hallettj** [comment]
This plugin is a great idea! Thanks for making it! And this bug is only a small inconvenience.

**Comment by epwalsh** [comment]
Thanks for the bug report @hallettj! #316 should fix :)
