### ISSUE TITLE
Link insertion searches wrong workspace

### ISSUE THREAD

**Issue by theherk** [epwalsh/obsidian.nvim#325]
### 🐛 Describe the bug

When I input `[` followed by characters to search to input a link, only the first workspace is searched. The workspace I'm in currently is not searched at all. However, if I use the generated "Create..." completion the note is created in the correct (current) workspace.

### Versions

```
ᐅ nvim --version
  nvim --headless -c 'lua require("obsidian").info()' -c q
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.4/share/nvim"

Run :checkhealth for more info
[obsidian.nvim (v2.6.0)] Commit SHA: bc2561cd4d8049a5c91415f15bfb5c3e68b79c48
[plenary.nvim] Commit SHA: 55d9fe89e33efd26f532ef20223e5f9430c8b0c0
[nvim-cmp] Commit SHA: 538e37ba87284942c1d76ed38dd497e54e65b891
[telescope.nvim] Commit SHA: da8b3d485975a8727bea127518b65c980521ae22
ripgrep 14.0.3⏎ 
```

**Comment by epwalsh** [comment]
Hey @theherk, can you see if #328 fixes the issue?

**Comment by theherk** [comment]
> Hey @theherk, can you see if #328 fixes the issue?

@epwalsh Yep, epwalsh/cmp-fix seems to fix the issue. Now searches the active workspace. Thank you.

**Comment by epwalsh** [comment]
Great, I'll merge and release.
