### ISSUE TITLE
`:ObsidianFollowLink` won't navigate to a note in a subfolder

### ISSUE THREAD

**Issue by nref** [epwalsh/obsidian.nvim#332]
### 🐛 Describe the bug

Maybe it's me and not the extension, but with the default configuration, `:ObsidianFollowLink` to an existing note in another folder offers to create a new note.

Repro:

Given this structure:

```
note1.md
folder/
    note2.md
```

and

```
// in note1.md
[[note2]]
```

Placing the cursor on `[[note2]]` and invoking `:ObsidianFollowLink` results in the offer `Create new note 'note2'? [Y/n]`. I expected to navigate to the existing note `folder/note2.md`

[repro.zip](https://github.com/epwalsh/obsidian.nvim/files/13966592/repro.zip)

### Versions

```powershell
PS C:\Users\doug> nvim --version
NVIM v0.9.4
Build type: RelWithDebInfo
LuaJIT 2.1.1696883897
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```
```powershell
PS C:\Users\doug> nvim --headless -c 'lua require("obsidian").info()' -c q

[obsidian.nvim (v2.6.1)] Commit SHA: a9ae6b20560d716a5f9b89252e4ea29c8e64617a
[plenary.nvim] Commit SHA: 50012918b2fc8357b87cff2a7f7f0446e47da174
[nvim-cmp] Commit SHA: 538e37ba87284942c1d76ed38dd497e54e65b891
ripgrep 14.0.3 (rev 67ad9917ad)
```

**Comment by epwalsh** [comment]
@nref thank you! I was able to repro and I'm working on a fix. In the meantime, if you were to set `notes_subdir = "folder"` in your obsidian.nvim config, that would fix the issue.

**Comment by nref** [comment]
Ok, thanks! My folder structure is too many and changing to do that systematically, but I'll keep that in mind.

**Comment by epwalsh** [comment]
UPDATE: @nref my repro was actually a false positive. It is working correctly for me. Can you post your obsidian.nvim config? Also, were there any error messages in `:messages`?

**Comment by nref** [comment]
I don't understand, but it's working now. In case something was cached I created a new repro folder with a new name. Sorry, but thanks for your time. I'll close this.
