### ISSUE TITLE
Customizable link formats

### ISSUE THREAD

**Issue by Tetra-20** [epwalsh/obsidian.nvim#334]
### 🚀 The feature, motivation and pitch

```md
1. [[A Note]] Can follow, can write
2. [[../300 Other/A Note|A Note]] Can't follow, can't write
3. [[300 Other/A Note|A Note]] Can follow, can write
4. [A Note](A%20Note.md) Can't follow, can't write
5. [A Note](../300%20Other/A%20Note.md) Can follow, can't write
6. [a Note](300 Other/A Note.md) Can follow, can write
7. [A Note](300%20Other/A%20Note.md) Can follow, can't write
8. [[300 Other/A Note]] Can follow, can write
```
It would be neat if all of these links could be followed with `:ObsidianFollowLink` and written using nvim-cmp. (especially 5 for me since it's really compatible with different apps)

### Alternatives

- Follow and/or write these links in a separate app like Obsidian.

### Additional context

- I got number 7 to be able to be written by using `:gsub("%s+", "%%20")` at the end of each line in the snippet below. (There might be a better way to do it)
https://github.com/epwalsh/obsidian.nvim/blob/bf8083fdd9745f32cf2d30e9e16285a46294fd37/lua/obsidian/client.lua#L172-L173

**Comment by epwalsh** [comment]
Hey @Tetra-20,

You should be able to follow 2 and 4 (works for me at least), otherwise we have a bug. As for writing the other forms, we could provide a callback that allows users to customize this how they want.

**Comment by Tetra-20** [comment]
Odd, link 2 prompts me to create a new file and link 4 only works if the file is in the same directory as the file with the link. I'll look more into this and might create a separate issue.

**Comment by roman1267** [comment]
Not sure if this helps, but I whipped up this little piece of black magic:
`vim.cmd("silent! %s/\\(\\(\\\\\\)\\@<!\\[.*\\(\\\\\\)\\@<!\\](.*\\)\\@<=\\s\\+\\(.*\\\\)\\)\\@!/%20/g")`
which I run as an autocommand at `BufWritePre` for markdown files. It seems to work well as a hack until this feature is implemented.

**Comment by epwalsh** [comment]
#406 will allow complete customization of the link formats.
