### ISSUE TITLE
Bold / italic text is not highlighted.

### ISSUE THREAD

**Issue by Zenith-the-realest** [epwalsh/obsidian.nvim#337]
### 🐛 Describe the bug

Bold and italic text do not render with their separate colors:
![image](https://github.com/epwalsh/obsidian.nvim/assets/75748674/e3ce81b4-7d28-410d-ae61-d96782d945cc)
![image](https://github.com/epwalsh/obsidian.nvim/assets/75748674/6b93a4c2-4fe8-4b63-91e4-fd9454621b46)

I have tried setting conceallevel to 1, 2 and 3 and it does not work.

### Versions

`nvim --version:`
```
NVIM v0.10.0-dev-2129+gba9f86a9c
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377
Run "nvim -V1 -v" for more info
```

`nvim --headless -c 'lua require("obsidian").info()' -c q:`
```
[obsidian.nvim (v2.7.0)] Commit SHA: e2d6ce7b07941b0788177e1297699ad99c1470dc
[plenary.nvim] Commit SHA: 55d9fe89e33efd26f532ef20223e5f9430c8b0c0
[nvim-cmp] Commit SHA: 538e37ba87284942c1d76ed38dd497e54e65b891
[fzf-lua] Commit SHA: 7b7e80d33468dbf98506d2ce2f185bb9dc4923f3
[fzf.vim] Commit SHA: f6cb5b17897ff0c38f60fecd4b529678bcfec259
[mini.pick] Commit SHA: 29ccad7b9facb790d016a07c88fb55da5280297b
[vim-markdown] Commit SHA: 46add6c3017d3e4035dc10ffa9cb54221d8dfe1a
ripgrep 14.1.0```

**Comment by epwalsh** [comment]
Hey @Zenith-the-realest, obsidian.nvim does not take responsibility for bold, italics, and other basic markdown syntax. I recommend using treesitter for that.

**Comment by Zenith-the-realest** [comment]
I have nvim-treesitter, but the bold and italic text does not register
