### ISSUE TITLE
Telescope picker for links

### ISSUE THREAD

**Issue by Liquidmantis** [epwalsh/obsidian.nvim#343]
### 🚀 The feature, motivation and pitch

I'm hoping I just haven't been able to find the documentation, but it would be great if there was a Telescope picker for markdown links in a buffer.  Having to move to a link to open it is slow in comparison.

**Comment by epwalsh** [comment]
@Liquidmantis that's an interesting idea! Would def be a nice feature, and not too hard to implement. I think we have most of the pieces implemented already, like a function for finding all references in a string of text.

**Comment by Liquidmantis** [comment]
I haven't had much time but was starting to poke around to understand how it would be implemented to see if I could take a stab at it.  I was thinking Treesitter would make it reasonably straightforward.  

I currently use [urlview](https://github.com/axieax/urlview.nvim), but it doesn't support markdown links.  Here's an example of the experience with it, though.
![CleanShot 2024-01-29 at 12 53 52@2x](https://github.com/epwalsh/obsidian.nvim/assets/399056/f5cf1122-f05f-47a9-9c6f-95fbbdb26469)

**Comment by sotte** [comment]
I was just thinking about a "goto next link" and "goto previous link" mapping. A different way of solving a very similar issue.

Currently treesitter offers nodes for `inline_links`. Raw urls are not covered.

Here is an example:

![image](https://github.com/epwalsh/obsidian.nvim/assets/79138/e53fb1b6-7b48-4dac-8c3c-368c187dfbbe)

Building something like a telescope picker for this should be reasonable straight forward.

**Comment by Liquidmantis** [comment]
@epwalsh This is perfect!  Thanks!  Sorry I didn't contribute more.

**Comment by sotte** [comment]
This is a great little feature.
