### ISSUE TITLE
Treesitter not highlighting markdown files

### ISSUE THREAD

**Issue by rafaeljacov** [epwalsh/obsidian.nvim#350]
### 🐛 Describe the bug

Just installed the plugin using defaults but for some reason Treesitter doesn't work with my markdown.
I have markdown and markdown_inline installed
![image](https://github.com/epwalsh/obsidian.nvim/assets/110229646/c481c2d3-833b-4523-9c75-8741e193ba42)

Here's my config:
```lua
    {
        "epwalsh/obsidian.nvim",
        version = "*",  -- recommended, use latest release instead of latest commit
        lazy = true,
        ft = "markdown",
        -- Replace the above line with this if you only want to load obsidian.nvim for markdown files in your vault:
        -- event = {
            --   -- If you want to use the home shortcut '~' here you need to call 'vim.fn.expand'.
            --   -- E.g. "BufReadPre " .. vim.fn.expand "~" .. "/my-vault/**.md"
            --   "BufReadPre path/to/my-vault/**.md",
            --   "BufNewFile path/to/my-vault/**.md",
            -- },
            opts = {
                workspaces = {
                    {
                        name = "notes",
                        path = "~/WorkSpace/notes/",
                    },
                },

                -- see below for full list of options 👇
            },
        },
```

### Versions

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

[obsidian.nvim (v2.7.1)] Commit SHA: f604a30f74617850ca91a85fd35118ad6325bd5e
[plenary.nvim] Commit SHA: 663246936325062427597964d81d30eaa42ab1e4
[nvim-cmp] Commit SHA: 538e37ba87284942c1d76ed38dd497e54e65b891
[telescope.nvim] Commit SHA: d90956833d7c27e73c621a61f20b29fdb7122709
ripgrep 14.1.0%

**Comment by GusJelly** [comment]
Can you show your Treesitter configuration? There might be a weird conflict between settings
