### ISSUE TITLE
Todo list conceal

### ISSUE THREAD

**Issue by Isos9** [epwalsh/obsidian.nvim#357]
### 🐛 Describe the bug

Hi, this may not be an issue from obsidian itself, but I don't know where to look to resolve it.

Right now a checked item in a to-do list does not render as expected, any idea how? 
![image](https://github.com/epwalsh/obsidian.nvim/assets/16087932/0c1c61ef-6c24-470e-97f6-4faaa7039205)

I'm using Alacritty on Arch Linux with Jetbrain mono nerd font. conceallevel is at 2.

Thanks

### Versions

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
  
  
 [obsidian.nvim (v2.8.0)] Commit SHA: b101ad8988eb1452dabb6138763877a1794a1966
[plenary.nvim] Commit SHA: 253d34830709d690f013daf2853a9d21ad7accab
[nvim-cmp] Commit SHA: d3a2833c118843859c667f64b6169e22bffe13d0
[telescope.nvim] Commit SHA: 4522d7e3ea75ffddabdc39957168a8a7060b5df0
ripgrep 13.0.0%

**Comment by epwalsh** [comment]
Hey @Isos9 is that an upper case "X" in the box?

**Comment by Isos9** [comment]
Yes, it is.
My bad, I got it mixed with taskwiki functions, I used my usual keymap to toggle the checkbox.
Thanks

**Comment by epwalsh** [comment]
For future reference, if anyone requires using an uppercase "X" for some reason, you can just add this line to the `ui.checkboxes` part of your config:

```lua
          ["X"] = { char = "", hl_group = "ObsidianDone" },
```
