### ISSUE TITLE
Enhanced Tag Management

### ISSUE THREAD

**Issue by panosz** [epwalsh/obsidian.nvim#359]
### 🚀 The feature, motivation and pitch

While authoring new notes, determining the most appropriate tags can be challenging, particularly when the potential for duplicating existing tags exists. Current autocompletion features, although valuable, offer limited assistance, as they primarily facilitate the discovery of tags starting with similar prefixes. This limitation makes it difficult to efficiently organize and categorize notes, especially when similar but not identical tags (e.g., `my_allergies` vs. `allergies`) are in use.

## Proposed Solution
Implement an enhanced tag management feature that provides a comprehensive overview of all existing tags within the current workspace. This feature should enable users to:

1. **View a List of All Tags**: Offer an easily accessible interface that displays all tags currently in use, potentially leveraging fuzzy search to help find similar tags even if they don't share the same prefix.
2. **Tag Selection and Application**: Allow users to select multiple tags from this overview and apply them directly to the current note. This could streamline the process of tagging, ensuring consistency and preventing the proliferation of nearly duplicate tags.

## Implementation Consideration
I guess using a custom telescope picker would be an ideal approach for this feature, given its powerful search and UI capabilities such as listing tags, fuzzy searching, and multi-selection support. However, I am not sure how to actually build it.

**Comment by epwalsh** [comment]
Agreed @panosz, there's a lot we could improve here. A good first step would be to build on `Client:find_tags()` to allow an "empty" search, which would return ALL tags in the vault. I'll work on that soon.

**Comment by epwalsh** [comment]
As of a6596be, tag completion is now fuzzier. For example:

![image](https://github.com/epwalsh/obsidian.nvim/assets/8812459/048f14bc-190b-4cff-a373-d51607f8d1c7)

**Comment by epwalsh** [comment]
One more easy-ish improvement we could make would be to open up a finder with a list of ALL tags when no argument is provided to `:ObsidianTags`.

**Comment by panosz** [comment]
> One more easy-ish improvement we could make would be to open up a finder with a list of ALL tags when no argument is provided to `:ObsidianTags`.

I agree. Another plus is that this implements what one would intuitively expect from the command. I was actually surprised when I first tried `:ObsidianTags` (without having read the documentation) and discovered that it didn't list all tags.
