### ISSUE TITLE
Enhance toggle_checkbox function to also convert non-checkbox lines into checkboxes

### ISSUE THREAD

**Issue by anggerdeni** [epwalsh/obsidian.nvim#361]
### 🚀 The feature, motivation and pitch

I am new to this plugin and I think this is an awesome project. But I came across an unexpected behavior when setting it up. Following the keymap recommendation, I set `<leader>ch` to toggle checkboxes. My expectation is as follow:

1. It will toggle between checked/unchecked for an existing checkbox [it works fine]
2. It will convert a line which is not a checkbox into a checkbox [nothing happens]

Will it be a good idea to implement the second scenario?

### Alternatives

`toggle_checkbox` should automatically insert `- [ ]` to beginning of the line. Currently I'm using the following code to achieve it
```lua
    ["<leader>ch"] = {
      action = function()
        local line_num = unpack(vim.api.nvim_win_get_cursor(0)) -- 1-indexed
        local line = vim.api.nvim_get_current_line()
        print(line)
        if not string.match(line, "^%s*- %[[ x~>-]%].*") then
          line = "- [ ]" .. line
          vim.api.nvim_buf_set_lines(0, line_num - 1, line_num, true, { line })
          return
        end

        return obsidian.util.toggle_checkbox()
      end,
      opts = { buffer = true },
    },
```

**Comment by epwalsh** [comment]
@anggerdeni yes this would be good to have. Would you like to make a PR?

**Comment by anggerdeni** [comment]
@epwalsh sure, I've created the PR here https://github.com/epwalsh/obsidian.nvim/pull/363
