### ISSUE TITLE
Stop taking the first heading as an alias.

### ISSUE THREAD

**Issue by alexandre-dos-reis** [epwalsh/obsidian.nvim#371]
### 🚀 The feature, motivation and pitch

Hi, again thank you for your work.

it is possible to stop taking the first heading as an alias ?

I keep a `title` key in the frontmatter so this is useless for me. Thanks

**Comment by pranavTripathi02** [comment]
Hi @alexandre-dos-reis 
I wanted a similar feature and these changes to the config seem to work for me.
We check if the tags and aliases have any values and if not, they are not automatically added.

```
note_frontmatter_func = function(note)

	local out = { }

	if #note.tags > 0 then
		out.tags = note.tags
	end
	if #note.aliases > 0 then
		out["aliases"] = note.aliases
	end

	if note.metadata ~= nil and not vim.tbl_isempty(note.metadata) then
		for k, v in pairs(note.metadata) do
			out[k] = v
		end
	end
	return out
end,


```

**Comment by alexandre-dos-reis** [comment]
@pranavTripathi02 Thank you for your help. Unfortunately, this doesn't solve my problem. The first header keeps coming back to aliases.

**Comment by pranavTripathi02** [comment]
Let me know if this is what you're looking for

from https://github.com/epwalsh/obsidian.nvim#configuration-options
```
-- Optional, boolean or a function that takes a filename and returns a boolean.
  -- `true` indicates that you don't want obsidian.nvim to manage frontmatter.
  disable_frontmatter = false,
```

**Comment by epwalsh** [comment]
As of #375, `note` objects now have a `title` field (taken from the first heading), so you could remove `note.title` from `note.aliases` in your `note_frontmatter_func`.

**Comment by aarnphm** [comment]
If I remove `note.aliases`, it will also clean up the aliases within the frontmatter, so essentially, this `frontmatter_func` is barely usable.

**Comment by epwalsh** [comment]
The default behavior now does _not_ add the title as an alias automatically. If you still want the old behavior, use the `note_frontmatter_func` example in the README:

```lua
  note_frontmatter_func = function(note)
    -- Add the title of the note as an alias.
    if note.title then
      note:add_alias(note.title)
    end

    local out = { id = note.id, aliases = note.aliases, tags = note.tags }

    -- `note.metadata` contains any manually added fields in the frontmatter.
    -- So here we just make sure those fields are kept in the frontmatter.
    if note.metadata ~= nil and not vim.tbl_isempty(note.metadata) then
      for k, v in pairs(note.metadata) do
        out[k] = v
      end
    end

    return out
  end
```

**Comment by aarnphm** [comment]
This is not an issue. The problem here is that if I have existing aliases, `note.aliases` will include all my aliases + the headings, which is not expected, and I don't think that is correct.
