### ISSUE TITLE
Autocompletion does not work

### ISSUE THREAD

**Issue by jclmntn** [epwalsh/obsidian.nvim#373]
### 🐛 Describe the bug

I'm trying to use obsidian.nvim, but I noticed the completion when pressing [[ is not working in my setup. These are my configurations for the lsp, the cmp and obsidian.nvim. Perhaps I'm missing something else:

```
    {
        "neovim/nvim-lspconfig",
        dependencies={
            "williamboman/mason.nvim",
            "williamboman/mason-lspconfig.nvim",
            "hrsh7th/cmp-nvim-lsp",
            "hrsh7th/cmp-buffer",
            "hrsh7th/cmp-path",
            "hrsh7th/cmp-cmdline",
            "hrsh7th/nvim-cmp",
            "L3MON4D3/LuaSnip",
            "saadparwaiz1/cmp_luasnip"
        },
        config = function()
            require("mason").setup()
            require("mason-lspconfig").setup({
                ensure_installed = { 'pyright', 'pyflakes', 'lua_ls', 'clangd', 'clojure-lsp' },
                handlers = {
                    function(server_name)
                        require("lspconfig")[server_name].setup {}
                    end,
                    ["lua_ls"] = function ()
                        local lspconfig = require("lspconfig")
                        lspconfig.lua_ls.setup {
                            settings = {
                                Lua = {
                                    diagnostics = {
                                        globals = { "vim" }
                                    }
                                }
                            }
                        }
                    end

                }
            })

            local cmp = require('cmp')
            cmp.setup({
                snippet = {
                    expand = function(args)
                        require('luasnip').lsp_expand(args.body)
                    end
                },
                mapping = cmp.mapping.preset.insert({
                    ['<C-p>'] = cmp.mapping.select_prev_item(cmp_select),
                    ['<C-n>'] = cmp.mapping.select_next_item(cmp_select),
                    ['<C-y>'] = cmp.mapping.confirm({ select = true }),
                    ['<C-Space>'] = cmp.mapping.complete()
                }),
                sources = cmp.config.sources({
                    { name = 'nvim_lsp' },
                    { name = 'luasnip' }
                }, {
                        { name = 'buffer' }
                    })
            })
        end
    },
    {
        "epwalsh/obsidian.nvim",
        version = "*",  -- recommended, use latest release instead of latest commit
        lazy = true,
        ft = "markdown",
        -- Replace the above line with this if you only want to load obsidian.nvim for markdown files in your vault:
        -- event = {
        --   -- If you want to use the home shortcut '~' here you need to call 'vim.fn.expand'.
        --   -- E.g. "BufReadPre " .. vim.fn.expand "~" .. "/my-vault/**.md"
        --   "BufReadPre path/to/my-vault/**.md",
        --   "BufNewFile path/to/my-vault/**.md",
        -- },
        dependencies = {
            -- Required.
            "nvim-lua/plenary.nvim",

            -- see below for full list of optional dependencies 👇
        },
        opts = {
            workspaces = {
                {
                    name = "VaultTeste",
                    path = "~/vaults/VaultTeste/",
                },
            },
            completion = { nvim_cmp = true }
            -- see below for full list of options 👇
        },
    }

```

### Versions

`nvim --version`
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

            
`nvim --headless -c 'lua require("obsidian").info()' -c q`            
hello
[obsidian.nvim (v2.9.0)] Commit SHA: 8b10f0c377ee6f8f45aaeb59a6eb8a8ce28c5a43
[plenary.nvim] Commit SHA: 4f71c0c4a196ceb656c824a70792f3df3ce6bb6d
[nvim-cmp] Commit SHA: 04e0ca376d6abdbfc8b52180f8ea236cbfddf782
ripgrep 13.0.0 (rev af6b6c543b)

**Comment by epwalsh** [comment]
Hey @jclmntn any errors in `:messages`?

The next thing to check is if `obsidian` has been registered as a source. Can you post the output running this from a markdown file within your vault:

```vim
:lua vim.print(require("cmp").get_config().sources)
```

**Comment by jclmntn** [comment]
Hey @epwalsh, thanks for the answer.
Regarding the results in `:messages`: there are no errors.

In fact, it seems that obsidian hasn't been registered as a source:

{ {
    group_index = 1,
    name = "nvim_lsp",
    option = {}
  }, {
    group_index = 1,
    name = "luasnip",
    option = {}
  }, {
    group_index = 2,
    name = "buffer",
    option = {}
  } }
  
This is my first week using nvim and lua, but something tells me the problem might be related to the scope in which cmp setup is being defined. I'll tinker a bit more to see if I can make it work, but if you have any other ideas, please do tell me.

**Comment by epwalsh** [comment]
Hmm okay 🤔 Keep in mind Obsidian.nvim only registers its `cmp` sources for markdown buffers within a workspace. So based on the config you posted that would be any `.md` file within `"~/vaults/VaultTeste/"`.

**Comment by 777uliahshafar** [comment]
Why does type [[ in normal mode cause vim motion that is scroll up to previous header. But when I check the `:nmap [[` it said call search. Any ideas? Thank you

**Comment by jclmntn** [comment]
After restructuring my lazy configuration with many files instead of using a monolith, obsidian.nvim started to work as intended!
Should I close this issue?

**Comment by epwalsh** [comment]
Good to hear! Yea let's close. We can reopen if you run into an issue again.

**Comment by jclmntn** [comment]
Quick question regarding the autocompletion: I've noticed that it works for every file inside the vault root path, but not on files that are in the vault's subdirectories. Is this a bug or an expected behavior? Is there anyway to make it work in both cases?

**Comment by epwalsh** [comment]
Hey @jclmntn it's definitely _supposed_ to work everywhere within the vault. Can you give me some steps to reproduce?

**Comment by epwalsh** [comment]
Usually completion not working is a sign that obsidian.nvim does not think the current buffer is a markdown file within your vault. There were some issues with symlinks before which I think have all been resolved on `main` now.

**Comment by jclmntn** [comment]
Just in case, I'm already using the most up to date commit. So this is my setup:

```
return {
    "epwalsh/obsidian.nvim",
    version = "*",  -- recommended, use latest release instead of latest commit
    --lazy = true,
    ft = "markdown",
    -- Replace the above line with this if you only want to load obsidian.nvim for markdown files in your vault:
    -- event = {
    --   -- If you want to use the home shortcut '~' here you need to call 'vim.fn.expand'.
    --   -- E.g. "BufReadPre " .. vim.fn.expand "~" .. "/my-vault/**.md"
    --   "BufReadPre path/to/my-vault/**.md",
    --   "BufNewFile path/to/my-vault/**.md",
    -- },
    dependencies = {
        -- Required.
        "nvim-lua/plenary.nvim",
    },
    opts = {
        workspaces = {
            {
                name = "Base de Conhecimento",
                path = "~/vaults/Base de Conhecimento",
            }
        },
        daily_notes = {
            folder = "Daily"
        }
    },
}
```

This gif shows how it works as intended in a file that is within the vault root path:
![vault_root_path](https://github.com/epwalsh/obsidian.nvim/assets/21028099/9b6ae72d-dd5f-4b01-947b-718dd975c0f7)

This second gif shows how it does not work in a file that is within a subdirectory:
![subdirectory](https://github.com/epwalsh/obsidian.nvim/assets/21028099/f14c3c8f-4edb-4341-a394-c3fcac123e6f)

I've noticed that obsidian is not listed as a source on files that are withing a subdirectory. I think you are spot on regarding the file not being recognized as `.md`. Is there anything else that I should try?

**Comment by epwalsh** [comment]
@jclmntn can you run this from the note where autocomplete does NOT work and tell me the output:

```vim
:lua vim.print(require("obsidian.workspace").get_workspace_for_dir(vim.fs.dirname(vim.api.nvim_buf_get_name(0)), require("obsidian").get_client().opts.workspaces))
```

**Comment by epwalsh** [comment]
And also:

```vim
:lua vim.print(require("obsidian.workspace").get_workspace_for_dir(require("obsidian").get_client().buf_dir, require("obsidian").get_client().opts.workspaces))
```

**Comment by jclmntn** [comment]
Nothing happens: no messages, no errors. 🤔

**Comment by epwalsh** [comment]
Huh.. okay I just made a new command `:ObsidianDebug`, which will give me some more info to go off of. Can you pull the latest commit and then run that command?

**Comment by jclmntn** [comment]
Sure thing!
This is what I got after running `:ObsidianDebug` from inside the file where autocomplete does not work:

```
Current buffer directory: 'C:/Users/jclmntn/vaults/Base de Conhecimento/Daily'
Workspaces:
  No active workspaces
  Inactive workspace: Workspace(name='Base de Conhecimento', path='C:/Users/jclmntn/vaults/Base de Conhecimento', root='C:/Users/jclmntn/vaults/Base de Conhecimento')
```

If I run it from inside a file where autocomplete is working:

```
Current buffer directory: 'C:/Users/jclmntn/vaults/Base de Conhecimento'
Workspaces:
  Active workspace: Workspace(name='Base de Conhecimento', path='C:/Users/jclmntn/vaults/Base de Conhecimento', root='C:/Users/jclmntn/vaults/Base de Conhecimento')
```

**Comment by epwalsh** [comment]
Ah, okay I think we're getting somewhere. I'm guessing this is a windows bug with `plenary.path`. Let's try to confirm. Can you put this code into a file `tmp.lua` and then from the markdown buffer run `:luafile tmp.lua`.

```lua
-- tmp.lua
local Path = require "plenary.path"

local cur_dir = Path:new "C:/Users/jclmntn/vaults/Base de Conhecimento/Daily"
local dirs = cur_dir:parents()
table.insert(dirs, 1, tostring(cur_dir))

for _, dir in ipairs(dirs) do
  print(dir)
end
```

**Comment by jclmntn** [comment]
Awesome! These are the results:

```
C:/Users/jclmntn/vaults/Base de Conhecimento/Daily
C:\Users\jclmntn\vaults\Base de Conhecimento
C:\Users\jclmntn\vaults
C:\Users\jclmntn
C:\Users
C:\
C:\
```

**Comment by epwalsh** [comment]
Ok definitely a plenary path bug! I have a potential fix here: https://github.com/epwalsh/obsidian.nvim/pull/400

Can you try on that branch?

**Comment by jclmntn** [comment]
Looks like it's fixed! Thanks a bunch!
