### ISSUE TITLE
Configurable backlinks view - telescope picker and/or vsplit

### ISSUE THREAD

**Issue by sotte** [epwalsh/obsidian.nvim#374]
### 🚀 The feature, motivation and pitch

It would be great to have more configuration options for the backlink view. I often have many backlinks. The current implementation always opens the backlink view in a quickfix like view at the bottom and only the height is configurable.

It would be great,

a) if the view would be more configurable: use vsplit, tab, ...
b) or if the backlinks could be piped to telescope to that I can easily search and go to the notes with telescope.

(I guess a similar feature would be useful for tags as well: show all files with a given tag in telescope.)

**Comment by sotte** [comment]
For a) one would have to make the `botright` and `split` from [here](https://github.com/epwalsh/obsidian.nvim/blob/d1c816206600dab89c73d14c1e95e8ef2783de28/lua/obsidian/location_list.lua#L142)  configurable.

From the user's perspective it cold look something like this:

```lua
backlinks = {
  view_strategy = "vsplit",  -- vsplit|split|tabnew
  ...
}
```

**Comment by epwalsh** [comment]
> a) if the view would be more configurable: use vsplit, tab, ...

This is easy enough to support. I'd be happy to review a PR with your suggestion.

> b) or if the backlinks could be piped to telescope to that I can easily search and go to the notes with telescope.

The Lua API for gathering backlinks is close to being stable. Once it's stable it would be easy enough for users to pipe that into telescope. And that would be a great example to add to the [cookbook](https://github.com/epwalsh/obsidian.nvim/discussions/categories/cookbook).

**Comment by sotte** [comment]
> This is easy enough to support. I'd be happy to review a PR with your suggestion.

I'm not sure if I have the time right now to implement this. So, anybody, feel free grab this one :+1: 

I also might wait for the stable API and then use telescope directly.

**Comment by epwalsh** [comment]
Sounds good... there's not too much left to do to stabilize the API, I just want to move the functionality into a `Client` method (it's currently in its own module).

If you don't hear back from me about this within a week or two feel free to ping me.

**Comment by epwalsh** [comment]
Ok, it's now pretty straightforward to create your own command for this. Here's a snippet:


```lua
---@type obsidian.Client
local client = require("obsidian").get_client()

local note = assert(client:resolve_note "OLMo research hub") -- replace with name or ID of your note

client:find_backlinks_async(note, true, function(backlinks)
  local items = {}
  for _, matches in ipairs(backlinks) do
    local path = client:vault_relative_path(matches.path)
    for _, match in ipairs(matches.matches) do
      items[#items + 1] = {
        value = { path = path, line = match.line },
        display = string.format("%s:%s:%s", path, match.line, match.text),
        ordinal = match.text,
        filename = matches.path,
        lnum = match.line,
      }
    end
  end

  local picker = assert(client:picker())
  picker:pick(items, {
    prompt_title = "Backlinks",
    callback = function(value)
      vim.cmd(string.format("e %s", value.path))
      vim.api.nvim_win_set_cursor(0, { tonumber(value.line), 0 })
    end,
  })
end)
```

I like this a lot, actually, so eventually I'm going to build this in as a configurable "view" for backlinks.

**Comment by sotte** [comment]
Thank so much @epwalsh. This is great!

**Comment by lethc** [comment]
@epwalsh At first, I thought this hadn't been solved yet, but then I realized that it works if you use Telescope. Is it possible that it also works if you use fzf-lua?
