### ISSUE TITLE
bug: Links within notematter is parsed incorrectly.

### ISSUE THREAD

**Issue by aarnphm** [epwalsh/obsidian.nvim#380]
### 🐛 Describe the bug

If frontmatter contains a links within the vault, the regex frontmatter won't be reserved when saving with `obsidian.nvim`:

<img width="259" alt="Screenshot 2024-02-09 at 03 04 26" src="https://github.com/epwalsh/obsidian.nvim/assets/29749331/c8db4b15-9908-4b2b-a80d-78b749eb417d">

It will then be converted to 
<img width="272" alt="Screenshot 2024-02-09 at 03 05 14" src="https://github.com/epwalsh/obsidian.nvim/assets/29749331/66a2c5b7-1e0f-4f98-a945-fe710b65dd7c">

which is incorrect.

### Versions

```prolog
NVIM v0.10.0-dev-4e59422
Build type: Release
LuaJIT 2.1.1693350652
Run "nvim -V1 -v" for more info
```

```prolog
[obsidian.nvim (v2.10.0)] Commit SHA: 6b9f27f0c1758863b6eaaffe7614c7bc6ec54675
[plenary.nvim] Commit SHA: 4f71c0c4a196ceb656c824a70792f3df3ce6bb6d
[nvim-cmp] Commit SHA: 04e0ca376d6abdbfc8b52180f8ea236cbfddf782
ripgrep 13.0.0 (rev af6b6c543b)
```

**Comment by aarnphm** [comment]
Hmm sorry for this, oversight on my end. This is also invalid frontmatter.

**Comment by aarnphm** [comment]
Actually if the front matter is

```prolog
---
test: [[quotes]]
```

the problem still persists.

**Comment by epwalsh** [comment]
@aarnphm in YAML `[ ... ]` indicates an inline list. If you surround that in quotes it will work as expected:

```yaml
test: "[[quotes]]"
```

**Comment by aarnphm** [comment]
got it. This is a usage issue, not a bug.
