### ISSUE TITLE
Links to new notes from Daily notes aren't being created in the correct directory

### ISSUE THREAD

**Issue by jakelucasnyc** [epwalsh/obsidian.nvim#383]
### 🐛 Describe the bug

In one of my daily notes, I create a wiki link to a file that doesn't exist yet. I then put my cursor over the wiki link and use the "gf" shortcut. I'm prompted if I want to create the file. I type "y" and Enter. Depending on how I create the wiki link, after confirming I want to create the file, I either receive an error, or the file is created in the wrong location.

I'm running this plugin on WSL (Ubuntu 20.04)

I'm using lazy.nvim to load this plugin. Here is where I download the plugin through lazy.nvim:
Path: `$XDG_CONFIG_HOME/nvim/lua/jpl/lazy.lua` (inside `require("lazy").setup({})`)
![image](https://github.com/epwalsh/obsidian.nvim/assets/70170165/af8cb343-a6f8-4155-953c-a6e4f2f796ac)

Here is where I configure the plugin:
Path: `$XDG_CONFIG_HOME/nvim/after/plugin/obsidian.lua`
![image](https://github.com/epwalsh/obsidian.nvim/assets/70170165/93773b53-e6ae-4274-823c-e9901f689f8c)
Note the values of notes_subdir, new_notes_location, and daily_notes.folder

This is where I encounter the first case of the bug:
![image](https://github.com/epwalsh/obsidian.nvim/assets/70170165/dda4717d-fcae-4599-aefd-0a31172cc8fe)

Following the above wiki link results in the following error:
![image](https://github.com/epwalsh/obsidian.nvim/assets/70170165/2379966e-65af-4dd1-81eb-b6089ea61f99)
Note: What seems to have happened here is that, when I attempted to create the new note, obsidian.nvim attempted to create the file in a path like this: `VaultPath/DailyNotesFolder/DefaultNotesSubdir/NewNote.md`. I would've expected for the new note to be created in a path like this: `VaultPath/DefaultNotesSubdir/NewNote.md`

This is where I encounter the second case of the bug:
![image](https://github.com/epwalsh/obsidian.nvim/assets/70170165/50739453-11e7-4f86-a9d5-ccde61cfc379)

This case does not result in an error, but the new note is created in a path like: `VaultPath/DailyNotesFolder/NewNote.md`. I would've expected the note to be created in a path like this: `VaultPath/DefaultNotesSubdir/NewNote.md`

### Versions

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

[obsidian.nvim (v2.10.0)] Commit SHA: 32de09d0c737d314ff629068902c4657c244d55b
[plenary.nvim] Commit SHA: 4f71c0c4a196ceb656c824a70792f3df3ce6bb6d
[nvim-cmp] Commit SHA: 04e0ca376d6abdbfc8b52180f8ea236cbfddf782
[telescope.nvim] Commit SHA: 0f865f17af4f9bc1587a0132414cdfd32d91852e
ripgrep 11.0.2

**Comment by epwalsh** [comment]
@jakelucasnyc I've believe I've fixed both of these issues in #384.

Note that when using the autocomplete option to create a new note you should hit ENTER on the option, which will trigger the note to be created immediately.

**Comment by jakelucasnyc** [comment]
@epwalsh I updated to this commit and both cases work as expected, thanks so much for your help! 

For clarification, whenever the autocomplete comes up and I navigate to the option I want with <C-n> or <C-p>, if I press Enter, I end up performing a carriage return in the buffer, moving the closing brackets of the wiki link to the next line. I'm still in insert mode when pressing Enter, which may be a problem, but going out of insert mode takes away the autocompletion options, so I'm not sure what else to try. Nevertheless, the original way I was creating these new notes works like a charm now. so I'm fine with sticking to that method.

**Comment by epwalsh** [comment]
@jakelucasnyc sounds like an issue with your `cmp` mappings? You may need this:

https://github.com/epwalsh/dotfiles/blob/0bbc7bb130c1a2c64a6f05f3b6f85c2b334affcf/neovim/lua/plugins/completion.lua#L77-L79
