### ISSUE TITLE
Undo history contains empty change when no change to frontmatter

### ISSUE THREAD

**Issue by ianhomer** [epwalsh/obsidian.nvim#386]
### 🐛 Describe the bug

With frontmatter enabled `disable_frontmatter = false,`

1. make a simple change to markdown file
2. press `u` to try to undo the change
3. change made is not undone
4. press `u` to try to undo the change
5. change made is not undone
6. press `u` twice quickly (i.e. quicker than the frontmatter update takes)
7. change made is undone

Looking at the undo tree (e.g. with https://github.com/simnalamburt/vim-mundo) you can see there is an empty change in the undo history.

### Versions

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info

[obsidian.nvim (v2.10.0)] Commit SHA: 32de09d0c737d314ff629068902c4657c244d55b
[plenary.nvim] Commit SHA: 4f71c0c4a196ceb656c824a70792f3df3ce6bb6d
[nvim-cmp] Commit SHA: 04e0ca376d6abdbfc8b52180f8ea236cbfddf782
[telescope.nvim] Commit SHA: 0f865f17af4f9bc1587a0132414cdfd32d91852e
ripgrep 14.1.0⏎

**Comment by epwalsh** [comment]
Hey @ianhomer, fixed in https://github.com/epwalsh/obsidian.nvim/commit/261e9456843be38fdc7b9d1be9d4a67d49345449.

**Comment by ianhomer** [comment]
Thank you @epwalsh - fix works well for me.
