### ISSUE TITLE
Autocompletion not working on vault

### ISSUE THREAD

**Issue by Jlchong3** [epwalsh/obsidian.nvim#388]
### 🐛 Describe the bug

# Issue
nvim-cmp is not detecting obsidian as a source on the vault, and the mappings also stopped working and I don't know why.
I tried reinstalling the plugin several times, but the problem still persists.

### No completion for links
![image](https://github.com/epwalsh/obsidian.nvim/assets/127264125/26079450-f5e2-406a-9cb3-979c2c345574)

### No option for default mapping (leader ch)
![image](https://github.com/epwalsh/obsidian.nvim/assets/127264125/361b03dd-fa21-4cac-83ad-fd2df6f2fc4c)

### My config
```
{
        "epwalsh/obsidian.nvim",
        version = "*",
        lazy = true,
        ft = "markdown",
        dependencies = {
            "nvim-lua/plenary.nvim",
        },
        opts = {
            workspaces = {
                {
                    name = "notes",
                    path = "~/OneDrive/Documentos/Obsidian Notes",
                },
            },

            templates = {
                subdir = "Templates"
            }
        },
    }
```

If someone could help me with this issue I would appreciate it

## nvim --version
NVIM v0.9.4
Build type: RelWithDebInfo
LuaJIT 2.1.1696883897
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

## nvim --headless -c 'lua require("obsidian").info()' - c q
[obsidian.nvim (v3.0.0)] Commit SHA: 387f5cf90718b729e1e855e66dd272039395a6dc
[plenary.nvim] Commit SHA: 4f71c0c4a196ceb656c824a70792f3df3ce6bb6d
[nvim-cmp] Commit SHA: 04e0ca376d6abdbfc8b52180f8ea236cbfddf782
[telescope.nvim] Commit SHA: d90956833d7c27e73c621a61f20b29fdb7122709
ripgrep 14.1.0 (rev e50df40a19)

**Comment by epwalsh** [comment]
Hey @Jlchong3 where is the file located that you were editing? Inside your vault?

You could try downgrading obsidian.nvim. Maybe a recent change to the workspaces API broke something for you.

**Comment by Jlchong3** [comment]
Yes, the file is in my my vault
I tried downgrading obsidian.nvim to v2.9.0, but the problem still remains
## Version
>[obsidian.nvim (v2.9.0)] Commit SHA: 8b10f0c377ee6f8f45aaeb59a6eb8a8ce28c5a43
[plenary.nvim] Commit SHA: 4f71c0c4a196ceb656c824a70792f3df3ce6bb6d
[nvim-cmp] Commit SHA: 04e0ca376d6abdbfc8b52180f8ea236cbfddf782
[telescope.nvim] Commit SHA: d90956833d7c27e73c621a61f20b29fdb7122709
ripgrep 14.1.0 (rev e50df40a19)

## Problems
when I run CmpStatus I get this
```
# ready source names
- luasnip
- nvim_lsp:marksman

# unused source names
- obsidian
- obsidian_new
- obsidian_tagsk
```

I could manually make the cmp use those as sources, but I can't do anything about the mappings
```
require("obsidian").setup({
    workspaces = {
        {
            name = "notes",
            path = "~/OneDrive/Documentos/Obsidian Notes",
        },
    },
    mappings = {
        ["gf"] = {
            action = function()
                return require("obsidian").util.gf_passthrough()
            end,
            opts = { noremap = false, expr = true, buffer = true },
        },
        ["<leader>ch"] = {
            action = function()
                return require("obsidian").util.toggle_checkbox()
            end,
            opts = { buffer = true },
        },
    },
    templates = {
        subdir = "Templates"
    },
})
```
I separated the the configuration of the plugin in another file to explicitly set the mappings in the setup, but it still isn't working. Neither of the mappings can be used when editing a file in my vault; commands like ObsidianFollowLink still work without a problem though.

**Comment by epwalsh** [comment]
Is your vault behind a symlink?

**Comment by nelsonfrz** [comment]
I am encountering the same problem with the latest and older releases.

**Comment by epwalsh** [comment]
Can either of you pinpoint which release was the latest working one?

**Comment by hatunike** [comment]
I'm pretty new to Obsidian neovim as of about 2 weeks. It was working up until a few days ago for me. I thought it was just something I had done. Other commands appear to be working. For example, I can follow links, and I can use the "Today" command.

**Comment by hatunike** [comment]
"gf" command doesn't work, but ObsidianFollowLink does.

**Comment by epwalsh** [comment]
Okay, so the fact that commands work, yet mappings and completion don't mean that obsidian.nvim does not think the current markdown file is inside one of your workspaces / vaults. Can you run this for me (from a markdown file) and paste the output:

```lua
:lua vim.print(require("obsidian.workspace").get_workspace_for_dir(vim.fs.dirname(vim.api.nvim_buf_get_name(0)), require("obsidian").get_client().opts.workspaces))
```

**Comment by epwalsh** [comment]
I'm guessing you have you vault behind a symlink? If that's the case, try setting the `path` in your workspace config to the resolved path (what the symlink is pointing to).

**Comment by epwalsh** [comment]
I think I found the issue. Can you all confirm #390 fixes this?

**Comment by hatunike** [comment]
```
:lua vim.print(require("obsidian.workspace").get_workspace_for_dir(vim.fs.dirname(vim.api.nvim_buf_get_name(0)), require("obsidian").get_client().opts.workspaces))
```

Leads to : 

```
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'get_workspace_for_dir' (a nil value)
stack traceback:
	[string ":lua"]:1: in main chunk
```
I did update to the that commit - and after I switched my path of my vault from being an environment variable : 

path = os.getenv("Obsidian"),

to instead being the path - then everything worked.

But even with the latest commit, using the environment variable didn't work.
