### ISSUE TITLE
Changing colors of elements or tags (like in obsidian)

### ISSUE THREAD

**Issue by BigLadDylan** [epwalsh/obsidian.nvim#392]
### Discussed in https://github.com/epwalsh/obsidian.nvim/discussions/391

<div type='discussions-op-text'>

<sup>Originally posted by **BigLadDylan** February 12, 2024</sup>
Hello, can somebody tell me where i can change (or override) colors of certain tags like headings bullet points etc.

 (both fg and bg) Ideally without editing my theme config. Is it handled by Tree sitter? idk 

This is my current theme: https://github.com/navarasu/onedark.nvim
Here is what my current theme is set to:
```lua
darker = {
		black = "#0e1013",
		bg0 = "#1f2329",
		bg1 = "#282c34",
		bg2 = "#30363f",
		bg3 = "#323641",
		bg_d = "#181b20",
		bg_blue = "#61afef",
		bg_yellow = "#e8c88c",
		fg = "#a0a8b7",
		purple = "#bf68d9",
		green = "#8ebd6b",
		orange = "#cc9057",
		blue = "#4fa6ed",
		yellow = "#e2b86b",
		cyan = "#48b0bd",
		red = "#e55561",
		grey = "#535965",
		light_grey = "#7a818e",
		dark_cyan = "#266269",
		dark_red = "#8b3434",
		dark_yellow = "#835d1a",
		dark_purple = "#7e3992",
		diff_add = "#272e23",
		diff_delete = "#2d2223",
		diff_change = "#172a3a",
		diff_text = "#274964",
},
```
The bullet point seems to be using  `bg1 =#282c34`  as the background color... 
but editing the configuration from the repo doesnt have an effect ALTHOUGH i managed to successfully switch the bullet point character with another so that shows its working? I should also mention that other elements are also miscolored like the checkboxes.

```lua
 ui = {
        enable = true,
        update_debounce = 200,
        checkboxes = {
            [" "] = { char = "󰄱", hl_group = "ObsidianTodo" },
            ["x"] = { char = "", hl_group = "ObsidianDone" },
            [">"] = { char = "", hl_group = "ObsidianRightArrow" },
            ["~"] = { char = "󰰱", hl_group = "ObsidianTilde" },
        },
        bullets = { char = "", hl_group = "ObsidianBullet" }, -- does recognise this change.
        external_link_icon = { char = "", hl_group = "ObsidianExtLinkIcon" },
        reference_text = { hl_group = "ObsidianRefText" },
        highlight_text = { hl_group = "ObsidianHighlightText" },
        tags = { hl_group = "ObsidianTag" },
        hl_groups = {
            ObsidianTodo = { bold = true, fg = "#f78c6c" },
            ObsidianDone = { bold = true, fg = "#89ddff" },
            ObsidianRightArrow = { bold = true, fg = "#f78c6c" },
            ObsidianTilde = { bold = true, fg = "#ff5370" },
            ObsidianBullet = { bold = true, fg = "#ffffff", bg = "#000000" }, --colors dont change accordingly
            ObsidianRefText = { underline = true, fg = "#c792ea" },
            ObsidianExtLinkIcon = { fg = "#c792ea" },
            ObsidianTag = { italic = true, fg = "#89ddff" },
            ObsidianHighlightText = { bg = "#75662e" },
        },
    },
```
still, even this doesnt explain how to change the colors of other elements such as headings and bolds...

not sure if they are related but im getting these warning from lua-ls diagnostics:
 │     Missing required fields in type `obsidian.config.ClientOpts`: `picker` Lua Diagnostics. (missing-fields) [1, 27]
 │     Missing required fields in type `obsidian.config.CompletionOpts`: `perferred_link_style` Lua Diagnostics. (missing-fields) [16, 18]
 │     Annotations specify that at most 0 return value(s) are required, found 1 returned here instead. Lua Diagnostics. (redundant-return-value) [64, 16]
 │     Missing required fields in type `obsidian.config.UIOpts`: `tick` Lua Diagnostics. (missing-fields) [92, 10]
 
I just decided to ignore them seeing as i copied the configuration straight from the repo. But I thought it was worth mentioning.

Any help would be greatly appreciated. I understand this issue is multifaceted but its very important i get the colors right for my note taking otherwise its a deal breaker</div>

**Comment by chuan2984** [comment]
I just ran into the same issue, dont have time right now to debug it, which is what I think it is, a bug. i have been able to recreate this option by copy pasting the sourcode and adding a autocmd in my config like so

```
    vim.api.nvim_create_autocmd({ 'BufRead', 'BufNewFile', 'TextChanged', 'TextChangedI' }, {
      pattern = '*.md',
      group = vim.api.nvim_create_augroup('MarkdownSyntaxCustomization', { clear = true }),
      callback = function()
        local hl_opts = {
          checkboxes = {
            [' '] = { char = '󰄱', hl_group = 'ObsidianTodo' },
            ['x'] = { char = '', hl_group = 'ObsidianDone' },
            ['>'] = { char = '', hl_group = 'ObsidianRightArrow' },
            ['~'] = { char = '󰰱', hl_group = 'ObsidianTilde' },
          },
          -- Use bullet marks for non-checkbox lists.
          bullets = { char = '•', hl_group = 'ObsidianBullet' },
          external_link_icon = { char = '', hl_group = 'ObsidianExtLinkIcon' },
          reference_text = { hl_group = 'ObsidianRefText' },
          highlight_text = { hl_group = 'ObsidianHighlightText' },
          tags = { hl_group = 'ObsidianTag' },
          block_ids = { hl_group = 'ObsidianBlockID' },
          hl_groups = {
            -- The options are passed directly to `vim.api.nvim_set_hl()`. See `:help nvim_set_hl`.
            ObsidianTodo = { bold = true, fg = '#f78c6c' },
            ObsidianDone = { bold = true, fg = '#89ddff' },
            ObsidianRightArrow = { bold = true, fg = '#f78c6c' },
            ObsidianTilde = { bold = true, fg = '#ff5370' },
            ObsidianBullet = { bold = true, fg = '#89ddff' },
            ObsidianRefText = { underline = true, fg = '#c792ea' },
            ObsidianExtLinkIcon = { fg = '#c792ea' },
            ObsidianTag = { italic = true, fg = '#89ddff' },
            ObsidianBlockID = { italic = true, fg = '#89ddff' },
            ObsidianHighlightText = { bg = '#75662e' },
          },
        }

        -- This is copied from obsidian source since it does not work
        local function install_hl_groups(ui_opts)
          for group_name, hlopts in pairs(ui_opts.hl_groups) do
            vim.api.nvim_set_hl(0, group_name, hlopts)
          end
        end

        install_hl_groups(hl_opts)

        vim.api.nvim_set_hl(0, 'ObsidianHighlightTag', { fg = '#e6f0d1', bold = true })
        -- Used to hide codeblock that starts with dataview
        vim.cmd [[match ObsidianHighlightTag /highlights::/]]
        -- Execute Vimscript command to define the syntax region
        vim.cmd [[ syntax region DataViewBlock start=/^\(```dataview\|^```dataviewjs\)/ end=/^```/ conceal cchar=* ]]
      end,
    })

```

**Comment by BigLadDylan** [comment]
lua_ls still throws me multiple non-fatal warnings about the default config code thats on the repo. 

Could indicate either my monkey ability to read a manual or an underlying issue with the config.

*Crucially* I think the issue is simply that the config is having trouble overriding highlights set by your theme.

I've mentioned a functioning workaround [in this identical issue](https://github.com/epwalsh/obsidian.nvim/issues/403#issuecomment-1959267811)
