### ISSUE TITLE
`ObsidianNew` does not respect `notes_subdir`

### ISSUE THREAD

**Issue by Mawdac** [epwalsh/obsidian.nvim#395]
### 🐛 Describe the bug

Platform: MacOS

Minimal reproducible config using `lazy.nvim`:

```lua
return {
  "epwalsh/obsidian.nvim",
  version = "*",
  ft = "markdown",
  opts = {
    {
    notes_subdir = "inbox",
    daily_notes = {
      folder = "inbox/dailies",
    },
    workspaces = {
      {
        name = "personal",
        path = "~/vaults/personal",
      },
      {
        name = "work",
        path = "~/vaults/work",
      },
    },
  },
  init = function()
    require("which-key").register({ o = { name = "+obsidian" } }, { prefix = "<leader>", mode = { "n", "v" } })
  end,
  keys = {
    { "<leader>on", "<cmd>ObsidianNew<CR>", desc = "New Note" },
    { "<leader>od", "<cmd>ObsidianToday<CR>", desc = "Todays Note" },
  },
}
```

`ObsidianToday` will still create notes in the first listed workspace using the `daily_notes` location. `ObsidianNew` seems to be using the cwd of the buffer I'm on (or something?) It's behavior is way random whether I'm in or oustide of my vault and doesn't respect `notes_subdir`

Example:
- Open a file, then run `ObsidianNew` with no title, it creates a file in the same dir as the open file in your current buffer.
- Open a file in your vault, then open a file somewhere outside the vault, it defaults back to some dir in my vault (inbox/dailies when I tried it, sometimes other places)

Not sure what's happening exactly but let me know if I can share more.

### Versions

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
[obsidian.nvim (v3.1.0)] Commit SHA: 06154ec6f2964632d53c8fea9f0c175f31357192
[plenary.nvim] Commit SHA: 4f71c0c4a196ceb656c824a70792f3df3ce6bb6d
[nvim-cmp] Commit SHA: 04e0ca376d6abdbfc8b52180f8ea236cbfddf782
ripgrep 14.0.3⏎

**Comment by epwalsh** [comment]
Hey @Mawdac, `:ObsidianNew` respects the `completion.new_notes_location` field in your config, which defaults to "current_dir". To get the behavior you want, you should set that to "notes_subdir".

**Comment by Mawdac** [comment]
Ah that explains it, thank @epwalsh !
