### ISSUE TITLE
"Invalid alias in frontmatter"

### ISSUE THREAD

**Issue by DefinitelyNotSimon13** [epwalsh/obsidian.nvim#412]
### 🐛 Describe the bug

Whenever I save a file or when I try to wikilink another file, I get :
```
Invalid alias value found in frontmatter for /home/simon/4_Notes/uni/Mathe/Mitschrift 19.02.2024.md. Expected string, found table.
```

Even after quite  a bit of digging, changing my Linter settings etc, I still get the error and I am absolutely clueless. This may very well be an issue on my side, however since I have no issues at all in Obsidian itself, I feel like this might also be a bug. 
Any help would be appreciated either way.

### Config

```
 154   │   {
 155   │     "epwalsh/obsidian.nvim",
 156   │     version = "*", -- recommended, use latest release instead of latest commit
 157   │     lazy = true,
 158   │     ft = "markdown",
 159   │     dependencies = {
 160   │       "nvim-lua/plenary.nvim",
 161   │       "hrsh7th/nvim-cmp",
 162   │       "epwalsh/pomo.nvim"
 163   │     },
 164   │     opts = {
 165   │       workspaces = {
 166   │         {
 167   │           name = "Notes",
 168   │           path = "~/4_Notes",
 169   │         },
 170   │       },
 171   │     },
```

### Environment

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
[obsidian.nvim (v2.10.0)] Commit SHA: 32de09d0c737d314ff629068902c4657c244d55b
[plenary.nvim] Commit SHA: 4f71c0c4a196ceb656c824a70792f3df3ce6bb6d
[nvim-cmp] Commit SHA: 04e0ca376d6abdbfc8b52180f8ea236cbfddf782
ripgrep 14.1.0%   
```

**Comment by epwalsh** [comment]
Hey @DefinitelyNotSimon13, I think the error is pretty clear, no? There's an issue parsing the frontmatter for the note at `/home/simon/4_Notes/uni/Mathe/Mitschrift 19.02.2024.md`.

**Comment by epwalsh** [comment]
If this is a parser issue let me know with a reproducible example and I'll reopen. Otherwise it seems like you have invalid YAML in the frontmatter for one of your files.
