### ISSUE TITLE
Add option to customize file name 

### ISSUE THREAD

**Issue by milch** [epwalsh/obsidian.nvim#444]
### 🚀 The feature, motivation and pitch

As far as my understanding of the config goes, right now you can basically choose between unique IDs, which then results in unique filenames because the file name and ID always match, or you could allow for non-unique filenames, which results in ID-clashes. Personally for some folders I like to have an Index.md that serves as an entry point to that folder and links out to other important notes, and I don't use zettel-style or other kinds of unique filenames. However, even with non-unique filenames it makes sense for the IDs to still be unique so things like linking by ID work as expected. Some Obsidian plugins, e.g. the Omnivore plugin, work this way by using the title of the article as the filename but using a UUID as the ID

A way to implement this could be to introduce a `file_name_func` that takes options such as the ID, title and path, and returns the intended file name. A default `file_name_func = function(opts) return opts.id end` would then maintain the current behavior.

### Alternatives

I could disregard IDs altogether and always link to the path, but sometimes paths can get quite long, and because concealed texts still make the line take up that space in neovim that can break the formatting or make it very awkward looking

**Comment by epwalsh** [comment]
Hey @milch, I can definitely sympathize with that and I like your proposed solution. I've created a draft of that feature in #445. Can you let me know if that's sufficient for your use-case?

**Comment by milch** [comment]
You're the best, thank you so much. I just tried it out and it works great 🎉  There is a minor issue I believe where the assumption that `id == filename` still holds, which is the front matter function. If I create a note in Obsidian (or e.g. with nvim-tree, or delete the front matter on an existing note), open it and then save it in neovim, the inserted `id` will be the name of the file, but I think it should now call the `note_id_func` to obtain the id.

**Comment by epwalsh** [comment]
@milch thank you for the coffee funds by the way!

**Comment by epwalsh** [comment]
@milch once #451 lands you could also accomplish this through a callback by adding this to your obsidian.nvim config:

```lua
callbacks = {
  enter_note = function(client, note)
    if not note.has_frontmatter then
      note.id = client:new_note_id(note.title)
      client:update_frontmatter(note)
    end
  end,
},
```

**Comment by milch** [comment]
Thanks for the update! I'm not sure I 100% understand, updating the IDs on previously created notes is one thing, but e.g. if I use `:ObsidianExtractNote` to create a new note from text in another note, it correctly creates that note with the name specified in the `note_path_func` and the id with the ID generated by the `note_id_func`, but then as soon as I save it the ID gets replaced with the filename. That's using a slightly modified version of the default front matter function from the README:

```lua
			note_frontmatter_func = function(note)
				local out = {
					id = note.id,
					aliases = note.aliases,
					tags = note.tags,
					created_date = os.date("%Y-%m-%d", os.time()),
				}
				-- `note.metadata` contains any manually added fields in the frontmatter.
				-- So here we just make sure those fields are kept in the frontmatter.
				if note.metadata ~= nil and not vim.tbl_isempty(note.metadata) then
					for k, v in pairs(note.metadata) do
						out[k] = v
					end
				end
				return out
			end,
```

**Comment by milch** [comment]
Oh my bad, I pulled the latest mainline branch and that seems to be fixed.

**Comment by epwalsh** [comment]
Ah yea I did notice that bug. Yea should be fixed now.
