### ISSUE TITLE
Don't write frontmatter to file if it is empty

### ISSUE THREAD

**Issue by UtkarshVerma** [epwalsh/obsidian.nvim#480]
### 🚀 The feature, motivation and pitch

Currently, the plugin exposes `note_frontmatter_func` which is of the type `fun(note:obsidian.Note):table`. The table is prepended to the current buffer on save.

Now, when the table is empty, this results in an unnecessary addition of empty frontmatter at the top of the file.

```md
---
---

Other text....
```

I think it would be more intuitive if we checked the returned table using `vim.tbl_isempty()` and only inject the frontmatter if it has some content.

### Alternatives

To not affect the defaults, if that is desirable, we could change the type of `note_frontmatter_func` to `fun(note:obsidian.Note):table?`.

The `nil` value would indicate that there is no frontmatter and that it should be removed from the current file.

**Comment by epwalsh** [comment]
@UtkarshVerma I agree this would make sense. If you want to make a PR, I believe you'd just have to modify `Note:frontmatter_lines()` to return an empty list when `vim.tbl_isempty()`:

https://github.com/epwalsh/obsidian.nvim/blob/1c2921ed1fd26e541c7ab1fc98f924125c010e67/lua/obsidian/note.lua#L582
