### ISSUE TITLE
New note in buffer only (ie. don't save freshly created note)

### ISSUE THREAD

**Issue by RetroTechCorner** [epwalsh/obsidian.nvim#489]
### 🚀 The feature, motivation and pitch

It would be great if ObsidianNew (or alternative command) could only create a note in the current/new buffer and only save on explicit vim write.  
Currently there's no way (I know of) discarding a new note (as it will be written to the disk on creation - which leads/may lead to many "empty" notes)

**Comment by epwalsh** [comment]
@RetroTechCorner that seems reasonable for `:ObsidianNew`. I've implemented that in #490.
