### ISSUE TITLE
Allow searching of nested tags / tags starting with string

### ISSUE THREAD

**Issue by SchnozzleCat** [epwalsh/obsidian.nvim#493]
### 🚀 The feature, motivation and pitch

Obsidian supports nested tags, and it would be nice to be able to either search for nesting, or search for tags starting with some string.

e.g. for tags ``#topleveltag/subtag1`` and ``#topleveltag/subtag2``, ``ObsidianTags topleveltag`` would return both.

Currently it will just show an empty telescope picker.

As an example:
In obsidian:
![image](https://github.com/epwalsh/obsidian.nvim/assets/67333469/181f30c8-f303-4656-bb0e-57400382c606)

In nvim after ``ObsidianTags resources``:
![image](https://github.com/epwalsh/obsidian.nvim/assets/67333469/02f58537-e826-4c4e-bd42-0eb8d67f403d)

### Additional context

Something that is also strange is that ``ObsidianTags`` seems to think tags exist when searching for beginning string, as it doesn't give the error ``Tags not found`` that is normally shown when searching for a tag that does not exist at all. 

For example, if I have the tag ``#mytag``, ``ObsidianTags myt``, will show an empty telescope picker, instead of showing ``Tags not found``. 
(Ideally this would show all files that have a tag starting with the query string)

**Comment by epwalsh** [comment]
Hey @SchnozzleCat, I fixed the issue with the empty picker in 450c3da.

**Comment by SchnozzleCat** [comment]
> > and it would be nice to be able to either search for nesting, or search for tags starting with some string.
> 
> If you run `:ObsidianTags` without any arguments, you'll get a picker list of ALL tags, which you can then filter down. When you select a tag or multiple tags in that picker list, `<CR>` will open a new picker with the location of those tags. Does that solve your use-case?

I'm not sure why I didn't think to try it without arguments :sweat_smile: 

Yes, that should cover my use case, thanks!
