### ISSUE TITLE
[Feature] Follow header links

### ISSUE THREAD

**Issue by cmvanb** [epwalsh/obsidian.nvim#50]
### 🚀 The feature, motivation and pitch

I use header links in Obsidian like these:

```
[[#Some header in my note]]

...

### Some header in my note
```

In Obsidian, clicking the header link scrolls down to the linked header in the document.

It would be useful if obsidian.nvim could do the same with `:ObsidianFollowLink`.

### Alternatives

The alternative is scrolling down manually.

**Comment by epwalsh** [comment]
Agreed, this would be great. Contributions welcome!

**Comment by swaits** [comment]
+1 on this.

Any pointers on where to start look at implementation? I'm glad to look at it, but if you have any ideas on how you want it done, @epwalsh, I'll use that as guidance.

**Comment by epwalsh** [comment]
Hey @swaits, it looks like we'd start by checking for a "#" at the beginning of the link name, somewhere after [this point](https://github.com/epwalsh/obsidian.nvim/blob/0418505ff7d1e06460450a02b9209d03f4c2a50d/lua/obsidian/command.lua#L534) in the `command.follow` function. The tricky part would then be iterating over lines in the buffer to find the matching header. It would be good to split that functionality into a util function (`lua/obsidian/util.lua`).

**Comment by mscott99** [comment]
I use links of the form [[file_name#header_section]], and clicking on them creates a wrong file "file_name#header.md" that I then have to delete later. A quick fix would be to simply ignore anything after the '#' and treat it as a normal link; that would already be a big improvement.

**Comment by epwalsh** [comment]
@mscott99 quick fix in #152.

**Comment by MohamedOsman1998** [comment]
I made a comment in #152 and ill make it here as well, but the fix in #152 doesnt fix links that use ^. i.e. block links. A fix for that would be great as well!

**Comment by videbar** [comment]
Hi @epwalsh, I'd like to do some work on this.

I've used tree-sitter to prototype two functions:

- `get_header_pos()`: Takes a header title and find the position of the section in the file. I think this could be used inside [`command.follow`](https://github.com/epwalsh/obsidian.nvim/blob/0418505ff7d1e06460450a02b9209d03f4c2a50d/lua/obsidian/command.lua#L517) to jump to the right position in the file being opened (e.g., using something like `:edit +<line number> <filename>`). If the reference is in the current buffer, only the cursor needs to move.

- `get_all_headers()`: Finds all the header titles of a given file. This could be used to add the title sections as suggestions in the autocomplete menu. Could you point me to a place in the code where this could be implemented? I saw that there are two files called `cmp_obsidian.lua` and `cmp_obsidian_new.lua`, but I'm not sure where it should be placed.

So far they don't support hierarchy, i.e, linking something as `[[note_name#section#subsection]]`, but I can open a PR, add the functions to `util.lua` and see if I can make everything work. From there, I can see how hard it is to also add hierarchy.

**Comment by epwalsh** [comment]
Hey @videbar, sorry for the slow reply...

> `get_all_headers()`: Finds all the header titles of a given file. This could be used to add the title sections as suggestions in the autocomplete menu. Could you point me to a place in the code where this could be implemented? I saw that there are two files called cmp_obsidian.lua and cmp_obsidian_new.lua, but I'm not sure where it should be placed.

I think this is only relevant for existing note completion, which lives in `cmp_obsidian.lua`. The logic there relies on the `client:search()` method (in `obsidian/init.lua`) which returns an iterator over `Note` objects. So if we were to get this working with minimal changes then I think we want to modify `client:search()` to handle headers, and the iterator it returns needs to contain header information as well. So maybe we make a new object, like `SearchResult` or something that contains both a note and an optional header link within the note.

Does that make sense? I'd be happy to review a PR

**Comment by epwalsh** [comment]
This is implemented now on `main`.
