### ISSUE TITLE
Feature request: open on current line

### ISSUE THREAD

**Issue by anuramat** [epwalsh/obsidian.nvim#520]
### 🚀 The feature, motivation and pitch

New function/command: in Obsidian app, open current file **and scroll down to the current line**

Motivation: I'm doing math notes in obsidian, and I usually have two windows side by side: Neovim to write, and Obsidian to preview the rendered output. With this feature, I won't ever have to touch the obsidian app window to scroll down to the currently edited line. The rough equivalent of this for actual LaTeX is called SyncTeX.

**Comment by XiaowenHu96** [comment]
This sounds like you're looking for a search functionality similar to SyncTeX. 
This would require the viewer (in this case, the Obsidian app) to support some kind of protocol for remote control, allowing an editor (such as Neovim) to send commands to it. As far as I know, Obsidian currently does not support this feature directly. The closest feature available is the official [Obsidian URI protocol](https://help.obsidian.md/Extending+Obsidian/Obsidian+URI), which, unfortunately, does not support jumping to an arbitrary line.

In terms of community plugins, there are options like [Advanced URI](https://github.com/Vinzent03/obsidian-advanced-uri) and [Obsidian Local REST API](https://github.com/coddingtonbear/obsidian-local-rest-api). However, it's uncertain to what extent the maintainers are willing to add features that rely on third-party plugins.

I would actually recommend you set it up on your own. The advanced URI plugin does support jumping to a specific line in a file. Then all you need to do is to figure out the current position through `nvim_win_get_cursor` and then issue a command `xdg-open <URL>` from neovim (assuming Linux).
