### ISSUE TITLE
ObsidianTags does not work if visual selection has been triggered

### ISSUE THREAD

**Issue by DRKolev-code** [epwalsh/obsidian.nvim#557]
### 🐛 Describe the bug

If you do `viw` and then do `:ObsidianTags` it works. If you exit visual selection and do `:ObsidianTags` again it tries to find the previously selected word from `viw`. From the code it seems it should look for the word under the cursor in normal mode but it does not do that.

### Config

Don't think it matters.

### Environment

Don't think it matters.

**Comment by epwalsh** [comment]
Hey @DRKolev-code, fixed in f73e6fd.
