### ISSUE TITLE
Completion for folder names

### ISSUE THREAD

**Issue by aleprovencio** [epwalsh/obsidian.nvim#561]
### 🚀 The feature, motivation and pitch

Hi! As my notes live inside different folders, it would be very nice if there was some sort of completion aid when creating a new note with either `:ObsidianNew` or via the insert mode completion. This also extends to `:ObsidianRename` and other commands.

Forgive me if I'm missing some setting.

**Comment by epwalsh** [comment]
Hey @aleprovencio, I've added this for `:ObsidianRename` in 79f7f2a. And for the prompt in `:ObsidianNew` in c299e28.
