### ISSUE TITLE
Folder completion not working from `config.workspaces.path`

### ISSUE THREAD

**Issue by aleprovencio** [epwalsh/obsidian.nvim#570]
### 🐛 Describe the bug

Some of my notes live in a repository that contains a [`quartz`](https://quartz.jzhao.xyz/) structure:

```
 .
├──  .git
├──  .github
├──  .gitea
├──  content  <- WHERE MY NOTES LIVE
│  ├──  Fleeting
│  ├──  Literature
│  ├──  Permanent
│  ├──  Projects
│  ├──  Resources
│  └──  index.md
├──  docs
│  ├── ...
├──  quartz
│  ├── ...
├──  README.md
├── ...
```

So I have this setting for `obsidian.nvim`:

```lua
workspaces = {
    {
      name = 'zk',
      path = vim.fn.expand '~/.local/share/code/zk-quartz/content',
    },
}
```

Notice that `path` points to the `content` folder instead of the root of `zk-quartz` where `.git` lives.

Commands like `ObsidianQuickSwitch` work as intended and will present the filtered notes like `Fleeting/Note to find` (instead of `content/Fleeting/Note to find`)

However, when using `:ObsidianNew`, the completion starts from `zk-quartz` instead of the `content` directory, so it will only complete something like `content/Fleeting/A new note`. If `notes_subdir` and `new_notes_location` are not set, it will try to create this file on `content/content/Fleeting/A new note`

A workaround I have found for this problem is to set `notes_subdir = 'content'`, `new_notes_location = 'notes_subdir'` and bring the `config.workspaces.path` to the parent directory, like:

```lua
workspaces = {
    {
      name = 'zk',
      path = vim.fn.expand '~/.local/share/code/zk-quartz',
    },
}
```

But as a consequence, `ObsidianQuickSwitch` will always prefix the redundant `content/` directory to the filtered notes and I must always start the completion to `ObsidianNew` with `content/` instead of for instance `Fleeting/`.

Am I missing something or can this be improved somehow?

### Config

```lua
  {
    'epwalsh/obsidian.nvim',
    version = '*',
    dependencies = {
      'nvim-lua/plenary.nvim',
    },

    opts = {
      workspaces = {
        {
          name = 'zk',
          path = vim.fn.expand '~/.local/share/code/zk-quartz/content',
        },
      },
    },
  }
```

### Environment

```shell
❯ nvim --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1713773202

    arquivo vimrc de sistema: "$VIM/sysinit.vim"
            padrão para $VIM: "/usr/share/nvim"

Run :checkhealth for more info

~ 
❯ nvim --headless -c 'lua require("obsidian").info()' -c q

Obsidian.nvim v3.7.11 (754d3410b907b5f5ae3c9f4ccf643ea945021341)
Status:
  • buffer directory: nil
  • working directory: /home/aleprovencio
Workspaces:
  ✓ active workspace: Workspace(name='no-vault', path='/home/aleprovencio', root=
'/ho
me/aleprovencio')
  ✗ inactive workspace: Workspace(name='zk', path='/home/aleprovencio/.local/shar
e/co
de/zk-quartz/content', root='/home/aleprovencio/.local/share/code/zk-quartz/conte
nt')
Dependencies:
  ✓ plenary.nvim: 08e301982b9a057110ede7a735dd1b5285eb341f
  ✓ nvim-cmp: 8f3c541407e691af6163e2447f3af1bd6e17f9a3
Integrations:
  ✓ picker: TelescopePicker()
  ✓ completion: enabled (nvim-cmp) ✗ refs, ✗ tags, ✗ new
    all sources:
      • nvim_lsp
      • path
      • emoji
      • buffer
      • luasnip
Tools:
  ✓ rg: ripgrep 14.1.0
Environment:
  • operating system: Linux
Config:
  • notes_subdir: nil⏎                                                           
```

**Comment by epwalsh** [comment]
What directory are you in when you run `:ObsidianNew`? `~/.local/share/code/zk-quartz` or `~/.local/share/code/zk-quartz/content`?

**Comment by aleprovencio** [comment]
You are right, that must the problem because `:pwd` shows I'm in `~/.local/share/code/zk-quartz`.

I tried disabling `project.nvim` which is something I know that changes `CWD`, but still no luck.

Any ideas of what else might be going on?

**Comment by aleprovencio** [comment]
Anyway, I'm now using `project.nvim` to stay at the right `CWD` by appending `.obsidian` to its patterns.
Thanks for you help and effort on this plugin @epwalsh
