### ISSUE TITLE
:ObsidianBacklinks not yielding any results

### ISSUE THREAD

**Issue by gerryhernandez** [epwalsh/obsidian.nvim#58]
### 🐛 Describe the bug

When doing `:ObsidianBacklinks` from within a note inside of NeoVim, the resulting window does not show any references. From within Obsidian's viewer, I do see references.

A couple things of note:
1. I'm very new to Obsidian itself and I might be missing something obvious that's unrelated to this plugin. I basically just use Obsidian as a glorified Markdown viewer, plus some other things that make more sense in a GUI.
2. The backlinks that Obsidian shows are "linked mentions." Not sure if that makes a difference or not.

Minimal reproduction steps:
1. Navigate to an existing note.
2. Write a new `[[Link Like This]]`
3. Use `gf` within the link and it'll navigate to a new buffer.
4. `:w` the buffer and then the metadata at the top is automagically filled in.
5. Do an `:ObsidianBacklinks`
6. The backlinks nvim window is empty, but Obsidian application shows the backlink.

One more thing, which I'm not sure is related or not: I'm prompted to hit `<CR>` after `:ObsidianBacklinks` before the nvim window is displayed. It's an annoying papercut, but not the focus of this issue.

### Versions

```
❯ nvim --version
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

❯ nvim --headless -c 'lua print(require("obsidian").VERSION)' -c q
1.6.1% 

❯ git log -1 --oneline
06c1d13 (HEAD -> main, upstream/main, origin/main, origin/HEAD) chore: auto generate docs                                                                                       
```

**Comment by BeCracked** [comment]
I have the same issue with neovim 0.9.0. A note with a number of backlinks does not show any for `ObsidianBacklinks`.

```
❯ nvim --version
NVIM v0.9.0-dev-91-gd339b4aad
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az334-638

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

❯ nvim --headless -c 'lua print(require("obsidian").VERSION)' -c q
1.6.1%
```

**Comment by epwalsh** [comment]
Hey @gerryhernandez, can you show me what the frontmatter looks like for the note in question? I'm having trouble reproducing this

**Comment by xiantang** [comment]
this is because your frontmatter problem, you can check you file header if not have yaml style frontmatter your can use my script to add frontmatter to your files:


```bash

#!/bin/bash

# list all markdown files in the current directory
# then check the header is ymal start with ---
# if not, add the value to the start of the file %s is the file name

value=$(cat <<EOF
---
id: "%s"
aliases:
  - "%s"
tags: []
---\n\n
EOF)

for file in *.md; do
		if [[ $(head -n 1 "$file") != "---" ]]; then
				echo "Adding header to $file"
				# remve the .md from the file name
				file_name=${file%.md}
				echo "$file_name"
				printf  --  "$value" "$file_name" "$file_name"  >> temp
				cat "$file" >> temp
				mv temp "$file"
				echo "$file_name" 
		fi
done
```

**Comment by gerryhernandez** [comment]
Hey @epwalsh , I left Obsidian and just came back. Sorry for the slow response. Anyhow, using my reproduction steps in the original post, the backlinks don't work when following a link (`gf` fallthrough) to create a new note, but they do work when doing an `:ObsidianNew` to create the note. I can reproduce this every time.

Now that I have a workaround, I can survive for a while without a fix. I have other priorities right now, but I can dedicate time to fix this on the 15th. In the meantime, if anyone else could confirm/reproduce this behavior to rule out my own environment, that'd be appreciated!

**Comment by gerryhernandez** [comment]
Well, I think I came up with a minimal, sensible fix. I've been using it for a few hours, so I put a PR together.
