### ISSUE TITLE
Is it possible to change the working vault on the fly?

### ISSUE THREAD

**Issue by Paracelsus-Rose** [epwalsh/obsidian.nvim#60]
### 🚀 The feature, motivation and pitch

Looking for a way to change the working vault set up in config.  Not the best with lua or nvim, but this would be greatly used. Thinking of something along the lines of harpoon, where you can mark a few vaults, then open a modal and switch to each vault, then execute commands as needed.  If there is some way I can help, I would be willing to dive in and make a PR, just really not sure how to get started.  Thanks :-)

**Comment by epwalsh** [comment]
Hey @Paracelsus-Rose, this is definitely doable. We could probably expose a new command that would change the Obsidian [client's directory](https://github.com/epwalsh/obsidian.nvim/blob/302cf774058f3a3f085aa03cd0ec7ca41d80cf21/lua/obsidian/init.lua#L28).

**Comment by bassamsdata** [comment]
That's would be very helpful and a powerful command. 🔝

**Comment by epwalsh** [comment]
We now have the `:ObsidianWorkspace` command.
