### ISSUE TITLE
treesitter error in obsidian note

### ISSUE THREAD

**Issue by hfytr** [epwalsh/obsidian.nvim#601]
### 🐛 Describe the bug

I get this error every few seconds when typing in a note:```
   Error  05:03:29 PM msg_show.lua_error Error executing vim.schedule lua callback: ...ed-0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 94 for language latex
stack traceback:
	[C]: in function '_ts_parse_query'
	...ed-0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get_query'
	...share/nvim/lazy/noice.nvim/lua/noice/text/treesitter.lua:7: in function 'get_query'
	...share/nvim/lazy/noice.nvim/lua/noice/text/treesitter.lua:49: in function 'fn'
	...5/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:345: in function 'for_each_tree'
	...5/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:349: in function 'for_each_tree'
	...5/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:349: in function 'for_each_tree'
	...share/nvim/lazy/noice.nvim/lua/noice/text/treesitter.lua:45: in function 'highlight'
	...local/share/nvim/lazy/noice.nvim/lua/noice/text/init.lua:67: in function 'highlight'
	...dw/.local/share/nvim/lazy/nui.nvim/lua/nui/line/init.lua:58: in function 'highlight'
	...dw/.local/share/nvim/lazy/nui.nvim/lua/nui/line/init.lua:73: in function 'render'
	...ocal/share/nvim/lazy/noice.nvim/lua/noice/text/block.lua:98: in function 'render'
	...al/share/nvim/lazy/noice.nvim/lua/noice/lsp/override.lua:52: in function 'stylize_markdown'
	...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/view/docs_view.lua:64: in function 'open'
	...e/fbwdw/.local/share/nvim/lazy/nvim-cmp/lua/cmp/view.lua:292: in function 'callback'
	.../.local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/async.lua:138: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Config

```
-- lazy config
{
    "epwalsh/obsidian.nvim",
    version = "*",
    lazy = true,
    ft = "markdown",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "hrsh7th/nvim-cmp",
      "nvim-telescope/telescope.nvim",
      "nvim-treesitter/nvim-treesitter",
    },
    opts = {
      workspaces = {{
        name = "docs",
        path = "~/docs",
      }},
    },
  }
```

### Environment

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1693350652

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/lx2qw2fwcx699g4vy10kf9y967zl608g-neovim-unwrapped-0.9.5/share/nvim
"

Run :checkhealth for more info
Obsidian.nvim v3.7.12 (db41b1f20459293436fab510bec58c82a73bd1f7)
Status:
  • buffer directory: nil
  • working directory: /home/fbwdw
Workspaces:
  ✓ active workspace: Workspace(name='docs', path='/home/fbwdw/docs', root='/home/fbwdw/docs')
Dependencies:
  ✓ plenary.nvim: 08e301982b9a057110ede7a735dd1b5285eb341f
  ✓ nvim-cmp: cd2cf0c124d3de577fb5449746568ee8e601afc8
  ✓ telescope.nvim: 6312868392331c9c0f22725041f1ec2bef57c751
Integrations:
  ✓ picker: TelescopePicker()
  ✓ completion: enabled (nvim-cmp) ✗ refs, ✗ tags, ✗ new
    all sources:
      • nvim_lsp
      • luasnip
      • path
Tools:
  ✓ rg: ripgrep 14.1.0
Environment:
  • operating system: Linux
Config:
  • notes_subdir: nil%                                                                                                                                     ```

**Comment by epwalsh** [comment]
Hey @hfytr, I don't see anything in the stack trace from obsidian.nvim's code...

**Comment by ForceFaction** [comment]
I have the same problem.  Invlaid node type on every LaTeX fragemnt enclosed by $$.  I don't know how to produce helpful debug information though.

**Comment by ForceFaction** [comment]
So the solution seems to be to `:TSInstall all` and `TSUpdate`  which updated the latex parser.  This makes the error disappear.
