### ISSUE TITLE
Don't hardcode "daily-notes" tag when using ObsidianToday / ObsidianYesterday

### ISSUE THREAD

**Issue by SignalWalker** [epwalsh/obsidian.nvim#628]
### 🚀 The feature, motivation and pitch

Right now, the plugin automatically adds "daily-notes" to the tags in [`Client._daily`](https://github.com/epwalsh/obsidian.nvim/blob/c6bd6d93e4724ac2dc0cae73ebe1d568bf406537/lua/obsidian/client.lua#L1935). For parity with the official app, I'd prefer to manage that in the note's template, but there doesn't seem to be a way to stop the plugin from adding that tag.

**Comment by epwalsh** [comment]
Hey @SignalWalker, that's sort of a legacy feature from when I was building this for personal use only, and definitely doesn't make much sense now! In 2d69fb2 I've added the configuration option to customize or remove these.

**Comment by SignalWalker** [comment]
Cool, thanks!
