### ISSUE TITLE
Noevim GUI apps crashes whenever apply obsidain command

### ISSUE THREAD

**Issue by bassamsdata** [epwalsh/obsidian.nvim#65]
### 🐛 Describe the bug

Firstly, I would like to thank you for this amazing plugin.

**The issue:**
Neovim _**crashes**_ every time an obsidian command execute on the Gui apps of Neovim (Neovide and goneovim)

**Steps to reproduce:**
- open neovide or goneovim
- setup obsidian to a specific vault.
- try any of these obsidian commands: `obsidianopen`, `obsidiannew`, `obsidiansearch` and search and try to open the file.
- the gui app will crash.

**Notes:** 
- even changing the vault the issue persisits. 
- the gui app can open any `md` file from the vault until link the vault to the obsidian plugin and try to open the note from the obsidian plugin then the gui will crash until you un-link the vault.

### Versions

nvim --version
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3

nvim --headless -c 'lua print(require("obsidian").VERSION)' -c q
1.6.1%

OS: macOS 12.6

**Comment by epwalsh** [comment]
Hey @bassamsdata, sorry to hear that. I am able to reproduce this so I'll try to debug it.

**Comment by epwalsh** [comment]
It seems Neovide doesn't like the Lua function `os.execute()`. In fact, open any buffer in Neovide and run `:lua os.execute("ls")` and it will immediately crash. There's an open issue for this already: https://github.com/neovide/neovide/issues/1376

**Comment by bassamsdata** [comment]
Unfortunately, it cannot be used on these apps. In spite of the fact that the apps have been built differently (Neovide and goneovim), they behave strangely. Your time spent debugging it is greatly appreciated.

**Comment by bassamsdata** [comment]
This seems to be solved with the latest version of neovide 0.10.4.
Thanks for your assistance
