### ISSUE TITLE
Find note

### ISSUE THREAD

**Issue by joserc87** [epwalsh/obsidian.nvim#66]
### 🚀 The feature, motivation and pitch

First of all, thanks for this marvelous plugin and apologies if the feature is there, but I couldn't find it.

One of the most basic things I do in obsidian is to `<Ctrl-O>` to quickly open a note, if I remember the name. I'm not talking about searching _inside_ the notes, but trying to open a specific note by name, so this is not the same usecase as `:ObsidianSearch`, it's much simpler than that. For example, let's say I just want to quickly read my `obsidian.nvim` cheatsheet. I'd like to run something like `:ObsidianSelectNote` (conveniently mapped to some shortcut) to see a list in Telescope with *only* the name of the notes (so it's a much more reduced list than with `:ObsidianSearch`) and from there I can type the name of the note to open it.

AFAIK there is no such command, but if there is, I'm happy to send a PR to change the README.

### Alternatives

I guess that for the time being `:ObsidianSearch` does the job as well, because it _also_ searches for the filename, but if I already know the name of the note, having to search through the content as well seems inefficient.

**Comment by epwalsh** [comment]
Hey @joserc87, currently Obsidian relegates that functionality to other plugins. Personally I use `fern` in combination with `fzf` via [fern-mapping-fzf.vim](https://github.com/LumaKernel/fern-mapping-fzf.vim). But it would be nice to have something like that within this plugin.

**Comment by joserc87** [comment]
Fair enough. It's just a list of files, so I can hack it myself into telescope. The only benefit of having it inside obsidian.nvim is that I don't have to spread the configuration to multiple places. Since obsidian.nvim "knows" where my notes are, it can list the files. Not a huge deal, but it would be a nice to have.
I'm a complete noob when it comes to lua and neovim plugins, but I could try to give it a go and try to create a PR, because as I said, I love this plugin. Kudos!

**Comment by epwalsh** [comment]
Great, I'd love to see a PR for this if you find the time!

**Comment by joserc87** [comment]
I sent a PR.
> Personally I use fern in combination with fzf via [fern-mapping-fzf.vim](https://github.com/LumaKernel/fern-mapping-fzf.vim).
I'm very interested to know if there is anything in your current workflow that is not in the new command. We should make it at least as useful as your current workflow, so that you can make the switch.

**Comment by joserc87** [comment]
#68 got merged, so I'm happy to resolve this issue :tada:
