### ISSUE TITLE
ObsidianNewFromTemplate documentation

### ISSUE THREAD

**Issue by ajmichels** [epwalsh/obsidian.nvim#670]
### 📚 The doc issue

The documentation shows:

> `:ObsidianNewFromTemplate [PATH] [TEMPLATE]` to create a new note from a template in the templates folder.

Which seems to suggest that the name of the template can be specified as part of the command. Which would honestly be great if it was an optional argument. However, this doesn't seem to actually work.

The documentation goes on to say:

> Selecting from a list using your preferred picker. This command has one optional argument: the path to the new note.

Which matches the behavior, as far as I can tell, but not the example.

### Suggest a potential alternative/fix

Either the documentation should be updated to:

> `:ObsidianNewFromTemplate [PATH]` to create a new note from a template in the templates folder. Selecting from a list using your preferred picker. This command has one optional argument: the path to the new note.

Or preferably the functionality would be updated so support the second optional argument to specify the template. This would users to predefine operations to create notes using specific templates without needing to select them from the picker.

For example, one might want to have a "weekly note" template and have a key mapping to create such a note from a specific template every time.

**Comment by epwalsh** [comment]
@ajmichels I fixed the documentation in 45bd6b9. It would be nice to allow a template arg as well but that might take a little more care as it would change the signature of the command, and how we parse the arguments.
