### ISSUE TITLE
Support find backlinks under cursor

### ISSUE THREAD

**Issue by xiantang** [epwalsh/obsidian.nvim#71]
### 🚀 The feature, motivation and pitch

📃 Motivation

I want implement this feature like lsp feature find references, because sometime we don't just only see the backlinks in this buffer, but also want to see the backlinks in current cursor : 

` vim.keymap.set('n', 'gr', vim.lsp.buf.references, bufopts)`

when I press `gr` in normal mode, it will show all references of the word under cursor.

and show a quickfix list window, I can select one of them to jump to the reference.

when the cursor is not in a markdown link, it will show the backlinks of current buffer.

```lua
vim.keymap.set("n", "<Leader>gr", function()
	if require("obsidian").util.cursor_on_markdown_link() then
		return "<cmd>ObsidianCursorBacklinks<CR>"
	else
		return "<cmd>ObsidianBacklinks<CR>"
	end
end, { noremap = false, expr = true })
```

### Additional context

I already implemented this feature in my branch
let me showoff in a gif:

![Kapture 2023-01-01 at 15 33 46](https://user-images.githubusercontent.com/34479567/210163905-34fcdbd2-4645-4f38-b13b-d7a3c3709c63.gif)

**Comment by xiantang** [comment]
PTAL @epwalsh

**Comment by simonlearnscoding** [comment]
thats pretty cool. is it possible to show backlinks as virtual text? has this been merged into production?

**Comment by epwalsh** [comment]
Virtual text might be a little too limited to show a list of backlinks, although we could potentially have a hover window. I'm not sure yet what it would take to implement that.
