### ISSUE TITLE
Markdown Links instead of WikiLinks

### ISSUE THREAD

**Issue by vicecaycedo** [epwalsh/obsidian.nvim#75]
### 🚀 The feature, motivation and pitch

Markdown links are generally better supported than WikiLinks in other tools. As such, Obsidian has the option to use markdown links instead of wikilinks. Can a similar configuration option be provided here for the autocompletion? Thanks!

**Comment by vicecaycedo** [comment]
Yes, that's exactly what I meant 🙂 

I like the second option more as well, but if that's too much work, the first option seems good to me too!

Thanks for making this plugin!

**Comment by bigzhu** [comment]
Need this feature too, 2 is better.

**Comment by epwalsh** [comment]
Option 2 is now implemented in #237
