### ISSUE TITLE
Toggle checkboxes in range

### ISSUE THREAD

**Issue by einarpersson** [epwalsh/obsidian.nvim#765]
### 🚀 The feature, motivation and pitch

It is very common that I want to select many checkboxes at once and toggle them all. My expectation was that I could do visual line selection and then toggle checkbox, but it says 'range not allowed'.

### Alternatives

Do some kind of wrapper utility function myself, but I thought that I can't be the only one that would benefit from this

**Comment by grezzogg** [comment]
This worked for me:

`vim.keymap.set("v", "<leader>ol", ':g/^/lua require("obsidian").util.toggle_checkbox()<cr>')`

**Comment by einarpersson** [comment]
> This worked for me:
> 
> `vim.keymap.set("v", "<leader>ol", ':g/^/lua require("obsidian").util.toggle_checkbox()<cr>')`

Thanks so much!
