### ISSUE TITLE
Can't use `dir` with a space in it

### ISSUE THREAD

**Issue by qwertzui11** [epwalsh/obsidian.nvim#77]
### 🐛 Describe the bug

As a new user I tried to set `dir` to the default obsidian-vault directory. This result in the error `Unknown option: Vault`. 

```lua
      require('obsidian').setup {
        dir = "~/Documents/Obsidian Vault/",
        completion = {
          nvim_cmp = true, -- if using nvim-cmp, otherwise set to false
        }
      }
```

### Versions

nvim 0.8.2
obsidian-plugin 1.6.1

Thx for the great plugin!

**Comment by gerryhernandez** [comment]
Where/when are you seeing the error? Is it at startup, or is it when you try to perform an action?

**Comment by qwertzui11** [comment]
on startup when loading the plugin

**Comment by gerryhernandez** [comment]
There you go! 😎

**Comment by qwertzui11** [comment]
thank you, for the quick fix! 😍
