### ISSUE TITLE
Allow Subcommands with completions.

### ISSUE THREAD

**Issue by Muizzyranking** [epwalsh/obsidian.nvim#790]
### 🚀 The feature, motivation and pitch

I recently started using this plugin and I really love it and there are sometimes I would want to use a particular command and using tab to find the command is really messy.

I do not know if I should put this upon myself to get it done. I feel like I might not be able to write an acceptable code and that is why I am opening this issue.

There should be just one command `Obsidian` and there should be subcommand, e.g
`Obsidian new`
`Obsidian check`

I think this would be cleaner and less annoying to work with when using tab completion. Thank yout.

**Comment by Dardanos-Aeolus** [comment]
seems like a duplicate of this:
https://github.com/epwalsh/obsidian.nvim/issues/662
with this fix:
https://github.com/epwalsh/obsidian.nvim/pull/668

**Comment by Muizzyranking** [comment]
Oh. Thank you.
