### ISSUE TITLE
Error in init.lua:77: attempt ot compare number with boolean (ripgrep check fails)

### ISSUE THREAD

**Issue by Mrcuve0** [epwalsh/obsidian.nvim#80]
### 🐛 Describe the bug

Hi! Thank you for your plugin!
I'm just getting started with Obsidian and encountered this error whenever I open (or close) a buffer containing a note in the vault folder (or switching to the note buffer from another buffer).

See screenshot, first line:
![Screenshot from 2023-01-10 14-37-07](https://user-images.githubusercontent.com/36898760/211581442-14d758ad-4371-45a7-aa6d-a15d1355c3c3.png)

I took a quick look at the code, and as far as I understood we execute it everytime open a buffer containing a note in the vault. Anyway, the line that fails is:

```lua
  if os.execute "rg --help" > 0 then
    echo.err "Can't find 'rg' command! Did you forget to install ripgrep?"
  end
```
**I do have ripgrep installed.**

I tried running `os.execute()` inside nvim and I get the following:
![Screenshot from 2023-01-10 15-34-08](https://user-images.githubusercontent.com/36898760/211582650-d9b675ce-94e7-4890-8bdc-3a8ddc73e3c8.png)
So the issue must be in the parsing of the return code.

`:h os.execute` gives us:
![Screenshot from 2023-01-10 15-34-51](https://user-images.githubusercontent.com/36898760/211591481-4ee22296-a7b3-40b6-9c8d-481e752a26a6.png)
As far as I understand, to cover all cases one should test Linux, MacOS, Windows (?) and many of the possible shell combinations (bash, sh, fish, zsh etc). Seems a bit cumbersome. Since the use of ripgrep is optional and it is clearly specified in your readme, maybe this check is not even so important.

I tried fuzzy searching in all the plugins I have and none seem to implement a similar check (would have been cool to copy paste their solution). Even telescope does not seems to enforce it as a requirement.

---

Sorry I didn't provide you a snippet of code issuing the error, but you probably got the point anyway ahah

### Versions

`nvim --version`

```
NVIM v0.8.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.8.1/redhat-linux-build/cmake.config -I/builddir/build/BUILD/neovim-0.8.1/src -I/usr/include -I/usr/include/luajit-2.1 -I/builddir/build/BUILD/neovim-0.8.1/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.8.1/redhat-linux-build/include
Compiled by mockbuild@koji

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

`nvim --headless -c 'lua print(require("obsidian").VERSION)' -c q`

`1.6.1`

**Comment by epwalsh** [comment]
Hey @Mrcuve0, thanks for all the details. I'm going to remove the check like you suggested: #81 

I can't believe `os.execute()` doesn't have a consistent return type... 😞
