### ISSUE TITLE
Option to disable todo list conceal

### ISSUE THREAD

**Issue by LuisA92** [epwalsh/obsidian.nvim#83]
### 🚀 The feature, motivation and pitch

Is there any way to disable the concealling of todo list characters?

**Comment by epwalsh** [comment]
Not at the moment, but I'd be happy to accept a PR

**Comment by Chaitanyabsprip** [comment]
I'm lost, I've been trying to get todo list conceal for two days now, just installing this plugin didn't work, I have been searching reddit and google for an easy solution that I could hack together. Anyway, this is an inbuilt functionality? How do I enable this?

**Comment by epwalsh** [comment]
Hey @Chaitanyabsprip, you might also need `vim-markdown`. Can you try installing that and then see if it works? https://github.com/preservim/vim-markdown#installation

**Comment by Chaitanyabsprip** [comment]
I came back to this plugin after a long time, earlier I had figured out the conceal with treesitter, now I've done away with that in favour of using the additional_vim_regex_highlighting config param in treesitter highlight module. That must be the source of conceal for OP as well.

**Comment by epwalsh** [comment]
This is now configurable. See the `ui` options.
