### ISSUE TITLE
[Feature] Implement `ObsidianOpen` for Windows

### ISSUE THREAD

**Issue by pidgeon777** [epwalsh/obsidian.nvim#84]
### 🚀 The feature, motivation and pitch

Actually, when running `ObsidianOpen` in Windows 10 Pro, the following error is generated:

```
[Obsidian] open command does not support this OS yet
```

**Comment by epwalsh** [comment]
@pidgeon777 I'm not sure. There's no mention of that in the [docs](https://help.obsidian.md/Advanced+topics/Using+obsidian+URI).

**Comment by pidgeon777** [comment]
@epwalsh Does this behaviour happen with your setup as well?

**Comment by epwalsh** [comment]
No, for me it seems to always open in visual mode

**Comment by pidgeon777** [comment]
Ok, I'll reset all the options and disable all plugins, and try again.
