### ISSUE TITLE
[Obsidian] failed opening Obsidian app to note

### ISSUE THREAD

**Issue by TJohn0312** [epwalsh/obsidian.nvim#92]
### 🐛 Describe the bug

I'm not quite sure whats going on here, echo ping google works, and I've disabled my windows firewall to wsl so it can talk to Firefox and my local machine. 

Do I need any other configurations or prerequisites for ObsidianOpen?

any suggestions on what I should try?

#### nvim --version
NVIM v0.9.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

#### nvim --headless -c 'lua print(require("obsidian").VERSION)' -c q
1.7.0

**Comment by epwalsh** [comment]
Hey @TJohn0312, you shouldn't need any other dependencies for `:ObsidianOpen`. Can you try calling the "open" command directly? On Mac, for example, this would be something like `open -a /Applications/Obsidian.app obsidian://open?vault=my-vault&file=my-file`

**Comment by TJohn0312** [comment]
wsl came with xdg-open by default, but I guess it doesn't link opening windows apps.
installing wslu fixed it
-Thanks
