### ISSUE TITLE
Relative module name requires are not correct

### ISSUE THREAD

**Issue by folke** [epwalsh/obsidian.nvim#93]
This line is not correct. You should just do a `require("deps.lua_yaml.yaml")` here instead. In Lua, there's no such thing as relative module names.

https://github.com/epwalsh/obsidian.nvim/blob/3d459708c77f9ce7ae7165dda07812e685f30d61/lua/obsidian/yaml.lua#L1

This actually works by accident with the default Neovim loader, since it will replace dots by forward slashes and append the full lua path. So it will try loading
`.../lua////deps/lua_yaml.lua`, but as you can see that doesn't really resolve the relative paths. It just works by accident.

The lazy loader works correctly and interpreted the module as `...deps.lua_yaml`, since forward slahes in module names are interpreted the same as a `.`

Due to this that file could not be loaded.

I added a work-around (hack) to lazy for now, but you should really fix this anyway.

See also https://github.com/folke/lazy.nvim/issues/543

**Comment by gerryhernandez** [comment]
Well I just learned something. Thanks for that!
