### ISSUE TITLE
Bundling other plugins is considered bad practice

### ISSUE THREAD

**Issue by folke** [epwalsh/obsidian.nvim#95]
### 🐛 Describe the bug

I noticed you bundle plenary as part of obsidian.nvim in #18

This is not great.

If the user also has plenary installed, then depending on the loading order, the bundled plenary or the user's version will be used.

Additionally, having a top-level lua directory called `deps` is also far from ideal. Would've been better to at least put it in the `obsidian` namespace.

Maybe you just don't fully understand how plugins work in Neovim?

`/lua` is shared amongst all plugins, and won't be just visible to your own plugin.

### Versions

I noticed you bundle plenary as part of obsidian.nvim in #18

This is considered a bad practice.

**Comment by epwalsh** [comment]
I'm not an expert in Lua or Neovim, just learning as I go. PRs are always welcome, snark is not. ✌️

**Comment by folke** [comment]
It was not my intention to be snarky? I've seen other people that also didn't fully understand how plugins work and thought that everything inside their own `/lua` folder was sandboxed. But that's not how the `/lua` folder works.

I'll close this issue since I actually don't use obsidian, but still want to make sure you understand that depending on loading order, you may override the user's installed version of plenary.

**Comment by epwalsh** [comment]
I'm keeping this open as it's a legitimate concern
